### ISSUE TITLE
admin interface

### ISSUE THREAD

**Issue by posativ** [posativ/isso#10]

**Comment by mkzero** [comment]
*bump* Still no progress?

**Comment by danikvsn** [comment]
Have you given thought about using Django for your project? It automatically sets up an administrator interface that you can customize

**Comment by daniyyz** [comment]
Hi All, i was looking into the notification.py file, where the url's are generated for Delete or Activate emails, for moderated comments. 

It seems, for this topic, the simplest admin interface would be a looping through of all those URL's and turning them into HTML. then we can click and do stuff via a webpage. 

I'm new to the code, so don't know yet the best place for something like that, but i'll keep poking around.

Thx,
m
