### ISSUE TITLE
use Waitress as default web server in quickstart

### ISSUE THREAD

**Issue by posativ** [posativ/isso#120]
The current quickstart document uses Isso behind nginx, but the quickstart should not cover any web server at all. Instead, the installation guide can recommend the installation of [Waitress](https://pypi.python.org/pypi/waitress), so Isso can run on public interfaces.

**Comment by ix5** [comment]
There are several documented ways of running Isso now, either behind a proxy server or via e.g. uwsgi, gevent, gunicorn.
