### ISSUE TITLE
URI queries return 404 responses

### ISSUE THREAD

**Issue by nikonyrh** [posativ/isso#125]
The HTTP GET to "/js/embed.min.js" works as intended, but the browser-generated "/?uri=%2Ftest.html&nested_limit=5" returns this:

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Isso is run in Ubuntu 12.0.04 by an init.d script & gunicorn with a proxying Nginx. Have you seen this before and do you have any debugging tips? I tried to set the "name" and host in isso.conf but I was unable to confirm this configuration because query to /main returns 404 error as well.

**Comment by ix5** [comment]
This should be fixed by https://github.com/posativ/isso/pull/565
