### ISSUE TITLE
Bad request when trying to post a new comment with an incorrect value for website

### ISSUE THREAD

**Issue by Zimmi48** [posativ/isso#131]
Hello,
If, for instance, you type google (not google.com) in the website field and try to post your comment, the comment won't post but it does not show any error message such as "Please correct the website field before posting".
What happens is that the server reject the post (400 BAD REQUEST) and this makes the JS fail:

<pre>SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data</pre>

<pre>var create = function(tid, data) {
        var deferred = Q.defer();
        curl("POST", endpoint + "/new?" + qs({uri: tid || location}), JSON.stringify(data),
            function (rv) { deferred.resolve(JSON.parse(rv.body)); });
        return deferred.promise;
    };</pre>

Correcting this would require adding a field validation client-side in the JS, I think.
Thanks.

**Comment by matlink** [comment]
I got the same issue only on one article. I don't know why this is happening only on this article. What is the source of the problem ?

**Comment by posativ** [comment]
403 is not a "Bad Request", but an invalid JSON request (e.g. wrong email address or the email/website URL is too long). The patch is not available on PyPi yet, I have to prepare a new release.

**Comment by matlink** [comment]
Well, it only happens when the URL of the website running ISSO is too long, even if the comment has only a short body (3 char for example) and nothing else.

**Comment by posativ** [comment]
What do you mean by "too long"? 255 characters? Less?

**Comment by matlink** [comment]
Not that long : 

      "refonte-du-blog-du-pgcd-avec-pelican.html"

**Comment by posativ** [comment]
Can you use the website inspector and see what is in the actual response from Isso? I don't think your issue is related to #131 (this ticket).

**Comment by ix5** [comment]
@matlink @Zimmi48 is this still a current issue?

**Comment by Zimmi48** [comment]
Sorry, I wouldn't know. I haven't used isso in years.

**Comment by ix5** [comment]
Closing in favor of https://github.com/posativ/isso/issues/673, which is quite similar
