### ISSUE TITLE
No comments inserted when importing from Disqus

### ISSUE THREAD

**Issue by pvorb** [posativ/isso#135]
`isso -c /etc/isso.conf import comments.xml` runs without any error but no comments are added to the database. I checked the sqlite comments db. The tables are available, but there are no comments.

**Comment by spookylukey** [comment]
As further input, I have an export that has empty `<id>` from some posts, and not from others.

I **think** the pattern is:
* really old threads, from an old import have a numeric id e.g. `<id>15</id>`
* all newer threads from recently created posts have an empty id `<id />`

So it would be nice if the import could deal with this without having to pass a flag.
