### ISSUE TITLE
Isso does not find the correct page title

### ISSUE THREAD

**Issue by funkenstrahlen** [posativ/isso#139]
Mail title is generated by this method:

``` python
def thread(data, default=u"Untitled.", id=None):
    """
    Extract <h1> title from web page. The title is *probably* the text node,
    which is the nearest H1 node in context to an element with the `isso-thread` id.
    """

    html = html5lib.parse(data, treebuilder="dom")

    ...
```

https://github.com/posativ/isso/blob/7701dafa136c0cbe5338b1a5546ab58afbbaadb0/isso/utils/parse.py#L23

All my mails are titled "Untitled." despite I only use `<h1>` a single time on the whole webpage. Example page: http://funkenstrahlen.de/blog/2014/11/05/liste-von-videos-mit-youtube-dl-laden/

Check with

```
curl "http://funkenstrahlen.de/blog/2014/11/05/liste-von-videos-mit-youtube-dl-laden/" | grep h1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7814  100  7814    0     0   122k      0 --:--:-- --:--:-- --:--:--  123k
  <h1 class="post-title">Liste von Videos mit youtube-dl laden</h1>
```

How can I improve my page, so it shows the correct title in mails?

**Comment by rhester72** [comment]
I've been testing isso for a few months now, on Pelican (static-generated Python) and Ghost (dynamic Node.js) without issue.  Tonight, I tested a theme called Ghostium that utilizes pjax, and after that, I started getting the "Untitled." emails, despite there being only one H1 element on the page.  However, the threads table in sqlite _does_ say Untitled. on mine.  The stranger part is that I reverted the theme back to the default (Casper), cleared browser and server cache, restarted isso and the web server, and even deleted the entire comment database, yet the problem persists, even though the environment has been fully restored to what was previously a working state.  I'm stumped.

**Comment by rhester72** [comment]
In thinking about this a bit more, is there no way at post time for us to pass the post title through directly via something similar to data-isso as part of the script itself?  Nearly every blogging system I'm familiar with makes provision to expose the title, which would save on a lot of guesswork.

**Comment by posativ** [comment]
Don't trust the user, that's why the title guessing is done server-side. I plan to implement an option to trust user input on the title of a thread. But the user can simply fake the data.

**Comment by rhester72** [comment]
I'm not talking about trusting the user.  In Ghost terms, I mean something more like:

    <script data-isso="//www.multics.us/isso/" src="//www.multics.us/isso/js/embed.min.js" title-isso="{{url}}"></script>
    <section id="isso-thread"></section>

where title-isso is a new argument explicitly expressing the title.  Is there some security ramification I'm not seeing?

**Comment by rhester72** [comment]
This is an example of the sole H1 on the page in question that is being 'missed':

    <h1 itemprop="name headline" class="post-title"><a href="/ghosttest/kickstart-revival-now-hosted-by-cloanto/" itemprop="url" data-pjax title="Kickstart Revival now hosted by Cloanto">Kickstart Revival now hosted by Cloanto</a></h1>

I suspected the use of pjax dynamic loading could be affecting the javascript's ability to "see" the post, but I've disabled pjax entirely with no change in result.

**Comment by posativ** [comment]
The attribute `isso-title` is parsed from the server and never submitted by the client. If the user submits a comment for some URL, Isso checks retrieves the site once to scrape the title. This may fail on JavaScript-heavy websites (e.g. Ghost).

Can you paste the whole HTML for the site?

**Comment by rhester72** [comment]
Here is an example live page:

https://www.multics.us/ghosttest/kickstart-revival-now-hosted-by-cloanto/

**Comment by hkockerbeck** [comment]
If the extraction of a specific `h1` element seems to prove problematic in some cases, maybe extracting the `title` element from the HTML `head` is a feasable alternative? I'd reckon `title` to be unambigious (compared with potentially multiple `h1`) and less likely to be heavily handled by JavaScript. 

Maybe there could be an additional setting? Something along the lines of `notification-title` with possible values `page-title`(`title` element), `page-headline` (`h1` element) and `custom` (a custom string in another setting, say `custom-notification-title` with e. g. `A new comment on my nice little blog!`.

**Comment by shiba89** [comment]
Wouldn't it be more appropriate to retrieve the text inside \<title\>\</title\>?

**Comment by remcoboerma** [comment]
Isn't this were opengraph comes in? http://ogp.me/

**Comment by mdosch** [comment]
Same for my [blog](https://blog.mdosch.de/) but after using isso-title it works. But only for comments on previously uncommented threads as others are already stored as untitled. Is there any possibility to force isso to update the titles?

**Comment by NerosTie** [comment]
An update of Ghost or Isso breaks something and now Isso doesn't find the title anymore. The value is `NULL` in the `threads` section of the database.

I use nothing fancy, just Ghost+Casper+Isso on Raspbian. Any idea how to fix that?

**Comment by ix5** [comment]
As mentioned in https://github.com/posativ/isso/issues/497, passing the title from the client via `data-title` is now possible.
