### ISSUE TITLE
check browser compatibility and fail gracefully

### ISSUE THREAD

**Issue by posativ** [posativ/isso#14]

**Comment by ix5** [comment]
Since Isso is still built using ancient technologies, most browsers nowadays should be able to render it correctly.

I have seen quite some people using messages such as "Isso comments needs Javascript to work" in the wild, that might be something to put into the docs.

**Comment by posativ** [comment]
Absolutely.

I think the web is almost unusable without JavaScript nowadays. User with JavaScript disabled are 99% very tech-savvy and should understand how this software works internally.
