### ISSUE TITLE
Newlines within comments

### ISSUE THREAD

**Issue by Zimmi48** [posativ/isso#145]
Hello,

Currently the default behavior is (like in classic Markdown) to make new paragraphs from double newlines but to discard single newlines.
Is there a simple way to create <br> from newlines like in GitHub's flavored Markdown?

Thanks!

**Comment by ix5** [comment]
This should be fixed by the introduction of html render flags for misaka (`hard-wrap ` / `HTML_HARD_WRAP`)

See https://github.com/posativ/isso/blob/e6dbd21819f8fdca9fdace447e9ba01276e8d6a9/docs/docs/configuration/server.rst#markup
