### ISSUE TITLE
Add a X-Isso header when requesting

### ISSUE THREAD

**Issue by Hywan** [posativ/isso#151]
It helps to hack when needed :-).

Thanks!

**Comment by posativ** [comment]
I've decided against "X-Isso", but included a user agent string "Isso/x.y (+http://...)".

**Comment by Hywan** [comment]
:+1:

**Comment by Hywan** [comment]
Any opened issue?

**Comment by posativ** [comment]
It is in the version on PyPi already.

**Comment by Hywan** [comment]
w00t! Thanks :-).
