### ISSUE TITLE
POST 400 (BAD REQUEST) 

### ISSUE THREAD

**Issue by sevko** [posativ/isso#153]
**isso** is installed and running, but comments/replies will sporadically fail to post with the following error ([here is my test page](http://sevko.io/articles/power-set-algorithms/)):

```
POST http://comments.sevko.io/new?uri=%2Farticles%2Fpower-set-algorithms%2F 400 (BAD REQUEST) comments.sevko.io/new?uri=%2Farticles%2Fpower-set-algorithms%2F:1

Uncaught SyntaxError: Unexpected token < embed.dev.js:903
```

The culprit line is `function (rv) { deferred.resolve(JSON.parse(rv.body)); });`, in:

```
var create = function(tid, data) {
    var deferred = Q.defer();
    curl("POST", endpoint + "/new?" + qs({uri: tid || location}), JSON.stringify(data),
        function (rv) { deferred.resolve(JSON.parse(rv.body)); });
    return deferred.promise;
};
```

Turns out the server's response was:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Website not Django-conform</p>
```

Here's my `isso.cfg`:

```
[general]
dbpath = /var/lib/isso/comments.db
host = http://sevko.io/
```

And the relevant bits of my `nginx.conf`:

```
server {
    listen 80;
    server_name sevko.io;
    root /var/www/sevko.io/_site;
    index index.html;
    charset UTF-8;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}

server {
    listen 80;
    server_name comments.sevko.io;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by sevko** [comment]
Classic. Posted this issue only to resolve it seconds later: I was entering junk data in the optional "website" text box, which triggered [this](https://github.com/posativ/isso/blob/master/isso/views/comments.py#L139).

**Comment by sevko** [comment]
@posativ , are error messages on the cards for things like this?

**Comment by posativ** [comment]
Yes, as a workaround the next release will not parse the HTML response but rather print the exact error message (in this case, not django-conform).

Improved error messages on the client-side is on the roadmap.

**Comment by fseasy** [comment]
it's just because the `website` info is invalid. the error is not ok...

**Comment by ix5** [comment]
I agree, there should at least be a warning in the client UI.

**Comment by ix5** [comment]
Closing in favor of https://github.com/posativ/isso/issues/673
