### ISSUE TITLE
[Feature request] Improve error message when data-isso is is formatted wrong

### ISSUE THREAD

**Issue by matlink** [posativ/isso#155]
Hello,
I installed ISSO on my machine and embedded it into my blog. As far as I am, comment form shows up (meaning that javascript embed file is loaded), but when I'm trying to post a new comment, it says me in the JS console "TypeError: i is not a function               embed.min.js:67".
Does someone know from where this error is ?
My server is listening like this : 

```
root /var/www/blog_pgcd/;
index index.html;
location /comments {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Script-Name /comments;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://127.0.0.1:8095;
}
```

Thanks.

**Comment by matlink** [comment]
Typo in the title

**Comment by posativ** [comment]
Can you use `embed.dev.js` instead of the minimized version?

**Comment by matlink** [comment]
Hum, I reinstalled ISSO with the PIP installer. Seems to work now. I was using a .deb version of ISSO distributed by someone else.

**Comment by matlink** [comment]
Sounds like <script data-isso="//comments.example.tld/" doesn't like to having a trailing slash at the end of the data-isso string between quotes :)

**Comment by posativ** [comment]
That should be fine, I am using a trailing slash for my API endpoints.

**Comment by matlink** [comment]
Oops, I meant trailing space :)

**Comment by posativ** [comment]
Oh ok, please leave this issue open, I'll provide a more useful error message.

**Comment by ix5** [comment]
Error message looks okay now
https://github.com/posativ/isso/blob/0b0737802b45e6602627d30d95454839dc708bb2/isso/js/app/api.js#L23-L26
