### ISSUE TITLE
Check for all older versions of html5lib instead of just 0.95

### ISSUE THREAD

**Issue by jethrogb** [posativ/isso#168]
In https://github.com/posativ/isso/blob/master/isso/utils/html.py#L48 there's a check for html5lib being version 0.95. That should be being <=0.95.

**Comment by jethrogb** [comment]
I don't understand this fix. You just increased the dependency requirements for no reason, while the alternate code path works perfectly fine for older versions of html5lib.

**Comment by posativ** [comment]
I can confirm that html5lib 0.95 (or higher) works. For example, 0.95 to 0.999 broke compatibility, so I don't see a reason to support versions that are not tested (by the autor) and quite old.

**Comment by jethrogb** [comment]
0.90 is in Debian oldstable and Ubuntu 12.04 LTS

**Comment by posativ** [comment]
Update or use a virtualenv.

**Comment by posativ** [comment]
I've added support for older html5lib (expect a maintenance release soon (tm)). If it breaks somewhere else, I will drop support for 0.95 entirely. I don't have the time to maintain compatibility with LTS version of certain distributions, when you can use virtualenv.

**Comment by jethrogb** [comment]
Thanks :)
