### ISSUE TITLE
usability minors

### ISSUE THREAD

**Issue by posativ** [posativ/isso#17]
- [ ] email address is actually only a private identifier to generate the same identicon again
- [ ] blank identicon changes to identicon from IP address changes to identicon from mail address -> not really intuitive on first evaluation
- [x] remove comment but still hovering the button reverts to original state after ~1 second
- [x] when replied to a comment, scrollIntoView doesn't work as expected (scrolled half page after document end)
- [ ] when you vote multiple times on a comment, you should get a appropriate error message

**Comment by ix5** [comment]
- Error messages should be part of https://github.com/posativ/isso/issues/673
- An explanation of email addresses and what fields get used/displayed on the client side are in need of an overhaul, probably also belong in #673
