### ISSUE TITLE
(Discussion) lazy load isso on scroll

### ISSUE THREAD

**Issue by Armonth** [posativ/isso#178]
The next link is about implementing on Disqus but can give ideas about how to setup "lazy loading" in Isso: http://www.am22tech.com/load-disqus-on-scroll/

This ticket is for the need of discussion and implement of this feature as enable/disable option:

**Benefits of using lazy load:**
- Better load times (don't load if user don't scroll to comment section).
- Most important one: **usability**. Most users when reading a article/post on a blog eye-calculate the % of article readed and the remaining using the scrollbar.
  
  If comments are not loaded until end article (on scroll) they can use scrollbar that way. If article is short (ie: 500 words) but then you load 100+ comments, user can't guess how much % article is readed right now.

**Drawback**
- The only notable drawback of implementing (and use!!) lazy load is **in theory** a loss in SEO because googlebot (again, in theory) don't scroll and get comments content. But that can be a advantage if you don't want comments affecting seo... or SEO is not a issue for you.
  
  The other drawback is about loading comments with JS if user don't allow JS... but anyway isso uses js for loading comments so that issue is the same with that option enabled or not and with all JS based systems...

**Comment by ix5** [comment]
Documented lazy-loading in https://github.com/posativ/isso/pull/684
