### ISSUE TITLE
Export generated HTML

### ISSUE THREAD

**Issue by zackw** [posativ/isso#181]
I'd like there to be an API entry point which causes the server to spit out the fully-formatted HTML for the _entire_ comment tree for a particular article.  The client script should notice that a page already contains a comment tree, and retrieve and inject only newer comments.  This would enable me to integrate isso with a static site generator such that _reading_ comments (older than some time window) did not require JavaScript.

**Comment by dertuxmalwieder** [comment]
^ Seconded. Some of us are paranoid and disapprove having to enable browser backdoors just to read text.

**Comment by blatinier** [comment]
Dup of #331
