### ISSUE TITLE
feature request : Standalone Pod and white list

### ISSUE THREAD

**Issue by Proxiweb** [posativ/isso#188]
Hello,

I need :

A way to configure a standalone pod which can't communicate with other pods.
A way to create a white list of pods the pod is authorized to talk.

Use case : I would like to install a pod for a school / a list of school.

**Comment by posativ** [comment]
Wrong issue tracker? This isn't Diaspora*

**Comment by Proxiweb** [comment]
sorry, too much tabs opened...
