### ISSUE TITLE
Is it possible to have nested comments

### ISSUE THREAD

**Issue by kumarbalap** [posativ/isso#190]
I love the app, clean and excellent work.
But, I found that it doesn't have the nested reply, whatever the reply we do in any level, it goes to the parent, I mean only one chain.

Am I missing anything? I have tested in the demo site.

Thanks,
Bala

**Comment by srijan** [comment]
Isso does not have this feature by design. Please have a look at #79.

**Comment by blatinier** [comment]
Dup of #210
