### ISSUE TITLE
comments on hashed url's ?

### ISSUE THREAD

**Issue by jkanche** [posativ/isso#192]
If i'm using a front end framework( ember) where routes are usually hashed. 

Is there a way to setup isso to save comments on applications that use hashed url's ?

**Comment by jkanche** [comment]
I kind of hacked the code a little bit to get it to work the way i want it to, but i was wondering if there is a better way to do this --

update location in api.js to use window.location.hash instead of window.location.pathname

since every URI is verified to be valid, comment out the code in the new method in the file isso/views/comments.py

               #with http.curl('GET', local("origin"), uri) as resp:
                    #if resp and resp.status == 200:
                        uri, title = parse.thread(resp.read(), id=uri)
                    # else:
                    #    return NotFound('URI does not exist')

**Comment by posativ** [comment]
No better way, currently.

**Comment by ix5** [comment]
See https://github.com/posativ/isso/issues/345, should be fixed by https://github.com/posativ/isso/pull/452 and a bit of adjustments in your framework.
