### ISSUE TITLE
Port from httplib to requests

### ISSUE THREAD

**Issue by mathstuf** [posativ/isso#193]
The problem I'm running into is that isso is getting 301 redirection status codes which makes isso claim "No URL". I tried changing just `utils.http` to use requests, but it looks like the API is just not compatible with httplib, so a larger change will be needed.

**Comment by mcepl** [comment]
Instead of the cargocultic switching to ``requests`` could you please describe what exact error happens to you? Of course, ``httplib`` can deal with 301 redirect correctly, or in whatever way you want.

**Comment by mathstuf** [comment]
It's been a while, but the response was probably straight 301 response instead of doing the redirect follow (I do http -> https via 301 on my server).

**Comment by mcepl** [comment]
Is http://www.diveintopython.net/http_web_services/redirects.html what you are looking for?

**Comment by mathstuf** [comment]
It would seem so.
