### ISSUE TITLE
Cant show Isso in Swedish

### ISSUE THREAD

**Issue by gntech** [posativ/isso#197]
Hi,
I am running isso 0.9.10 on my site and even though a swedish translation exists i cant make it visible. It defaults back to english when i set data-isso-lang="sv"

```
<script
  data-isso="/comments"
  data-isso-vote="false"
  data-isso-lang="sv"
  src="/comments/js/embed.min.js">
</script>
<section id="isso-thread"></section>
```

Ref: https://github.com/posativ/isso/commit/7f5ff457c1c1ba0d86031615314153c70d2f138c

**Comment by posativ** [comment]
Do you have a link to your `embed.min.js` file?

**Comment by gntech** [comment]
http://gntech.se/comments/js/embed.min.js

**Comment by posativ** [comment]
I doubt you run 0.9.10, you only have de, en, fr, it, eo and ru.

**Comment by gntech** [comment]
That is strange. I have installed isso in a virtualenv using pip. Is there
some way to verify which version is acutally installed?

Mvh Gustav Näslund
Tel. 073 5195 266

2015-08-25 10:59 GMT+02:00 Martin Zimmermann <notifications@github.com>:

**Comment by gntech** [comment]
Turns out the Swedish translation isnt available in the 0.9.10 release after all. I just assumed since the pull request was accepted Before the release.
https://github.com/posativ/isso/blob/0.9.10/isso/js/app/i18n.js
Is it possible to do a new release with updated translations?

**Comment by posativ** [comment]
Yes, exactly. I'll try to publish a new release today.

**Comment by gntech** [comment]
Thats great, thanks! :+1:

**Comment by gntech** [comment]
@posativ is there some way I can help out with the new release?

**Comment by posativ** [comment]
Next week might be possible, I need to fix a few things for the master (most translations are submitted to the master branch), especially #191 (if you have an idea on how to simply extend the dom without wrapping all methods, let me know).
