### ISSUE TITLE
Conflict with bootstrap dropdowns

### ISSUE THREAD

**Issue by pozitron57** [posativ/isso#203]
I've installed Isso on my website, it is fantastic, thank you very much for the work!

The only issue I have with it: if comments are on the page, then dropdown bootstrap menus behave weird. One can click on it, then click to any other part of the window (including other dropdown) will **compeletely remove** the dropdown entry. Well, it will just disappear. You can try it [here](http://lisakov.com/test-isso.html). And if the comments are not present on the page, everything is OK (see e.g. [main page](http://lisakov.com), it is in Russian but you only need to click on the dropdown).

 Any ideas?

**Comment by posativ** [comment]
Yup, see https://github.com/posativ/isso/pull/191. The proposed patch works, I think. I've seen your other PR, I'll review it when I get home in a few days.

**Comment by pozitron57** [comment]
It works, thanks!
