### ISSUE TITLE
Using Isso JavaScript client with an alternative backend

### ISSUE THREAD

**Issue by sprin** [posativ/isso#205]
Two months ago, I was looking for an open source JavaScript comment widget and backend for my personal sites, and I found Isso to be the best option (polished widget, great docs, actively maintained). However, the requirement for SQLite was a blocker. SQLite is not a good fit for my desired architecture. My reasons are pretty much the same as [outlined by Heroku](https://devcenter.heroku.com/articles/sqlite3). I looked at modifying Isso to use SQLAlchemy to support both PostgreSQL and SQLite backends, but these changes would have to run fairly deep since there are some SQLite-specific patterns: use of locks for concurrency control, BLOB type (pg has [bytea](http://www.postgresql.org/docs/9.4/static/datatype-binary.html)), PRAGMA statements, triggers. I am also not a fan of applications that take the "lowest common denominator" approach to databases, since they necessarily miss out on database-specific features that can provide big benefits in speed, space, and implementation simplicity.

So while I think SQLite is a great fit for many people due to its operational simplicity, I decided to write a PostgreSQL-driven comment backend, also in Python. And along the way, I wanted to create an architecture that allows changing almost any aspect of the application behavior through a plugin system. I just published the project, tentatively named "pg-discuss" ([readthedocs](https://pg-discuss.readthedocs.org/en/latest/), [github](https://github.com/sprin/pg-discuss)). I have yet to publicize it: I wanted to run some things by Martin and other Isso contributors and users first.

First, there's no included JavaScript widget, nor do I want to create a new JS widget. I want to recommend users to use the Isso JavaScript client. There is an [included extension](https://pg-discuss.readthedocs.org/en/latest/_modules/blessed_extensions/isso_client_shim.html) that "shims" the API to match the expectations of the Isso client. Is there any objection to shipping a built version of the Isso client with this project, along with appropriate credit and links back to the Isso project?

Second, I would like to contribute to the Isso client, such as being able to configure: which input fields display, markdown preview, allowed nesting level, OAuth 2.0 hooks, lazy loading. It is possible that some of these things would be out of scope with the Isso backend. Is there a way we can add these as optional features to the JS widget, even if they may be out of scope for the Isso backend?

Finally, I am hoping these two projects can collaborate and cross-promote. While they are both MIT-licensed comment systems in Python with JS embeds, I feel they occupy different niches. Isso has a great story for easy installation on your own hardware because of SQLite, the built-in WSGI server, and because it is packaged for Debian. Configuration of Isso is very straightforward. pg-discuss has better stories for extensibility via plugins, production-grade storage, and running multiple instances. However, plugin installation and configuration adds some complexity.

Thanks for Isso, it has been a huge inspiration!

**Comment by posativ** [comment]
Hi Steffen,

good to see new development! I've only glanced over pg-discuss, but I agree with your points. There is a develop branch that uses SQLAlchemy (though I'm not very happy with it in terms of library size). Also, I am not very happy with the current state of Isso. I would like to see a spec that defines the API (server-client) and general interaction model (e.g. required minimum setup for comments and optional extensions, e.g. authentication (OAuth, whatever).

I am currently limited on time for this project and I hope we can indeed collaborate. The current server architecture needs rework and I would like to fix a few design issues, too:

* requirement to GET the website and retrieve the title
* using bloom filters to store votes

I like to hear your opinion on the API and in general of the concept. Isso is still in 0.x.y and I have a few ideas/change requests (e.g. interchangeable markup w/ hints as you mentioned, configurable url validation for threads and anti spam) before making a 1.x release.

But the core of Isso needs to be minimal (not pulling weird dependencies, e.g not depending on some third-party webservice, easy deployment).

**Comment by reubano** [comment]
Very interested in this thread. I was looking for Disqus alts and came across this. I would love the ability to write plugins to add support for things like gravatars and social logins, and the ability to write engines for different backends. Any updates since the last comment?

**Comment by sprin** [comment]
@reubano: pg-discuss has matured to the point where the core API should not change much. I will support whoever would like to write an extension. The default frontend for pg-discuss is currently a slightly modified Isso client. I would like to contribute these little changes back to Isso while preserving compatibility - being able to use the same JS frontend for both Isso and pg-discuss backends is a goal of mine. As to your specific topics:

user icons (eg. gravatar): This would require some changes to the Isso JS frontend. Perhaps an option to configure an icon provider URL in lieu of the JS-generated icons? This is mentioned in the Isso FAQ: https://github.com/posativ/isso/blob/HEAD/docs/faq.rst. The backend (Isso or pg-discuss) would also need to know which value(s) to hash, based on what the provider is expecting.

social logins: You can write an identity provider extension to pg-discuss to authenticate users. It should be possible to write an OATH2 login, amongst others.

Different backends: Do you mean supporting different databases? The Isso backend is probably the best candidate to add support for multiple data stores: it uses SQLite now, but I think @posativ would be open to using a database abstraction layer as long as it is simple and small. pg-discuss is very PostgreSQL-oriented. To take full advantage of Postgres features and also for performance reasons, extensions are allowed to use the PostgreSQL dialect via SQLAlchemy. pg-discuss could be adapted to other data stores, but it would have to be a fork with a different extension API.

**Comment by reubano** [comment]
@sprin I'm glad that pg-discuss is stable. I too would like to see any pg-discuss front end changes ported back to Isso. @posativ would it be possible to convert Isso to a stub repo that pulls in `front-end` and `back-end` submodules? That way pg-discuss (and others?), can pull in just the Isso front end dependency. It would also make it easier to contribute back if the front end was a sep repo.

Re social logins, how difficult would it be to implement your `identitypolicy` in Isso? I ask because I would like to support different dbs via sqlalchemy. I saw in a previous issue that there is such a branch. @posativ can you clarify on the issues you encountered implementing sqlalchemy? Also, would you be open to support multiple backends in Isso? If not, @sprin could you explain how to go about creating a "different extension API"?

**Comment by ix5** [comment]
Seems @sprin has diverted their attention elsewhere. pg-discuss development has seemingly stalled in 2016.

The issue for using a different database backend at https://github.com/posativ/isso/issues/61 is still open, but without the driving force of @sprin or contributors such as @reubano, I'm afraid the effort to make Isso's frontend pluggable into other backends will never be tackled.

Closing as such.
