### ISSUE TITLE
trouble with installing ISSO on Windows 7

### ISSUE THREAD

**Issue by butgit** [posativ/isso#206]
On my Windows 7 machine, I installed the three prerequisites for ISSO as instructed in the installation guide :

- Python 2.7
- SQLite 3.8.11.1
- VCForPython27.msi (a working C compiler)

After that, I executed the command  `pip install isso` in cmd prompt, yet the installation failed and spat out the following error messages:

```
Collecting isso
Requirement already satisfied (use --upgrade to upgrade): html5lib in c:\python27\lib\site-packages (from isso)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous in c:\python27\lib\site-packages (from isso)
Requirement already satisfied (use --upgrade to upgrade): configparser in c:\python27\lib\site-packages (from isso)
Collecting misaka (from isso)
  Using cached misaka-1.0.2.tar.gz
Collecting ipaddr>=2.1 (from isso)
Collecting werkzeug>=0.8 (from isso)
  Using cached Werkzeug-0.10.4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from html5lib->isso)
Building wheels for collected packages: misaka
  Running setup.py bdist_wheel for misaka
  Complete output from command C:\Python27\python.exe -c "import setuptools;__file__='c:\\users\\my_name\\appdata\\local\\temp\\pip-build-yd4aen\\misaka\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\my_name\appdata\local\temp\tmpa9aiiepip-wheel-:
  running bdist_wheel
  running build
  running build_ext
  building 'misaka' extension
  creating build
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\src
  creating build\temp.win32-2.7\Release\src\sundown
  C:\Users\my_name\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcsrc/misaka.c /Fobuild\temp.win32-2.7\Release\src/misaka.obj
  misaka.c
  src/misaka.c(235) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
  error: command 'C:\\Users\\my_name\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
  
  ----------------------------------------
Failed to build misaka
Installing collected packages: misaka, ipaddr, werkzeug, isso
  Running setup.py install for misaka
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\my_name\\appdata\\local\\temp\\pip-build-yd4aen\\misaka\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\my_name\appdata\local\temp\pip-ijrwml-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'misaka' extension
    C:\Users\my_name\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcsrc/misaka.c /Fobuild\temp.win32-2.7\Release\src/misaka.obj
    misaka.c
    src/misaka.c(235) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\my_name\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
    
    ----------------------------------------
```

I don't quite understand what these error messages are about. Could anyone give me some hint?

**Comment by sprin** [comment]
The compiler cannot find the so-called "C (C99) headers", which don't appear to be bundled with your version of VC++. This affects the compilation of any software which needs the C99 headers, including Python libraries which have C99 extensions such as [Misaka](http://misaka.61924.nl/). Misaka is the library used by Isso to render Markdown text.

You can still download free, open-source versions of the headers. Here are some relevant links:
https://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio
http://deeplearning.net/software/theano/install_windows.html#visual-studio-and-cuda

The last link says:
> Finally download the stdint.h header from [here](http://msinttypes.googlecode.com/svn/trunk/stdint.h) and save it as C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\include\stdint.h.

My advice: If you are just trying out Isso on this system, but you are going to install it on a more typical server OS, that's find. If your intent is to host Isso on this system, then I would say hosting a web app on Windows 7 is very atypical. Unless you are familiar with hosting web applications, I would recommend having someone else host Isso for you, either a friend or commercial "Platform-as-a-Service" (PaaS) provider. Hosting web apps yourself requires some work to secure your network, the operating system, and the application itself. Most people who DIY usually start with a well-configured router/firewall and a Linux or *BSD system running on a segmented network.

**Comment by butgit** [comment]
I really appreciate your detailed answer. I hope I had read your comment before I did it my way as follows:

1. I uninstalled VCForPython27 and installed Visual Studio Express 2015,
2. typed in `SET VS90COMNTOOLS=%VS140COMNTOOLS%` in the cmd prompt,
3. then `pip install isso`. 

It worked on my system. 

And as you mentioned, hosting on a Windows machine seems not very practical when it can be accomplished on Linux, BSD, etc. I'm just trying to integrate ISSO into my Jekyll build, which will be deployed to Github Pages. (Warn me if this sounds implausible.)

Thank you again, and I'm closing this issue as fixed.

**Comment by sprin** [comment]
> And as you mentioned, hosting on a Windows machine seems not very practical when it can be accomplished on Linux, BSD, etc. I'm just trying to integrate ISSO into my Jekyll build, which will be deployed to Github Pages. (Warn me if this sounds implausible.)

Jekyll will  render your content (eg, Markdown files) in to HTML. GitHub Pages will display the rendered content. And the Isso JavaScript client is perfect for embedding in those rendered pages. But on their own, neither Jekyll nor GitHub Pages has any way to run the Isso backend. The backend is a web service that has to run from an always-on server. GitHub doesn't offer any way to host the backend for you.

There is freedom and knowledge to be gained through hosting your own web apps. And there are also probably people who would host for free on terms acceptable to you if you asked. I might be one of them ;) Email preferred.

**Comment by butgit** [comment]
That means I need a server to run isso because Github pages does not provide end users backend services. I'm glad that you cleared up my misconception about what isso is not. Today I picked up from you some web terminology such as web apps, backend, etc. It's a real learning experience. :+1: 

By the way, it's generous of you to offer me the opportunity of free hosting. but I have let my AWS account lie fallow for some time, so your warm heart is enough.
