### ISSUE TITLE
local install via pip writes into wrong directories

### ISSUE THREAD

**Issue by wernermo** [posativ/isso#207]
Hi guys,

I'm not sure if this is a bug with isso or pip but I need to start somewhere so here I am.

I work for a hosting company named Uberspace and we got the following setup here:

```
[moritz@andromeda lib]$ python2.7 --version
Python 2.7.10

[moritz@andromeda lib]$ pip2.7 --version
pip 7.1.2 from /package/host/localhost/python-2.7.10/lib/python2.7/site-packages (python 2.7)

[moritz@andromeda lib]$ cat /package/host/localhost/python-2.7/lib/python2.7/distutils/distutils.cfg 
[install]
install_lib = ~/lib/python2.7
install_scripts = ~/bin

[moritz@andromeda lib]$ cat /package/host/localhost/python-2.7/lib/python2.7/site-packages/altinstall.pth 
import os, site; site.addsitedir(os.path.expanduser('~/lib/python2.7'))
```

So packages in userland _should_ be installed to `~/lib/python2.7`. That works fine usually but not with isso:

```
[moritz@andromeda ~]$ pip2.7 install isso --user
[...]
Successfully built isso itsdangerous misaka html5lib ipaddr configparser
Installing collected packages: itsdangerous, misaka, six, html5lib, ipaddr, configparser, werkzeug, isso
Successfully installed configparser-3.3.0.post2 html5lib-0.9999999 ipaddr-2.1.11 isso-0.9.10 itsdangerous-0.24 misaka-1.0.2 six-1.10.0 werkzeug-0.10.4

[moritz@andromeda ~]$ find ./lib -name \*isso\* 
./lib/python2.7/isso-0.9.10.dist-info
./lib/python2.7/home/moritz/lib/python2.7/isso
./lib/python2.7/home/moritz/lib/python2.7/isso/css/isso.css
```

It looks like the path gets expanded somehow and used two times here. Have you seen this before or have any idea how to fix this?

Regards,
Moritz

**Comment by posativ** [comment]
Hey Moritz,

I have the very same issue, Uberspace did a rollback last time it occured. They have no idea why this is happening. It is not Isso's fault as it is using a very simple install script.

As a workaround, you can use Python2.6 or pip-2.6 to install Isso. If you contactthe support, you can mention ticket number `#213061`. Probably a regression when they updated to 2.7.10.

**Comment by wernermo** [comment]
> Uberspace did a rollback the last time it occured.

Yeah... Well... Like I said, I work for Uberspace, it was me who did the rollback the last time ☺️ 

This is really just isso, everything else seems to work fine via pip in our setup. Since the old Python Version was 2.7.3, which is really dated, we can't just rollback all the time...

So where do you think the error is? Python 2.7.10 is pretty much vanilla, the only changes we made were the `distutils.cfg` and the `altinstall.pth`

**Comment by posativ** [comment]
Sorry, I just glanced over the issue. It is not related to Isso, I just verified that certain packages install into the wrong folder, e.g `flup`, `ipaddr` or `misaka`. The only thing they have in common: they are not distributed as wheel. Several other packages, e.g. `django` or `werkzeug` will install correctly.

I can release a wheel distribution, but certain dependencies will still fail.

**Comment by posativ** [comment]
@wernermo did you check out the mentioned packages?

**Comment by posativ** [comment]
@wernermo closing this. The solution is using `pip-2.7 install --user`. The installation of packages without `--user` is no longer working at all (that's good).

**Comment by jacmoe** [comment]
You wrote an article about installing isso on Uberspace - and that is what got me into trouble :)
Pip3 did mess things up - pip-2.7 works.
