### ISSUE TITLE
Make comment nesting level configurable

### ISSUE THREAD

**Issue by sprin** [posativ/isso#210]
The current Isso JavaScript client allows for only one level of comment nesting. While this may be a good UX choice for most, there are many situations where arbitrary levels of comment nesting are desired.

The Isso client should support a user-configurable nesting level limit. The default should be "1", or the same limit as currently imposed, for backwards compatibility.

**Comment by ix5** [comment]
See https://github.com/posativ/isso/issues/79 and http://blog.codinghorror.com/web-discussions-flat-by-design/
