### ISSUE TITLE
How to tweak css

### ISSUE THREAD

**Issue by pozitron57** [posativ/isso#213]
Hi,

I installed Isso using `pip install isso`. It has been installed into `/usr/local/lib/python2.7/dist-packages/isso`. There is a `css/isso.css` style file, but it doesn't control anything, because in `js/embed.dev.js` (and `js/embed.min.js`) there is a line defining styles: 

    define("text!app/../../css/isso.css",[],function(){return"#isso-thread * {\n ...

So, I can change styles there and it works, but it is very awkward. How can I use isso.css instead? And why do I have files which are very different from files in master branch? Maybe It will be easier just to reinstall isso from source?

**Comment by posativ** [comment]
You can disable Isso's CSS using `<script src="..." data-isso-css="false"></script>` and use your own CSS rules, if that helps.

**Comment by pozitron57** [comment]
Arrgh, it's worth reading the documentation! Thanks and sorry for the stupid question.
