### ISSUE TITLE
Error installing misaka==2.0.0 and misaka==1.0.2

### ISSUE THREAD

**Issue by harish211** [posativ/isso#215]
Windows device- Cannot install isso when misaka==2.0.0 or 1.0.2

(c) C:\Users\Home\lib\c\tutorial>pip install .
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Processing c:\users\home\lib\c\tutorial
Collecting itsdangerous (from isso==0.10.dev0)
Collecting misaka==1.0.2 (from isso==0.10.dev0)
  Using cached misaka-1.0.2.tar.gz
Collecting html5lib<0.9999 (from isso==0.10.dev0)
  Downloading html5lib-0.999.tar.gz (885kB)
    100% |################################| 888kB 30kB/s
Collecting ipaddr>=2.1 (from isso==0.10.dev0)
Collecting configparser (from isso==0.10.dev0)
Collecting werkzeug>=0.8 (from isso==0.10.dev0)
  Using cached Werkzeug-0.10.4-py2.py3-none-any.whl
Collecting six (from html5lib<0.9999->isso==0.10.dev0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: misaka, html5lib
  Running setup.py bdist_wheel for misaka
  Complete output from command C:\Users\Home\lib\c\Scripts\python.exe -c "import setuptools;__file__='c:\\users\\home\\appdata\\local\\temp\\pip-build-myyctk\\misaka\\setup.py';exec
(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\home\appdata\local\temp\tmpcztddgpip-wheel-:
  running bdist_wheel
  running build
  running build_ext
  building 'misaka' extension
  creating build
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\src
  creating build\temp.win32-2.7\Release\src\sundown
  C:\Users\Home\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\Home\lib\c\PC /
Tcsrc/misaka.c /Fobuild\temp.win32-2.7\Release\src/misaka.obj
  misaka.c
  src/misaka.c(235) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
  error: command 'C:\\Users\\Home\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for misaka
  Running setup.py bdist_wheel for html5lib
  Stored in directory: C:\Users\Home\AppData\Local\pip\Cache\wheels\6b\55\00\8a4b5e3e0a63e3dd40553698199d2b57223495eab6c55310e3
Successfully built html5lib
Failed to build misaka
Installing collected packages: itsdangerous, misaka, six, html5lib, ipaddr, configparser, werkzeug, isso
  Running setup.py install for misaka
    Complete output from command C:\Users\Home\lib\c\Scripts\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\home\\appdata\\local\\temp\\pip-build-myyctk\\misaka\\se
tup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\home\appdata\local\temp\pip-ebaif8-record\
install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Home\lib\c\include\site\python2.7\misaka:
    running install
    running build
    running build_ext
    building 'misaka' extension
    C:\Users\Home\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\Home\lib\c\PC
 /Tcsrc/misaka.c /Fobuild\temp.win32-2.7\Release\src/misaka.obj
    misaka.c
    src/misaka.c(235) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\Home\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\Home\lib\c\Scripts\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\home\\appdata\\local\\temp\\pip-build-myyctk\\misaka\\setup.py';exec(compile(get
attr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\home\appdata\local\temp\pip-ebaif8-record\install-record.txt --sin
gle-version-externally-managed --compile --install-headers C:\Users\Home\lib\c\include\site\python2.7\misaka" failed with error code 1 in c:\users\home\appdata\local\temp\pip-build-
myyctk\misaka

(c) C:\Users\Home\lib\c\tutorial>pip install .
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Processing c:\users\home\lib\c\tutorial
Requirement already satisfied (use --upgrade to upgrade): itsdangerous in c:\users\home\lib\c\lib\site-packages (from isso==0.10.dev0)
Collecting misaka (from isso==0.10.dev0)
  Using cached misaka-2.0.0.tar.gz
Collecting html5lib<0.9999 (from isso==0.10.dev0)
Collecting ipaddr>=2.1 (from isso==0.10.dev0)
Collecting configparser (from isso==0.10.dev0)
Collecting werkzeug>=0.8 (from isso==0.10.dev0)
  Using cached Werkzeug-0.10.4-py2.py3-none-any.whl
Collecting cffi>=1.0.0 (from misaka->isso==0.10.dev0)
  Using cached cffi-1.3.0-cp27-none-win32.whl
Collecting six (from html5lib<0.9999->isso==0.10.dev0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.0.0->misaka->isso==0.10.dev0)
Building wheels for collected packages: misaka
  Running setup.py bdist_wheel for misaka
  Complete output from command C:\Users\Home\lib\c\Scripts\python.exe -c "import setuptools;__file__='c:\\users\\home\\appdata\\local\\temp\\pip-build-t6ssge\\misaka\\setup.py';exec
(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\home\appdata\local\temp\tmplotbpxpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\misaka
  copying misaka\api.py -> build\lib.win32-2.7\misaka
  copying misaka\callbacks.py -> build\lib.win32-2.7\misaka
  copying misaka\constants.py -> build\lib.win32-2.7\misaka
  copying misaka\utils.py -> build\lib.win32-2.7\misaka
  copying misaka\__init__.py -> build\lib.win32-2.7\misaka
  running build_ext
  generating cffi module 'build\\temp.win32-2.7\\Release\\misaka._hoedown.c'
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  building 'misaka._hoedown' extension
  creating build\temp.win32-2.7\Release\build
  creating build\temp.win32-2.7\Release\build\temp.win32-2.7
  creating build\temp.win32-2.7\Release\build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\misaka
  creating build\temp.win32-2.7\Release\misaka\hoedown
  C:\Users\Home\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Imisaka -IC:\Python27\include -IC:\Users\Home\l
ib\c\PC /Tcbuild\temp.win32-2.7\Release\misaka._hoedown.c /Fobuild\temp.win32-2.7\Release\build\temp.win32-2.7\Release\misaka._hoedown.obj
  misaka._hoedown.c
  misaka\hoedown/buffer.h(9) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
  error: command 'C:\\Users\\Home\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for misaka
Failed to build misaka
Installing collected packages: pycparser, cffi, misaka, six, html5lib, ipaddr, configparser, werkzeug, isso
  Running setup.py install for misaka
    Complete output from command C:\Users\Home\lib\c\Scripts\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\home\\appdata\\local\\temp\\pip-build-t6ssge\\misaka\\se
tup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\home\appdata\local\temp\pip-29dibs-record\
install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Home\lib\c\include\site\python2.7\misaka:
    running install
    running build
    running build_py
    running build_ext
    generating cffi module 'build\\temp.win32-2.7\\Release\\misaka._hoedown.c'
    already up-to-date
    building 'misaka._hoedown' extension
    C:\Users\Home\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Imisaka -IC:\Python27\include -IC:\Users\Home
\lib\c\PC /Tcbuild\temp.win32-2.7\Release\misaka._hoedown.c /Fobuild\temp.win32-2.7\Release\build\temp.win32-2.7\Release\misaka._hoedown.obj
    misaka._hoedown.c
    misaka\hoedown/buffer.h(9) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\Home\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\Home\lib\c\Scripts\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\home\\appdata\\local\\temp\\pip-build-t6ssge\\misaka\\setup.py';exec(compile(get
attr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\home\appdata\local\temp\pip-29dibs-record\install-record.txt --sin
gle-version-externally-managed --compile --install-headers C:\Users\Home\lib\c\include\site\python2.7\misaka" failed with error code 1 in c:\users\home\appdata\local\temp\pip-build-
t6ssge\misaka

**Comment by posativ** [comment]
Going to close this (similar reason here #216).

There are different markdown implementations (e.g. Hoedown) but it currently works on OpenBSD and Linux and I see no reason to use a different implementation. A configurable markup backend is on my wishlist though.

**Comment by harish211** [comment]
Please close this. I'm using mistune(https://github.com/lepture/mistune) for markdown, figured out lately.
Thank you though
