### ISSUE TITLE
curl is defined with 5 arguments, but always called with 4

### ISSUE THREAD

**Issue by Anaphory** [posativ/isso#217]
I get the following error on the firefox javascript console:

```
Timestamp: 11/11/15 14:34:56
Error: TypeError: reject is not a function
Source File: http://gereon.eltanin.uberspace.de/fcgi-bin/isso/js/embed.dev.js
Line: 867
```

The function definition, where this appears, is (Line 850)

```
var curl = function(method, url, data, resolve, reject) {
```

However, all calls of `curl` are passed only 4 arguments, so `reject === undefined`, which is not a function.
(_Why_ I get a server error is a different matter and may mean that my configuration is bad.)

**Comment by ix5** [comment]
Is this still current? Otherwise I'll close this.

**Comment by Anaphory** [comment]
Oof, I have no idea.
