### ISSUE TITLE
Generate hash value from email

### ISSUE THREAD

**Issue by georg90** [posativ/isso#219]
Hi,
I'd like to customize isso a little bit - so I'd need to know how the hash key is generated?

It's not just pbkdf2 isn't it?

I used: http://anandam.name/pbkdf2/ to generate the same key I found in the `data-hash` attribute.

Also I get this error when entering a custom salt/algorithm:

```
015-12-01 00:59:20,623 WARNING: no such option: [hash] salt
2015-12-01 00:59:20,623 WARNING: no such option: [hash] algorithm
```

Can somebody point me into the right direction?

**Comment by ix5** [comment]
You were probably using a version of isso (probably packaged from some repository) that did not know about the `[hash]` section yet.

Isso's current hashing behvaiour can be foudn at `isso/utils/hash.py`:
https://github.com/posativ/isso/blob/e6dbd21819f8fdca9fdace447e9ba01276e8d6a9/isso/utils/hash.py#L77-L98
