### ISSUE TITLE
403 forbidden for replies

### ISSUE THREAD

**Issue by apheleia** [posativ/isso#224]
I can write comments, but I cannot leave a reply. The response is always:

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>edit time frame is still open</p>
```

Even on different pages. Is that due to me using the same IP in two browsers? If so: what about networks with a lot of users, like universities. Can one user not reply to a comment of another user?

**Comment by posativ** [comment]
You can disable this feature by setting `reply-to-self` to `True` (https://posativ.org/isso/docs/configuration/server/#guard). If you are using two different browsers, the second browser doesn't have the cookie to know whether the IP address has an editable comment.

**Comment by apheleia** [comment]
In my particular case this won't be a problem, I was just curious as to how it detects "the same user". Thanks a lot!

**Comment by smileboywtu** [comment]
you can see the database to see more detail, here every comments with a ip address.

**Comment by smileboywtu** [comment]
0|tid||0||0
1|id|INTEGER|0||1
2|parent|INTEGER|0||0
3|created|FLOAT|1||0
4|modified|FLOAT|0||0
5|mode|INTEGER|0||0
6|remote_addr|VARCHAR|0||0
7|text|VARCHAR|0||0
8|author|VARCHAR|0||0
9|email|VARCHAR|0||0
10|website|VARCHAR|0||0
11|likes|INTEGER|0|0|0
12|dislikes|INTEGER|0|0|0
13|voters|BLOB|1||0


this is the scheme of the comments table information. find more detail you can get it out.

**Comment by blatinier** [comment]
Seems like not a problem anymore.
