### ISSUE TITLE
make js fails

### ISSUE THREAD

**Issue by floreal** [posativ/isso#226]
Trying to install from source according to https://posativ.org/isso/docs/install/
I got this error when i `make js`:
> r.js -o isso/js/build.embed.js out=isso/js/embed.min.js
> Error: Error: ERROR: module path does not exist: /home/floreal/work/isso/isso/js/components/almond/almond.js for module named: components/almond/almond. Path is relative to: /home/floreal/work/isso
>    at /usr/lib/node_modules/requirejs/bin/r.js:30214:35
>
> Makefile:40: recipe for target 'isso/js/embed.min.js' failed
> make: *** [isso/js/embed.min.js] Error 1

What information do you need to help me ?
What am I supposed to do ?

**Comment by posativ** [comment]
Have you run

    cd isso/js; bower --allow-root install almond requirejs requirejs-text jade

?

Also the installation from source is currently slighty broken (that's what you get when using hipster technology). Anyways, currently you need `r.js` and `bower` in your PATH

    npm install requirejs bower

Then you run the `bower` command I first wrote. Currently it looks like you also need to install `jade` via NPM.

Then you might get an error in require-js/text, you can fix that by moving `isso/js/components/text` to `isso/js/components/requirejs-text`.

**Comment by floreal** [comment]
Hi agaim, 
thanks a lot. It did work fine

Cheers
