### ISSUE TITLE
[help] i can comment, and i can see it in my db and web page, but when i refresh it, the comment not appear.

### ISSUE THREAD

**Issue by smileboywtu** [posativ/isso#229]
[help] i can comment, and i can see it in my db and web page, but when i refresh it, the comment not appear.

**Comment by ticoombs** [comment]
Do you have moderation turned on? If so you need to have SMTP setup to get a notification of new comments. 

`
[moderation]
enabled = true
`

**Comment by smileboywtu** [comment]
yes, i turn off this and the website work good. thank you.
