### ISSUE TITLE
[idea] I suggest use the bootstrap 3 css style for isso.

### ISSUE THREAD

**Issue by smileboywtu** [posativ/isso#231]
now bootstrap3 is a very popular front end style lib, many people use this as the library of their web style.
so why we do not use bootstrap3  decorate the isso ?

**Comment by smileboywtu** [comment]
anyone get any idea? I just start to learn about bootstrap and find it really good and easy.

**Comment by pozitron57** [comment]
On my website I use bootstrap for Isso and also I made it look like comments on github (I hope it is not the worst act of plagiarism). You can check it out [here](https://lisakov.com/en/blog/astrophoto-iris/#isso-thread) (English). Hitting the light-blue button "Comment with Markdown" in top right corner of the text-area will call a bootstrap modal with some tips about Markdown.

If you want to see more comments, check out [this page](https://lisakov.com/blog/astrophoto-iris/#isso-thread) (Russian). Note that I turned off nesting. The way I style comments now is not suitable for nested comments — it looks screwy.

**Comment by smileboywtu** [comment]
@pozitron57  your whole website just use the bootstrap3, is it? but the submit button of comments not use the b3 library. can you tell how you just use b3, have you use the jekyll or hexo?

**Comment by pozitron57** [comment]
@smileboywtu website uses bootstrap3 and is generated with hexo. Submit button, indeed, is not styled with bootstrap. Basically the only bootstrap thing is the modal with tips.

**Comment by posativ** [comment]
Bootstrap is a quite large dependency, I'd rather use the default css. You can still use a custom css by using `data-isso-css`:

```html
<script src="..." data-isso-css="false"></script>
```

**Comment by smileboywtu** [comment]
@posativ I just try with jekyll and b3, but now it seems need some time to get it work.

**Comment by smileboywtu** [comment]
@posativ have you check the error of the manual compile the js file from source when install isso from source, there seem be some errors in config.js due to the file directory changes.

**Comment by smileboywtu** [comment]
anyone can give me a sample code? how to decorate with my own style after make data-isso-css="false"

**Comment by smileboywtu** [comment]
should I use jquery to add class?

**Comment by pozitron57** [comment]
Just modify your `css/isso.css` in the root directory of isso.

**Comment by smileboywtu** [comment]
I'll try it.

**Comment by posativ** [comment]
After you disabled the default CSS, you can bring your own styles. E.g. copy isso.css to your project and modify it.

**Comment by smileboywtu** [comment]
I'll try to do it, but now I'm not familiar with the isso css class file, I don't know which use there class, I now can just use html with css.

**Comment by posativ** [comment]
You can find the markup used to render the comment form etc here: https://github.com/posativ/isso/tree/0466977/isso/js/app/text (using [Jade](http://jade-lang.com/)).

Bootstrap (or any other framework) can be used to style Isso, but should not be included.
