### ISSUE TITLE
data-isso-require-email leads to JS error

### ISSUE THREAD

**Issue by tohn** [posativ/isso#238]
I copied every custom data attributes [from the docs](https://posativ.org/isso/docs/configuration/client/), but got the following error (in the console of chromium):
`Uncaught TypeError: Cannot read property 'replace' of undefined` (embed.min.js:19)
After removing each line and testing, I found out that `data-isso-require-email` is responsible for this error, and it doesn't matter whether `require-email` is set to true in the guard section of the config file or not.

**Comment by posativ** [comment]
Hi! Can you replace `embed.min.js` with the [linked version](https://posativ.org/wtf/de8cc8012565865f/embed.min.js) and try again? Thanks.

**Comment by tohn** [comment]
Thanks a lot, the linked version works! :)
