### ISSUE TITLE
Apache reverse proxy not working

### ISSUE THREAD

**Issue by h4ck3rm1k3** [posativ/isso#245]
Code is crashing when using apache reverse proxy like this

```
Listen 8082
<VirtualHost *:8082>
  ServerName comments.pirateparty.electionr.us
  ProxyPreserveHost Off
  ProxyRequests off
  ProxyPass / http://localhost:8081/
  ProxyPassReverse / http://localhost:8081/
</VirtualHost>

```

**Comment by posativ** [comment]
Is your PR looking for an issue or resolving this?

**Comment by h4ck3rm1k3** [comment]
Yes, I have an issue. Look up 3 lines Problem with apache server #244 

The problems were that the origin was messed up. I have moved on for now. Will come back to this in a while.

**Comment by h4ck3rm1k3** [comment]
Retesting the problem went away.
