### ISSUE TITLE
Certificate chain incomplete (posativ.org)

### ISSUE THREAD

**Issue by JohnMaguire** [posativ/isso#247]
Hi @posativ,

First of all, thank you for isso. It's excellent, and I'm glad I can use something open source and self-hosted rather than Disqus.

I wanted to let you know that posativ.org seems to be having [some SSL issues](https://www.ssllabs.com/ssltest/analyze.html?d=posativ.org). I believe this is due to your certificate that was renewed today now being issued by the new "Let's Encrypt Authority X3", whereas it was previously "Let's Encrypt Authority X1". It looks like the certificate chain didn't get updated on the server.

You can read more about the new authority here: https://community.letsencrypt.org/t/upcoming-intermediate-changes/13106

And here is a thread where others are facing the same issue: https://community.letsencrypt.org/t/certificates-issued-by-lets-encrypt-authority-x3-not-valid-in-mozilla/13320

Thank you again for isso! :+1:

**Comment by posativ** [comment]
That was quick, thank you for the infortmation. Fixed!
