### ISSUE TITLE
JS client: data-isso-require-email="true" gives error

### ISSUE THREAD

**Issue by akanter** [posativ/isso#249]
`embed.dev.js:2157 Uncaught TypeError: Cannot read property 'replace' of undefined`

The line in question being
`$("[name='email']", el).placeholder.replace(/ \(.*\)/, "");`

It seems as though this code is trying to replace the "(Optional)" part of the placeholder text before the placeholder value is actually set.

**Comment by posativ** [comment]
Not quite, this is the actual fix https://github.com/posativ/isso/commit/2612fbc0f563c5a65b8dd004689ced04d190c20a. I've released a new version that includes this fix.
