### ISSUE TITLE
[documentation] make clear whether or not Isso supports notifications to commenters

### ISSUE THREAD

**Issue by taoeffect** [posativ/isso#255]
The [current documentation](https://posativ.org/isso/docs/configuration/server/) does not make it super clear whether the email notifications are sent to just the sysadmin or whether commenters receive them as well (i.e. whether they can "(un)subscribe" to a thread).

Also, curious what the answer to this actually is.

**Comment by pozitron57** [comment]
I agree with you, the answer isn't clear from the documentation. Unfortunately, Isso can send mails only to admin, not to commenters. See pull request #50.

**Comment by posativ** [comment]
Submit a PR to improve the documentation.
