### ISSUE TITLE
Any way to run Isso on separated server, without 404 Not Found error when checking page existing

### ISSUE THREAD

**Issue by cryptofuture** [posativ/isso#266]
Btw, I already backported pull #254, so there should be no issue here.  
My setup is a bit complicated:
Server 1 (backend): isso (gunicorn) to nginx proxy-pass.  Only access from frontend available. (ip and certificate checking).
Server 2 api.domain.tld (frontend). Only access from cloudflare available (ip and certificate checking).
End user connects to cloudflare CDN. Website itself I need to use with isso proxified from github pages to cloudflare. I first tried proxy isso to /comments/ folder, to frontend, and I see right requests to / on backend just as with current setup, but with same `404 Not Found error`

**Comment by posativ** [comment]
Where is the exact issue with Isso here? If you follow the WSGI spec, you can proxy on any host with any script prefix.

**Comment by cryptofuture** [comment]
Its like it always can't find url, that I can open in my browser. 
> - - [17/Aug/2016:11:46:34 +0000] "OPTIONS /?uri=%2F2016%2F06%2F08%2F09-test.html&nested_limit=5 HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
>  - - [17/Aug/2016:11:46:36 +0000] "GET /?uri=%2F2016%2F06%2F08%2F09-test.html&nested_limit=5 HTTP/1.0" 404 233 "https://app.doman.tld/2016/07/08/09-test.html" 
https://app.doman.tld - in isso.conf host section.

**Comment by posativ** [comment]
Did you try posting a comment? Also the OPTIONS request should return the right host.

**Comment by cryptofuture** [comment]
>Did you try posting a comment?
Yes.
Exactly how OPTIONS request should look like? Like `OPTIONS /?uri=app.doman.tld%2F2016%2F06%2F08%2F09-test.html&nested_limit=5`?
I see right host in Origin header.

**Comment by posativ** [comment]
Please include the API exchange when you post a comment, the GET request might be normal behavior.

**Comment by cryptofuture** [comment]
I moved to isso to directory on frontend again, cloudflare cache messed cors headers time after time.
No OPTIONS requests with this setup.
```
Client:
Host=app.domain.tld
User-Agent=Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0
Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language=en-US,en;q=0.5
Accept-Encoding=gzip, deflate
DNT=1
Content-Type=application/json
Referer=https://app.domain.tld/2016/07/08/test.html
Content-Length=71
Cookie=__cfduid=uidhere; cf_clearance=uidhere
Connection=keep-alive
POSTDATA={"author":null,"email":null,"website":null,"text":"TEST","parent":null}

Server:
Status=NOT FOUND - 404
Date=Wed, 17 Aug 2016 15:51:38 GMT
Content-Type=text/html; charset=UTF-8
Transfer-Encoding=chunked
Connection=keep-alive
Access-Control-Allow-Origin=https://app.domain.tld
Access-Control-Allow-Credentials=true
Access-Control-Allow-Methods=HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers=Origin, Referer, Content-Type
Access-Control-Expose-Headers=X-Set-Cookie, Date
Cache-Control=max-age=0
Expires=Thu, 01 Jan 1970 00:00:00 GMT
X-Content-Type-Options=nosniff
Server=cloudflare-nginx
CF-RAY=2d3e49da6e1f0a54-ARN
Content-Encoding=gzip
```

```
# Frontend
- - [17/Aug/2016:15:38:26 +0000] "GET /api/?uri=%2F2016%2F07%2F08%2Ftest.html&nested_limit=5 HTTP/1.1" 404 233 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:46:03 +0000] "GET /2016/07/08/test.html HTTP/1.1" 200 3395 "-" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:46:05 +0000] "POST /api/count HTTP/1.1" 200 2 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:46:05 +0000] "GET /api/?uri=%2F2016%2F07%2F08%2Ftest.html&nested_limit=5 HTTP/1.1" 404 233 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:46:09 +0000] "POST /api/new?uri=%2F2016%2F07%2F08%2Ftest.html HTTP/1.1" 404 133 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"

# Backend 
- - [17/Aug/2016:15:36:02 +0000] "GET /?uri=%2F2016%2F07%2F08%2Ftest.html&nested_limit=5 HTTP/1.0" 404 233 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:36:34 +0000] "POST /new?uri=%2F2016%2F07%2F08%2Ftest.html HTTP/1.0" 404 133 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:38:25 +0000] "GET /?uri=%2F2016%2F07%2F08%2Ftest.html&nested_limit=5 HTTP/1.0" 404 233 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:46:05 +0000] "POST /count HTTP/1.0" 200 2 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:46:05 +0000] "GET /?uri=%2F2016%2F07%2F08%2Ftest.html&nested_limit=5 HTTP/1.0" 404 233 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
- - [17/Aug/2016:15:46:09 +0000] "POST /new?uri=%2F2016%2F07%2F08%2Ftest.html HTTP/1.0" 404 133 "https://app.domain.tld/2016/07/08/test.html" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"
```

**Comment by posativ** [comment]
It seems like Isso fails to check for the requested page. I don't use Cloudflare.

**Comment by cryptofuture** [comment]
>It seems like Isso fails to check for the requested page. 
That for sure. Any way to make it proxy check or override check? I have content copy on github.io (proxyfied from it) maybe it can be used for checking instead.

**Comment by posativ** [comment]
> Any way to make it proxy check or override check?

Not unless you edit the source code.

**Comment by remcoboerma** [comment]
I think i have something similar. So i tried to workaround the need for isso to fetch the page. Didn't have luck with that yet though. Am i on the right track ?

**Comment by ix5** [comment]
Isso has had changes to its proxy handling since 2016. Closing unless someone can confirm this is still an issue for them.
