### ISSUE TITLE
bypass double submit

### ISSUE THREAD

**Issue by kudataz** [posativ/isso#267]
![2016-08-20_113605](https://cloud.githubusercontent.com/assets/1845137/17829077/02ffffc4-66cc-11e6-8cfb-e5c40a9bfae1.png)

Hii..
when i click fast in double they submit for 2times, how about disable with loading image after one click? :smile:

**Comment by BabyBichu** [comment]
Try setting the `rate-limit` to 1 in ur server configuration.
https://posativ.org/isso/docs/configuration/server/
