### ISSUE TITLE
How to edit the old thread URL in terminal using "sqlite3"?

### ISSUE THREAD

**Issue by SnorlaxYum** [posativ/isso#270]
I wonder......

**Comment by pozitron57** [comment]
Copy database from `/var/lib/isso/comments.db` somwhere and do the following:

    sqlite3
    sqlite> ATTACH 'comments.db' AS isso;
    sqlite> SELECT id,uri FROM isso.threads;

This will give you a list with id and uri of all threads. Let us imagine that you want to set new uri for the thread with id=51:

    sqlite> UPDATE isso.threads SET uri='/new/uri/' WHERE id=51;

**Comment by SnorlaxYum** [comment]
Thanks! Works again!
