### ISSUE TITLE
isso tells email is optional but I have [guard] require-mail=true

### ISSUE THREAD

**Issue by ghost** [posativ/isso#273]
![captura_2016-09-13_19-07-25](https://cloud.githubusercontent.com/assets/89915/18483673/5acb3ecc-79e5-11e6-98bc-4fd8b62da7c3.png)

but I have

```
[guard]
  require-email = true
```

It should show "E-mail (mandatory)"

**Comment by SnorlaxYum** [comment]
That's the words configured in ur embed.min.js .
For example, u could see the Website input of my isso shows "URL (Optional) ": https://blog.snorl.ax/2016/09/08/edit-thread-url-isso/#isso-thread

It's cause I replaced "Website (Optional)" with "URL (Optional)" in the js.

So in your case just copy the js to ur site path and edit and use it.

For example I wanna edit mine then I should copy the js first:
cp /the path to isso/js/embed.min.js /the path to my site/js/

Then I edit the js in /the path of my site/js using my favorite editor and replace "E-mail (Optional)" with "E-mail (mandatory)" then save.

Normally our code is:
<script data-isso="//example.com/isso/" src="//example.com/isso/js/embed.min.js"></script>

<section id="isso-thread"></section>

Just replace the src "//example.com/isso/js/embed.min.js" with "//example.com/js/embed.min.js"

Done!

**Comment by somenxavier** [comment]
@SnorlaxYum Thanks but it has nonsense to me. So what configuration serves for? It's prefered by users that "displayed message" is *automatically* changed by isso itself.

**Comment by SnorlaxYum** [comment]
I guess that variable isn't taken into account 'cause only a minority need the function and that will add much to the file size of the js file.
Anyway telling @posativ the suggestion won't hurt

**Comment by posativ** [comment]
It needs to be translated in all supported languages, the initial PR didn't covered the languages.

**Comment by freeboson** [comment]
@somenxavier @posativ if I'm not mistaken, isn't the issue that you haven't set `data-isso-require-author="true"` etc.?

**Comment by somenxavier** [comment]
Now I can't do that because my isso server is not responding

2017-09-09 14:23 GMT+02:00 Sujeet Akula <notifications@github.com>:

**Comment by ix5** [comment]
Solved by setting `data-isso-require-email="true"` on client
