### ISSUE TITLE
reply thru IE  does not show up properly???

### ISSUE THREAD

**Issue by wjianwei126** [posativ/isso#276]
it does not show up often  but if you ctrl F5  it show up again ??? what is the problem?

**Comment by wjianwei126** [comment]
btw it works fine on other explorer

**Comment by posativ** [comment]
No idea, what IE do you run?

**Comment by wjianwei126** [comment]
ie 10 ,  sometimes show up sometime not ,  it work ok on other browsers except ie

**Comment by ix5** [comment]
Not enough info.
