### ISSUE TITLE
"Ich schrei sonst!" customization

### ISSUE THREAD

**Issue by somenxavier** [posativ/isso#279]
I received isso emails with "Ich schrei sonst! isso@somenxavier.xyz " as user.
How can I edit this? there is no documentation for such issue In [server](https://posativ.org/isso/docs/configuration/server/#smtp) configuration

I have this

```
# sender address, e.g. isso@example.tld
from = isso@somenxavier.xyz
```

in my config

**Comment by pozitron57** [comment]
Not sure whether I understood correctly, but if you want to edit the subject of the mails, you can edit `core.py`. In my case, needed lines are 154–155:

    if not parseaddr(rv.get("smtp", "from"))[0]:
        rv.set("smtp", "from", formataddr((u"Ich schrei sonst!", rv.get("smtp", "from"))))

**Comment by somenxavier** [comment]
@pozitron57 Yes, you understood correctly. Can @posativ mark as a bug (minor) for customize in the config file?

**Comment by posativ** [comment]
You can just use `Foo bar <bla@local>`, I think.

**Comment by somenxavier** [comment]
> You can just use Foo bar <bla@local>, I think.

How? If it's true, perhaps you could clarify the documentation

**Comment by posativ** [comment]
Instead of using `from = foo@bar`, you can do `from = "Title" <foo@bar>`. Not sure if you need quotes, but it is written this way in the docs.

**Comment by somenxavier** [comment]
> Instead of using from = foo@bar, you can do from = "Title" <foo@bar>. Not sure if you need quotes, but it is written this way in the docs.

So now it's doc bug. Perhaps someone could improve this

**Comment by blatinier** [comment]
It's clear in the doc:

    from
        sender address, e.g. “Foo Bar” <isso@example.tld>

Closing.
