### ISSUE TITLE
Instead of logging submission errors to the console, show them to the commenter.

### ISSUE THREAD

**Issue by kindfulkirby** [posativ/isso#280]
What the title says. Right now when my comment doesn't go through (say, because I comment too often, or I could still edit my earlier comment), the error is logged to the browser console but not shown on the site.
Normal users won't check their console (I assume), so to them it might appear their comment DID go through (even though it is not displayed) or they might wonder WHY it didn't. 

A visible error message would be great, I think!

**Comment by ix5** [comment]
Closing in favour of https://github.com/posativ/isso/issues/673
