### ISSUE TITLE
Irritating "time stamp"

### ISSUE THREAD

**Issue by mdosch** [posativ/isso#283]
It's not really a time stamp but I didn't know how to proper describe it.

What I experienced:
I had a look at an old blog post of mine which I did in 09/2014. I read a comment and I saw on top of it "3 years ago" and I felt irritated as it's 10/2016 so there could be no comment from three years ago as this would mean 10/2013 when this blog post didn't exist yet.

So it seems like a comment thats 2 years and 1 month old is interpreted as "three years ago" which is totally wrong. It should switch to three years ago after 3 years, 2 years and 1 month should remain "two years ago".

In case you need an example: https://blog.mdosch.de/2014/09/11/die-fish-shell/

**Comment by posativ** [comment]
True, I have same issue with some of my posts. I'll work out a fix.

**Comment by jelmer** [comment]
@philipcmonk that seems like it should do it. Care to send a PR?

**Comment by philipcmonk** [comment]
Sure:  #335
