### ISSUE TITLE
Improving isso: helping text

### ISSUE THREAD

**Issue by somenxavier** [posativ/isso#284]
It could be useful if we could add a helping text in the config file. Something like "Please be polite. All comments are under the same license of the page" between "Comments" and "No comments yet".

![captura_2016-10-23_12-29-11](https://cloud.githubusercontent.com/assets/89915/19625567/9c95d1a4-991c-11e6-9cbf-737e8a1b337f.png)

**Comment by posativ** [comment]
That's up to you. Why enforce a license?

**Comment by somenxavier** [comment]
No. You missunderstood. I just gave you an example. It could be something different offcourse.

**Comment by posativ** [comment]
The `Comments` header is not automatically inserted by Isso. You can write any HTML/CSS/JS you like to insert whatever you want.
