### ISSUE TITLE
Avoiding page retrieval fails: title isn't sent in create request

### ISSUE THREAD

**Issue by remcoboerma** [posativ/isso#285]
I try to prevent the isso backend from fetching the page to get the title. So, reading the docs i use the following: 

```html
<section id="isso-thread" data-isso-id="uniqueid" data-title="subject-title" ></section>
```
If i'm not mistaken it should be that when data-isso-id and data-title are provided it shouldn't try to read the page. Which in my case is blocked because of authentication. 

Here comes the problem: I don't understand why the title attribute doesn't show up in the data transferred for new comment creation. (first comment for the first thread on this domain) 

Here's the data posted to `https://server/some-app/new?uri=uniqueid` when creating the first comment for a new thread: 
```json
{"author":null,"email":null,"website":null,"text":"test","parent":null}
```

In isso.js i see the following which makes me expect a title in the data sent. 
```javascript
api.create($("#isso-thread").getAttribute("data-isso-id"), {
                author: author, email: email, website: website,
                text: utils.text($(".textarea", el).innerHTML),
                parent: parent || null,
                title: $("#isso-thread").getAttribute("data-title") || null
            }).then(...)...
```

I noticed the files being served by my gunicorn are the minified versions, can there be that those (albeit just installed through an upgrade through pip) aren't the latest as developed here at git? 

Is there anything else i can do to make it work?

**Comment by remcoboerma** [comment]
So. the minified version is not up to date, because using the dev version works like a charm.

**Comment by ix5** [comment]
@fluffy-critter @jelmer another candidate for closing.
