### ISSUE TITLE
Is there a way to hide Email and Website boxes?

### ISSUE THREAD

**Issue by taechemist** [posativ/isso#287]
My blog is locally used, I want to hide Email text box and website text box. any idea? Thank you.

**Comment by SnorlaxYum** [comment]
Make use of the style "display:none" to hide their elements or edit the file "embed.min.js" to hide them.

**Comment by taechemist** [comment]
@SnorlaxYum I install isso on CentOS. Where I can find "embed.min.js" file. Thank you.

**Comment by SnorlaxYum** [comment]
If u succeeded in launching it just download it and edit if u can.  
Then upload that to ur site and change the js path in the embedded code to the path u uploaded that to. Be sure to include data-isso

Just like this:

<script data-isso="//comments.example.tld/"
 src="//example.tld/js/embed.min.js"></script>

<section id="isso-thread"></section>

**Comment by taechemist** [comment]
@SnorlaxYum Right now, I'm using window.onload to add style to hide them. But, sometimes they show up. Thank you.

**Comment by SnorlaxYum** [comment]
U have to include the style u added in ur css file and purge the cache

**Comment by taechemist** [comment]
Can you explain a bit a about how to do so. Because, right now I can't locate any files where isso is installed on my server at all. Thank you so much.

**Comment by SnorlaxYum** [comment]
There r 2 ways......  
**Way 1 - Edit the js file**  
No need in finding where it is as the isso js file needn't be in the same path as the isso and the same for everyone who uses the default js. Download the official one if u need edit that: Click on [me](https://posativ.org/isso/api/js/embed.min.js)  
Take the HTML code u use to embed isso for example, this is the default setting using the js file from isso path:
```
<script data-isso="//your isso path/"
        src="//your isso path/js/embed.min.js"></script>

<section id="isso-thread"></section>
```
Alternatively, u could use something like this (the js is not from ur isso path, I love and recommend this one as it offers u the possibility to cache the js file, unlike the default setting):  
```
<script data-isso="//your isso path/"
        src="//the path where u placed the edited js/embed.min.js"></script>

<section id="isso-thread"></section>
```
I think I may get what u have to do if u wanna edit the js mauallly. Just edit the js file and upload that to the static path of ur site and edit the HTML code u use to embed isso.  
**Way 2 - CSS**  
It's much easier to do that. Just include the following code in one of the css files on ur pages using isso r using (Alternatively, u could include the code using the html tag `<style>` if u don't want to edit the css file):  
input[name="email"],input[name="website"]{display:none}

**Comment by taechemist** [comment]
@SnorlaxYum Thank you so much

**Comment by SnorlaxYum** [comment]
Solved? Then u could close it.

**Comment by kaushalmodi** [comment]
@SnorlaxYum Thanks! I use

```css
/* * Hide E-mail and Website boxes in Isso comments */
#isso-thread input[name="email"],
#isso-thread input[name="website"] {
    display:none
}
```
