### ISSUE TITLE
A problem with CDN

### ISSUE THREAD

**Issue by SnorlaxYum** [posativ/isso#290]
Just started using CloudFlare CDN on isso and found a problem that the IP of the user sent to my email is the one of CloudFlare's. @posativ

**Comment by posativ** [comment]
Working as intended?

**Comment by SnorlaxYum** [comment]
@posativ Yep still working it seems that the solution can vary depending on which CDN u r using, the solution of CloudFlare: https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx- 

Then to solve the problem the file about the mail should insert those codes and replace the original variable about IP with that variable. Will gonna try when I'm free. 
By The Way should I stop isso before editing? Last time after some edit to some files, isso ceased working.

**Comment by posativ** [comment]
> Last time after some edit to some files, isso ceased working.

Yeah, whatever.

**Comment by SnorlaxYum** [comment]
Seems those module should be in the configuration file of the isso domain and then the variable of the ip should be replaced with that. Is that correct? @posativ

**Comment by SnorlaxYum** [comment]
Done!
