### ISSUE TITLE
Does not work on Windows (wfastcgi+IIS)

### ISSUE THREAD

**Issue by jtanx** [posativ/isso#292]
I was trying running this on Azure, and I ran into an issue with the use of `AF_UNIX` in [wsgi.py](https://github.com/posativ/isso/blob/master/isso/wsgi.py#L198)

Replacing it with:

```python
address_family = socket.AF_INET
```

Seems to fix it, but then I'm not sure what that's used for (or if it's even used?)

**Comment by posativ** [comment]
What have you exactly tried to run Isso on Azure? I think the default web server doesn't use this wsgi class.

**Comment by jtanx** [comment]
I was running Isso as a Web App following [this](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-python-configure) guide. It uses wfastcgi and IIS, It works as long as I remove the reference to `AF_UNIX` sockets.

This is my wsgi entry point:

```python
#!/usr/bin/env python
import site, os

from isso import make_app
from isso import config as isso_config

ISSO_CONFIG=os.path.abspath("production.cfg")

application = make_app(isso_config.load(ISSO_CONFIG))
```

**Comment by jtanx** [comment]
Hmm, looks like there are a few other issues:

```python
Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "D:\home\Python27\wfastcgi.py", line 833, in main
    result.close()
  File "D:\home\Python27\wfastcgi.py", line 710, in __exit__
    self.send(FCGI_END_REQUEST, zero_bytes(8), streaming=False)
  File "D:\home\Python27\wfastcgi.py", line 755, in send
    send_response(self.stream, self.record.req_id, FCGI_STDOUT, self.header_bytes)
  File "D:\home\Python27\wfastcgi.py", line 372, in send_response
    raise TypeError("content must be encoded before sending: %r" % content)
TypeError: content must be encoded before sending: u'Status: 200 Ok\r\nContent-Type: text/plain\r\nAccess-Control-Allow-Origin: --\r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Allow-Methods: HEAD, GET, POST, PUT, DELETE\r\nAccess-Control-Allow-Headers: Origin, Referer, Content-Type\r\nAccess-Control-Expose-Headers: X-Set-Cookie, Date\r\n\r\n'
```

This is in response to an OPTIONS request. Using `Response` instead of returning an empty array seems to fix it: https://github.com/jtanx/isso/commit/4cf2f4fa92505cb396ce8944089306cb19c0714d

I also had to merge #212 because the only wheel offered by misaka is for version 2.0.0 (and I don't want to build the wheel myself)

**Comment by posativ** [comment]
While support for Windows might be possible in theory, I don't think it is a good idea to integrate them into the mainline. I don't use Windows and I do not like the additional burden to support something non-unix like.

If you have the resources for Windows, you can run several light-weight containers (e.g. Alpine Linux) with Isso.

Although I'll definitely consider to merge Misaka 2.0 support (wheels rock).

**Comment by jtanx** [comment]
That's reasonable enough, I guess. The only reason I'm using Azure is that it's free for me and that it has better response times (1/3rd that of) Openshift. 

And to be fair, the changes to get it working on Windows were fairly minimal - the removal of `AF_UNIX` and the use of `Response` for `OPTIONS` responses.

**Comment by SnorlaxYum** [comment]
I've used Azure. As far as I know, u could use Linux on the machine. Why not switch to Linux? Windows is too heavy and useless unless ur site is powered by some ASP engine.

**Comment by jtanx** [comment]
I only have free access to the free tier of Web Apps - I cannot use the VMs. They do have 'App Service on Linux', but it currently doesn't work on the free tier.

**Comment by blatinier** [comment]
I'm digging but since misaka update has been merged, could we have some update here?

**Comment by jtanx** [comment]
I've been running isso on azure (windows) for ages now, but that was with the modifications listed above. To be honest, I haven't updated it since I made this post, since it's been working fine, so I don't know if it works out of the box, or if anything else breaks on latest master. But considering I can still see [AF_UNIX](https://github.com/posativ/isso/blob/94d031444d5e38d3e76b7a95d1e9aaf4725b42ae/isso/wsgi.py#L203), I'd say probably not without changing that.

**Comment by ix5** [comment]
I see https://github.com/posativ/isso/commit/faaff1d4acaad42fc6485ce2090875ade265ea43 as part of https://github.com/posativ/isso/pull/473, so I assume you fixed your problem yourself.
Feel free to re-open in case I am wrong.
