### ISSUE TITLE
fyi/ftr: html5lib dependency

### ISSUE THREAD

**Issue by tohn** [posativ/isso#296]
Just for your information/for the record:

I upgraded on my server (Arch Linux) to python-html5lib version 0.999999999-1, and since the requirement was not met in `setup.py`, isso stopped working. I then tried to compile isso with the new version of html5lib, but this led to another error:

```
[..]
ImportError: No module named 'html5lib.sanitizer'
```

The solution was to downgrade to python-html5lib version 0.9999999-2 and ignore this package in `/etc/pacman.conf`.

**Comment by jelmer** [comment]
This is also a problem for the Debian packages now that a newer version of html5lib is in the Debian archive.

**Comment by tohn** [comment]
As mentioned in the comments of the [AUR page](https://aur.archlinux.org/packages/isso), I replaced `python-html5lib` with `python-html5lib-9x07`.

**Comment by somenxavier** [comment]
Same happens in debian

**Comment by vivlab** [comment]
Hello, will this bug be resolved ?
Is there a workaround which doesn't require python skills ?
Thanks for your help.
