### ISSUE TITLE
Unicode issue in add_cors_headers with uWSGI and Python 2

### ISSUE THREAD

**Issue by hiliev** [posativ/isso#297]
While debugging some CORS issues, I found out that the 502 status I was getting back from Nginx was due to a `TypeError` exception in uWSGI:

```
Traceback (most recent call last):
  File "/usr/local/www/isso/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/www/isso/lib/python2.7/site-packages/isso/wsgi.py", line 119, in __call__
    return self.app(environ, start_response)
  File "/usr/local/www/isso/lib/python2.7/site-packages/isso/wsgi.py", line 147, in __call__
    add_cors_headers("200 Ok", [("Content-Type", "text/plain")])
  File "/usr/local/www/isso/lib/python2.7/site-packages/isso/wsgi.py", line 144, in add_cors_headers
    return start_response(status, headers.to_list(), exc_info)
TypeError: http status must be a string
```

The `TypeError` gets thrown by uWSGI because the first argument to the `start_response` handler is not a string but a `unicode` object. Replacing `"200 Ok"` on line 147 with `b"200 Ok"` seems to fix the problem. I'm not a Python guru, but it looks like the problem is that all string literals are Unicode and a cursory read through the WSGI specification leads to the section [Unicode Issues](https://www.python.org/dev/peps/pep-0333/#id26), which says that all strings must be byte strings and not Unicode. uWSGI performs similar checks on the response headers, but that passes fine as Werkzeug converts the headers to latin1 byte strings in `Headers.to_list()`.

For the sake of completeness, my setup is as following:
* OS is FreeBSD 10.3-RELEASE
* Python version is 2.7.13
* `uwsgi` 2.0.14 installed from ports
* `isso` 0.10.6 from PyPI
* `Werkzeug` 0.11.15 from PyPI

Other Python WSGI apps (MoinMoin) run flawlessly.

**Comment by neocogent** [comment]
I'm getting this as well with native isso server with gevent installed. My error msg similar but not identical as I guess spit out by python for pywsgi in gevent.
```

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 909, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/isso/wsgi.py", line 119, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/isso/wsgi.py", line 147, in __call__
    add_cors_headers("200 Ok", [("Content-Type", "text/plain")])
  File "/usr/local/lib/python2.7/dist-packages/isso/wsgi.py", line 144, in add_cors_headers
    return start_response(status, headers.to_list(), exc_info)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 831, in start_response
    raise UnicodeError("The status string must be a native string")
UnicodeError: The status string must be a native string
Sat Jan 21 15:39:49 2017 {'REMOTE_PORT': '41624', 'HTTP_HOST': 'isso.neocogent.com:8228', 'REMOTE_ADDR': '101.51.40.122', (hidden keys: 27)} failed with UnicodeError

101.51.40.122 - - [2017-01-21 15:39:49] "OPTIONS /new?uri=%2Fblog%2F2017%2F01%2Fhow-i-do-deploy.html HTTP/1.1" 500 161 0.000464

```

I've spent friggin hours trying to get isso to work in various ways and it's not at all easy - even for me as a python dev. Many things are not clear at all like what should go in the data-isso field and what is the isso-thread value. I thought that had to be changed with something for each thread like with disqus. I am trying to get my pelican blog to use isso. And after many hours I am seriously wondering why I started down this road. I don't want to use disqus any more but isso is proving to be far too much work to configure. If I leave data-isso blank it gives errors about invalid objects in the browser console. If I put something in I get errors in the "upstart init log" but nothing in the isso "log-file" log. Why don't python errors go to the isso log? </frustration-rant over>

**Comment by hiliev** [comment]
I am using it on a Nikola-powered site and Nikola puts the URL of the isso server in the `data-isso` attribute. It seems to tell the JS what the base URL for the isso API is. If I understand it correctly, isso gets this base URL from the URL of the JS itself, therefore the `data-isso` should only be set if, e.g., you have multiple API endpoints (for different sites) with the JS being served from a single URL.

**Comment by neocogent** [comment]
That's what I figured out eventually. But I had to experiment to find out you have to put http:// there and from the docs it seemed to want slashes. Not sure why such a little thing took so long to get but probably compounded by painfully slow net today. It's all good now. Actually it's great! I have integrated it into Pelican instead of Disqus and it handles count (on index pages) and embed (on articles).

Also, I have my static site served on Amazon S3 but feed the isso comments to a vps I run. So the url for data-isso points to the vps but strangely the isso js code was trying to POST it to my S3 url. So for a while I was getting errors from S3 about not allowing POST. I started out earlier trying to get isso running on openshift (redhat cloud) but couldn't get it to run due to permissions issues with pip install during the "git push". 

Anyway. Thanks for everything. It's great.

**Comment by rolisz** [comment]
This is still broken. If I replace the "200 Ok" with b"200 Ok" it works.

**Comment by damnms** [comment]
same problem here... isso is not working (debian version) which runs with gunicorn
Access to XMLHttpRequest at 'https://isso.xxx.de/count' from origin 'https://xxx.de' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
embed.min.js:13 POST https://isso.xxx.de/count net::ERR_FAILED

**Comment by ix5** [comment]
Is this still current? Isso doesn't support py2 anymore.

**Comment by ix5** [comment]
@damnms can you confirm this is still an issue with gunicorn? Please post versions of all software used.

@hiliev can you confirm this is still an issue with uwsgi? Please post versions of all software used

**Comment by hiliev** [comment]
I don't know if this is still an issue with uwsgi since I'm no longer running isso. Sorry about that.

**Comment by ix5** [comment]
Looks like with current uwsgi version 2.0.20, the situation is actually reversed.

Assuming the setup from the [uwsgi Quickstart](https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html), with `foobar.py` as the `wsgi-file`.

This throws an error:
```python
def application(env, start_response):
    start_response(b'200 OK', [('Content-Type','text/html')])
    return []
```
`$ ./uwsgi --http :9090 --wsgi-file foobar.py`
```sh
Traceback (most recent call last):
  File "foobar.py", line 3, in application
    start_response(b'200 OK', [('Content-Type','text/html')])
TypeError: http status must be a string
```

This, however, works fine:
```python
def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    return []
```

It's about the return type, which must either be empty or a byte array, i.e. this works `return []`, and also `return [b"Hello World"]`, but not `return ["Hello World"]`.

So I'd consider this fixed with the current state in isso:
https://github.com/posativ/isso/blob/48a473606e20ec2afd139858164fc5550a0375dc/isso/wsgi.py#L141-L143

**Comment by ix5** [comment]
(So that I don't forget: https://github.com/ix5/isso/tree/utils-py2-bytes probably belongs in here with uwsgi oddities, too)
