### ISSUE TITLE
no mail sent in uwsgi mode

### ISSUE THREAD

**Issue by 22decembre** [posativ/isso#300]
Hello (happy new year)

I manage to start isso on OpenBSD using uwsgi. I actually need it to launch isso in fastcgi mode, which OpenBSD/Httpd can then use.

Result is great in the website itself : I can post comments. But they are not displayed after if moderation is false (I checked, it is not my intention to do that).

I actually want to moderate comments, with smtp. But I see no mail sent in logs or anything in the uwsgi spooler.

And uwsgi logs are quite... Weird :

`*** Starting uWSGI 2.0.14 (64bit) on [Sun Jan  8 10:54:21 2017] ***
compiled with version: 4.2.1 20070719  on 31 December 2016 15:52:55
os: OpenBSD-6.0 GENERIC.MP#86
nodename: blackblock.22decembre.eu
machine: amd64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /var/www/isso
detected binary path: /var/www/isso/bin/uwsgi
your processes number limit is 1310
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: ipcsem
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "hash" initialized: 2MB (key: 2136 bytes, keys: 2187264 bytes, data: 32768 bytes, bitmap: 0 bytes) preallocated ***
*** RRDtool library available at 0x49fc32c8000 ***
uwsgi socket 0 bound to UNIX address /var/www/tmp/isso.sock fd 4
Python version: 2.7.13 (default, Dec 28 2016, 14:01:50)  [GCC 4.2.1 20070719 ]
Set PythonHome to /var/www/isso
Python main interpreter initialized at 0x4a0205d2900
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 363800 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
2017-01-08 10:54:21,733 WARNING: unable to connect to your website, Isso will probably not work correctly. Please make sure, Isso can reach your website via HTTP(S).
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x4a0205d2900 pid: 18658 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18658)
spawned the uWSGI spooler on dir /var/www/isso/mail with pid 98487
spawned uWSGI worker 1 (pid: 8100, cores: 1)
spawned uWSGI worker 2 (pid: 47801, cores: 1)
spawned uWSGI worker 3 (pid: 6841, cores: 1)
spawned uWSGI worker 4 (pid: 79932, cores: 1)
cache sweeper thread enabled
`

So I don't know why it says it cannot connect to the website. I get the commenting window in the website.

Here is what happens when I comment :

`[pid: 35481|app: 0|req: 15/19] 2a06:4000:1576:0:226:b9ff:fef6:d709 () {50 vars in 982 bytes} [Sun Jan  8 11:04:08 2017] GET /isso/?uri=%2F2016%2F12%2F19%2FSilkeborg-juleskydning-fr%2F&nested_limit=5 => generated 413 bytes in 1 msecs (HTTP/1.1 301) 8 headers in 468 bytes (2 switches on core 0)
[pid: 35481|app: 0|req: 16/20] 2a06:4000:1576:0:226:b9ff:fef6:d709 () {50 vars in 982 bytes} [Sun Jan  8 11:04:08 2017] GET /isso/?uri=%2F2016%2F12%2F19%2FSilkeborg-juleskydning-fr%2F&nested_limit=5 => generated 413 bytes in 1 msecs (HTTP/1.1 301) 8 headers in 468 bytes (2 switches on core 0)
[pid: 35481|app: 0|req: 17/21] 2a06:4000:1576:0:226:b9ff:fef6:d709 () {50 vars in 982 bytes} [Sun Jan  8 11:04:08 2017] GET /isso/?uri=%2F2016%2F12%2F19%2FSilkeborg-juleskydning-fr%2F&nested_limit=5 => generated 413 bytes in 1 msecs (HTTP/1.1 301) 8 headers in 468 bytes (2 switches on core 0)
[pid: 35481|app: 0|req: 18/22] 2a06:4000:1576:0:226:b9ff:fef6:d709 () {50 vars in 982 bytes} [Sun Jan  8 11:04:08 2017] GET /isso/?uri=%2F2016%2F12%2F19%2FSilkeborg-juleskydning-fr%2F&nested_limit=5 => generated 413 bytes in 1 msecs (HTTP/1.1 301) 8 headers in 468 bytes (2 switches on core 0)
[pid: 35481|app: 0|req: 19/23] 2a06:4000:1576:0:226:b9ff:fef6:d709 () {50 vars in 982 bytes} [Sun Jan  8 11:04:08 2017] GET /isso/?uri=%2F2016%2F12%2F19%2FSilkeborg-juleskydning-fr%2F&nested_limit=5 => generated 413 bytes in 1 msecs (HTTP/1.1 301) 8 headers in 468 bytes (2 switches on core 0)
2017-01-08 11:04:16,410 INFO: comment created: {"website": "https://www.22decembre.eu", "author": "22decembre", "parent": null, "created": 1483869856.366205, "text": "<p>tyr</p>", "dislikes": 0, "modified": null, "mode": 1, "hash": "787679c7c7c5", "id": 7, "likes": 0}
[pid: 97154|app: 0|req: 2/24] 2a06:4000:1576:0:226:b9ff:fef6:d709 () {52 vars in 982 bytes} [Sun Jan  8 11:04:16 2017] POST /isso/new?uri=%2F2016%2F12%2F19%2FSilkeborg-juleskydning-fr%2F => generated 221 bytes in 54 msecs (HTTP/1.1 201) 9 headers in 692 bytes (2 switches on core 0)`

I get tons of loglines like that. (And we can see isso receives the comment !).

Interesting to say, when I launch isso just on the command line (as www user) like
`env LANG=C.UTF-8 bin/isso -c isso.cfg run`

I get the "connected to SMTP server, connected to https://www...". But then my server cannot communicate with isso (looks like they are not talking the same protocol).

**Comment by 22decembre** [comment]
Isso.cfg :

`[general]
dbpath = /var/www/isso/comments.db
host=
        https://www.22decembre.eu/
        https://www.22december.dk/

log-file = log.log
notify = smtp

[server]

listen = unix:///var/www/tmp/isso.sock

[moderation]
enabled = false
purge-after = 30d

[smtp]
to = donotreply
username = donotreply
password =
from = donetreply@22decembre.eu
host = localhost
port = 587
security = starttls
timeout = 10`

`[uwsgi]
fastcgi-socket = /var/www/tmp/isso.sock
master = true
logto = /var/www/logs/isso.log

; set to `nproc`
processes = 4
cache2 = name=hash,items=1024,blocksize=32
enable-threads

; you may change this
spooler = mail
module = isso.run

; uncomment if you use a virtual environment
virtualenv = /var/www/isso
env = ISSO_SETTINGS=isso.cfg LANG=C.UTF-8`

**Comment by SnorlaxYum** [comment]
The value of "to" should be a valid email address able to receive the mail.
For example, u want to receive the notification in `hello@gmail.com`, then the "to" and its value under `[smtp]` should look like this `to = hello@gmail.com`.
Also, u should be sure that the notification could be sent using the settings.

**Comment by posativ** [comment]
This is correct. You need to set both, the sender and the receiver.

**Comment by 22decembre** [comment]
So actually, it does not change anything.

I do not see any mail sent.

**Comment by posativ** [comment]
You should see some logs in your SMTP server.

**Comment by tgray** [comment]
I was never able to get Isso to send mail when running under uwsgi either.  It would create spool entries in my spool directory, but no mails were sent or entries in the log were made.  I switched to gunicorn and was able to get moderation email alerts sent with the same settings.
