### ISSUE TITLE
Remove 404 when no comments

### ISSUE THREAD

**Issue by claudio4** [posativ/isso#301]
When there are not comments the server response is a 404 error and this is bad beacause de browsers and the search engines detect it as a broken link, please replace the 404 error to something like *no comments*.

Tanks for your time and nice project

**Comment by Tetsumaki** [comment]
+1 for this issue please.

**Comment by zontarian** [comment]
Yes, an empty array would be preferable or something like that.

**Comment by jelmer** [comment]
How would isso know what valid pages are? The alternative is returning a 200, but also for pages that don't actually exist.

**Comment by claudio4** [comment]
A option could be return a 204 (No Content).

**Comment by jelmer** [comment]
Still, how would isso know which URLs are for valid pages and which ones aren't? Presumably you'd only want to return a 204 for comments on pages that exist, but a 404 for pages that don't exist.

**Comment by claudio4** [comment]
Which is the point of knwing if a page doesn't exists if you can send a comment anyway and create it?

**Comment by jelmer** [comment]
That's a fair point.

**Comment by ix5** [comment]
Fixed by https://github.com/posativ/isso/pull/565
