### ISSUE TITLE
Comment Submission Form Placement

### ISSUE THREAD

**Issue by madranet** [posativ/isso#304]
Is there a way to config Isso to place the comment entry form *after* any existing comments instead of before?  If not, could this be added as an option? 

It makes more sense to me for the page flow to be:

`Read content > Read others' comments > Add comment`

rather than 

`Read content > Add comment  > Read others' comments`

which makes it more likely that people will add a comment making a point that's already been made.

**Comment by zaygraveyard** [comment]
Possible duplicate of #294

**Comment by blatinier** [comment]
Yop closing.
