### ISSUE TITLE
http & https redirection issues

### ISSUE THREAD

**Issue by kaushalmodi** [posativ/isso#305]
Hello,

I was trying out isso instead of disqus. I have never hosted a comments server, so am trying it out on localhost.

This is my isso.conf file:

```
; -*- mode: conf-windows -*-
[general]
; database location, check permissions, automatically created if not exists
dbpath = /home/kmodi/usr_local/opt/isso/var/comments.db
; your website or blog (not the location of Isso!)
host =
     http://localhost:4444/~kmodi/beta/
[server]
listen = http://localhost:1234/
```

I use this in my static blog:

```html
<script data-isso="//localhost:1234//"
        src="//localhost:1234/js/embed.min.js">
</script>
<section id="isso-thread"></section>
<noscript>Please enable JavaScript to view the comments powered by Isso.</noscript>
comments powered by <a href="https://posativ.org/isso/">Isso</a>
```

And this is how I start the server:

```
> isso -c /home/kmodi/usr_local/opt/isso/etc/isso.conf run
2017-02-22 12:38:09,756 INFO: connected to http://localhost:4444/~kmodi/beta/
```

Above is all I get; I see not activity there as I click on Submit.

Here is what Firefox Inspector shows: I get 301 error on POST and 404 error on GET when I click on Submit.

![image](https://cloud.githubusercontent.com/assets/3578197/23224416/519b6f0c-f8fc-11e6-9b9a-24f95020c4c2.png)

**Comment by kaushalmodi** [comment]
Thanks for the reply.

I tried Chrome and I get this.. the same 301 error.

![image](https://cloud.githubusercontent.com/assets/3578197/23225570/4e5f0da4-f900-11e6-934d-6086e0b04aeb.png)

> Where does it redirect?

How can I know that? I am an absolute beginner in web development.

I read through the QuickStart. I have not idea what Nginx is or how to install it -- I am on my work machine. So I probably won't be able to install that.

(My plan is to host comments for my work blog generated using `hugo`. Right now I am testing it out on localhost, but my blog then gets available at `foo.bar.com/~$USER/`.)

**Comment by posativ** [comment]
Inspector → Network →select the redirect request.

![2017-02-22-191735_858x340_scrot](https://cloud.githubusercontent.com/assets/337602/23225867/c95a4310-f933-11e6-871f-4ccf92347c18.png)

I wonder why it even redirects. This seems to be automatic from the framework. Can you remove the trailing slash at the end of `data-isso="//localhost:1234//"`?

**Comment by kaushalmodi** [comment]
I see this.. does it help?

![image](https://cloud.githubusercontent.com/assets/3578197/23226607/24cc27de-f904-11e6-88aa-bd44a4d0b4e8.png)

**Comment by kaushalmodi** [comment]
> Can you remove the trailing slash at the end of data-isso="//localhost:1234//"?

Yay! That fixed it!

The reason I got those trailing double-slashes is because I was looking for examples and had found [this](https://github.com/JohnMaguire/johnmaguire.me/commit/f2985a610665eda1955f9b31a9d6d088b69d0fa1).

Can you explain what those `//` did? Would that have caused problem anyways? Or just because this was on localhost?

Thanks!

---

Proof :)
![image](https://cloud.githubusercontent.com/assets/3578197/23226707/8b8d4bd8-f904-11e6-8e63-cd7340e55f8b.png)

> 2017-02-22 13:39:57,477 INFO: comment created: {"website": null, "author": null, "parent": null, "created": 1487788797.436903, "text": "<p>test2</p>", "dislikes": 0, "modified": null, "mode": 1, "hash": "4505c1eeda98", "id": 2, "likes": 0}

**Comment by posativ** [comment]
The second slash forced triggered an automatic redirection from the web framework and the JavaScript didn't handle that well. Definitely a bug, but with an easy workaround.

**Comment by posativ** [comment]
> I read through the QuickStart. I have not idea what Nginx is or how to install it -- I am on my work machine. So I probably won't be able to install that.

You can use the built-in web server of Isso/Python, a frontend web server (e.g. nginx) is still useful for HTTPS handling etc.

**Comment by kaushalmodi** [comment]
Now it is working on Firefox too.

**Comment by kaushalmodi** [comment]
> Definitely a bug, but with an easy workaround.

Should I keep this issue open then?

By the way, it also works on my published static website :)

I have this as isso.conf:

```
; -*- mode: conf-windows -*-
[general]
; database location, check permissions, automatically created if not exists
dbpath = /home/kmodi/usr_local/opt/isso/var/comments.db
; your website or blog (not the location of Isso!)
host =
     http://localhost:4444/~kmodi/beta/
     http://www.foo.bar.com/~kmodi/beta/
; you can add multiple hosts for local development
; or SSL connections. There is no wildcard to allow
; any domain.
; host =
;     http://localhost:1234/
;     http://example.tld/
;     https://example.tld/
[server]
listen = http://baz.foo.bar.com:5555/
; baz.foo.bar.com is my $HOST
; listen = http://localhost:1234/
; Basic Spam protection - https://posativ.org/isso/docs/configuration/server/#id8
[guard]
enabled = true
ratelimit = 2
direct-reply = 3
reply-to-self = false
require-author = false
require-email = false
```

**Comment by posativ** [comment]
> Should I keep this issue open then?

Yes. I guess this also affects automatic redirection from HTTP to HTTPS in certain situations.

**Comment by ix5** [comment]
@kaushalmodi is this still a current issue?

**Comment by kaushalmodi** [comment]
@ix5 I'll close this issue as I am not using isso right now.
