### ISSUE TITLE
XMPP notifications

### ISSUE THREAD

**Issue by posativ** [posativ/isso#31]

**Comment by drym3r** [comment]
It would be cool to have it on the server. In the meanwhile, I made a ugly bash script that does the job. It uses sendxmpp. 
https://daemons.cf/cgit/isso-utils/tree/notificaciones-comentarios.sh

**Comment by ix5** [comment]
This might be implemented as part of the [syscall](https://github.com/posativ/isso/pull/457) or [Webhook](https://github.com/posativ/isso/pull/724) PRs.

Closing this one, anyone still interested can amend the linked PRs or comment there.
