### ISSUE TITLE
Code inside comments (asterisks become italics)

### ISSUE THREAD

**Issue by hamoid** [posativ/isso#310]
In my comments I answer people's questions about code, often with code. 

Currently asterisks in my code disappear and become *italics*.

What would be the right approach? Could I disable markdown entirely? Or just italics?

**Comment by hamoid** [comment]
I'm trying to debug this and I'm not sure what's going on. 

In the command line I use sqlite to explore the database I see two comments. 
Both have `*` characters, but only in one of them they become italics.
In that one, the `*` characters are inside `<pre><code>` tags. I don't know if it's related or not.

**Comment by posativ** [comment]
It is currently not possible to disable the markdown conversion. By default, you can – as you mentioned – prepend 4 spaces for code blocks. Alternatively, you can wrap the code with ` ``` ` (known as fenced code).

**Comment by hamoid** [comment]
Underscores were also a problem. It turns out there's a flag we can use to disable underscores in the middle_of_words.

    [markup]
    options = no_intra_emphasis

It has to be written with underscores, even if http://misaka.61924.nl/ lists this flag as no-intra-emphasis (with - characters). This flag gets rid of many unwanted italics in my comments.

**Comment by ix5** [comment]
Note for anyone coming across this: As of misaka 2.0 (which Isso 0.12.2+ uses), you have to use dashes instead of underscores.
https://github.com/FSX/misaka/blob/981fd9851bd38e9105d3d1bf8e931d0e0558343f/misaka/utils.py#L15-L30
