### ISSUE TITLE
Uncaught ReferenceError: exports is not defined in `embed.js`

### ISSUE THREAD

**Issue by jdormit** [posativ/isso#318]
Both `embed.dev.js` and `embed.min.js` attempt to bind code to the `exports` object, which does not exist in a browser context. Is there a compile step which I missed?

Here's the stack trace for `embed.min.js`:

```
Uncaught ReferenceError: exports is not defined
    at comments.jeremydormitzer.com/js/embed.min.js:19
    at comments.jeremydormitzer.com/js/embed.min.js:19
```

And the same for `embed.dev.js`:

```
Uncaught ReferenceError: exports is not defined
    at embed.dev.js:1306
    at embed.dev.js:2205
```

**Comment by posativ** [comment]
What version? From PyPi?

**Comment by jdormit** [comment]
This was using the Debian package.

I think I needed to use the `isso` server's hosted `requirejs` script. What I ended up doing was installing `isso` from source, and then using:

```html
<script src="//comments.jeremydormitzer.com/js/config.js"></script>
<script data-main="//comments.jeremydormitzer.com/js/embed" src="//comments.jeremydormitzer.com/js/components/requirejs/require.js"></script>
```
 
I have a feeling I could have done something similar to make it work with the Debian package?

Anyway, it seems to be working now. Thanks for the quick response!

**Comment by dan-boa** [comment]
@jdormit how were you able to solve this issue. I am currently also facing the same problem. I installed it using pip.

**Comment by imphil** [comment]
I had the same issue with the debian package on Ubuntu 16.04. Using the embed.min.js file from https://posativ.org/isso/api/js/embed.min.js and putting that into my web directory solved the issue for now.

**Comment by andrew-vant** [comment]
I have the same issue, also with the ubuntu 16.04 package. It looks like this is a known bug with the debian/ubuntu package version 0.9.9, see here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783490. Newer versions are supposedly "fixed", but the changelog just says "use upstream javascript for now", and the file is missing from newer package versions. Why they were rolling their own JS I don't know.

I don't have a better workaround than manually installing the embed.min.js from master as commenters have mentioned above; but this was the first hit when I was trying to fix the problem myself, so I figured I'd save others the trouble of digging for the cause.

**Comment by jelmer** [comment]
We intentionally rebuild everything that is not the preferred form of modification (e.g. minified files), so that we know it is possible to make modifications and built the resulting artefacts.

**Comment by ttbek** [comment]
Well... it ended up in Ubuntu 16.04... why was the newer version never pushed to Ubuntu 16.04?  Hence there is still a 'new' bug open https://bugs.launchpad.net/ubuntu/+source/isso/+bug/1707347 since 2017.

**Comment by jelmer** [comment]
There is no maintainer for isso in Ubuntu. Ubuntu automatically imports snapshots of packages (including isso) from Debian unstable.

**Comment by ttbek** [comment]
Ah, ok, thanks for replying.  Hmm, they should probably do that more often then to update.  Is it worth mentioning in the documentation more explicitly than the Debian bug reference?  Ubuntu 16.04 isn't end of life until April 2021.  I noticed the Debian bug mention, but assumed Ubuntu would have a newer packaged, wasn't until I fought with it a while that I thought to check that.

**Comment by jelmer** [comment]
Not necessarily opposed to adding a note about this in the docs if you wanted to send in a patch.

In general, I don't know that we want to track the state of isso as packaged in distributions. The main place where this should be tracked/fixed is in Ubuntu itself.
