### ISSUE TITLE
Feature request: Reverse-sort the comments on rendering (latest first)

### ISSUE THREAD

**Issue by PeterCxy** [posativ/isso#319]
It's not very important, but I do think that sorting comments in 'latest-first' order will be more natural for readers. Maybe an option 'data-isso-sorting' can be added to the JavaScript client.

**Comment by dbrgn** [comment]
I agree. Seems to be a duplicate of #4.

**Comment by blatinier** [comment]
Agree. Closing. @jelmer I add the label feature to #4
