### ISSUE TITLE
Cannot send comments

### ISSUE THREAD

**Issue by raspatan** [posativ/isso#320]
Hello there!

I have an issue. I have followed the Quickguide instructions, and added Isso to my website, but I cannot send comments. 

I am running isso in `/opt/isso`. The nginx is in `/etc/nginx`. These are my configuration files:

isso.cfg [here](https://paste.ubuntu.com/24389161/).
nginx.conf [here](https://paste.ubuntu.com/24389172/).
([here](https://paste.ubuntu.com/24389227/) is the javascript code, in case it might be of help. Nothing special there. Just copy pasted from another site))

My html code is:

```
<!-- comments enabled (isso) --> 
<div class="comments">
    <h2 class="isso-title">Comments</h2>   
    <script type="text/javascript" 
        data-title="Comments"
        data-isso="//comments.127.0.0.1:4000/"
        data-isso-css="true"
        data-isso-lang="en"
        data-isso-reply-to-self="false"
        data-isso-require-author="false"
        data-isso-require-email="false"
        data-isso-max-comments-top="10"
        data-isso-max-comments-nested="5"
        data-isso-reveal-on-click="5"
        data-isso-avatar="true"
        data-isso-avatar-bg="#f0f0f0"
        data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 #2069b6 #486910 #e4bf80 #0f0f0f"
        data-isso-vote="true"
        data-vote-levels="[-5,5,15]"        
        src="https://cdnjs.cloudflare.com/ajax/libs/embed-js/4.2.2/embed.min.js"></script>    
    <section id="isso-thread"></section>

</div> 
```
The comment's box does appear on my website, but when I click submit, nothing happens. 

This is what I do to run my site (locally):

- create my site locally: `bundle exec jekyll serve` (using jekyll). This gives me a server address at `http://127.0.0.1:4000/`
- enable virtual environment: `source /opt/isso/bin/activate`
- run isso: `isso -c /opt/isso/isso.cfg run`. This gives me the message: `connected to http://127.0.0.1:4000/`

Then, I go to a particular subdomain in my website (`http://127.0.0.1:4000/blog/2017/097/hello/`), and try to submit a comment, but nothing happens. 

What is the issue? Am I actually running the proxy with nginx? Notice that my site is a blog and the comment box appears on every page. Is that ok?

**Comment by Libbum** [comment]
`comments.127.0.0.1`

You can't use a subdomain and an ip address at the same time. Are you going to have this accesible through some domain? If so, set it up with that domain in your nginx config. If not, and you're only going to look at it locally, try using the [sub-uri](https://posativ.org/isso/docs/setup/sub-uri/) setup instead so you can just use your loopback ip address.

**Comment by raspatan** [comment]
Thanks @Libbum for the quick response. Before going live, I want to test my website locally. As such, I have tried your second advice. Changed the `nginx` config as suggested. Not sure what goes in root, but I added the local directory where the `index.html` page is (`/home/lucho/myblog/_site/`). 

Doing just that makes no difference. Comments still are not submitted. I also tried to start `nginx`, but diesn't work. I get:

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] still could not bind()
```

In fact, the ports seem to been used. This is the output of `sudo netstat -tulpn`:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      1395/smbd       
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      3817/python2    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3367/nginx: master 
tcp        0      0 127.0.0.1:40048         0.0.0.0:*               LISTEN      2052/Brackets-node
tcp        0      0 127.0.0.1:9234          0.0.0.0:*               LISTEN      2029/Brackets --lan
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1600/dnsmasq    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      3949/cupsd      
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      2052/Brackets-node
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      1395/smbd       
tcp        0      0 127.0.0.1:4000          0.0.0.0:*               LISTEN      3713/jekyll serve
tcp        0      0 127.0.0.1:6342          0.0.0.0:*               LISTEN      2024/megasync   
tcp6       0      0 :::139                  :::*                    LISTEN      1395/smbd       
tcp6       0      0 :::80                   :::*                    LISTEN      3367/nginx: master 
tcp6       0      0 ::1:631                 :::*                    LISTEN      3949/cupsd      
tcp6       0      0 :::443                  :::*                    LISTEN      3367/nginx: master 
tcp6       0      0 :::445                  :::*                    LISTEN      1395/smbd       
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           2219/chrome     
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           911/avahi-daemon: r
udp        0      0 0.0.0.0:51416           0.0.0.0:*                           1600/dnsmasq    
udp        0      0 0.0.0.0:43308           0.0.0.0:*                           911/avahi-daemon: r
udp        0      0 127.0.1.1:53            0.0.0.0:*                           1600/dnsmasq    
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1589/dhclient   
udp        0      0 192.168.2.255:137       0.0.0.0:*                           1375/nmbd       
udp        0      0 192.168.2.17:137        0.0.0.0:*                           1375/nmbd       
udp        0      0 0.0.0.0:137             0.0.0.0:*                           1375/nmbd       
udp        0      0 192.168.2.255:138       0.0.0.0:*                           1375/nmbd       
udp        0      0 192.168.2.17:138        0.0.0.0:*                           1375/nmbd       
udp        0      0 0.0.0.0:138             0.0.0.0:*                           1375/nmbd       
udp        0      0 0.0.0.0:631             0.0.0.0:*                           2798/cups-browsed
udp6       0      0 :::5353                 :::*                                2219/chrome     
udp6       0      0 :::5353                 :::*                                911/avahi-daemon: r
udp6       0      0 :::40419                :::*                                911/avahi-daemon: r
```
I can see `nginx: master there`. Is it on already? If I try to restart the service, with `sudo service nginx restart`, I get:

`Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.`

The output of `systemctl status nginx.service` is: 

```
nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: en
   Active: failed (Result: exit-code) since Sun 2017-04-16 19:36:35 BST; 7min ag
  Process: 3785 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code
  Process: 3781 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process 

Apr 16 19:36:34 lucho-HP nginx[3785]: nginx: [emerg] bind() to [::]:80 failed (9
Apr 16 19:36:34 lucho-HP nginx[3785]: nginx: [emerg] bind() to [::]:443 failed (
Apr 16 19:36:35 lucho-HP nginx[3785]: nginx: [emerg] bind() to 0.0.0.0:80 failed
Apr 16 19:36:35 lucho-HP nginx[3785]: nginx: [emerg] bind() to [::]:80 failed (9
Apr 16 19:36:35 lucho-HP nginx[3785]: nginx: [emerg] bind() to [::]:443 failed (
Apr 16 19:36:35 lucho-HP nginx[3785]: nginx: [emerg] still could not bind()
Apr 16 19:36:35 lucho-HP systemd[1]: nginx.service: Control process exited, code
Apr 16 19:36:35 lucho-HP systemd[1]: Failed to start A high performance web serv
Apr 16 19:36:35 lucho-HP systemd[1]: nginx.service: Unit entered failed state.
Apr 16 19:36:35 lucho-HP systemd[1]: nginx.service: Failed with result 'exit-cod
lines 1-16/16 (END)
```

No idea what else to do. I should have mentioned that I am a very noob in all this. 

If I cannot test Isso offline, I can also attempt to do it online, but would prefer to do so locally first. Any help is very welcomed.

**Comment by Libbum** [comment]
Your root should indeed be the site you're trying to set up. If you comment out the isso portion of your nginx config does your site run without issue? From the sound of it that isn't the case at the moment if nginx is failing to run. You can also run `nginx -t` to see what errors your configuration is giving, but right now it seems like you may even have a zombie process attached to your ports. Try a restart, comment out the isso portion and get your site up and running. Then we'll set up the rest. Can you link me to your current nginx config?

**Comment by raspatan** [comment]
Sounds logical. [Here](https://pastebin.ubuntu.com/24395978/) is the config file, hosted in `/etc/nginx`. There seems to be no errors. Output of suggested command:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

```

Will run from restart tomorrow first thing and come back to you. I will check if `nginx` is enabled from startup. Should I run the proxy **before** starting my localhost, via `bundle exec jekyll serve`?

**Comment by Libbum** [comment]
Sure thing.

* nginx config looks ok, provided there is nothing suspect when you include files in these directories: `include /etc/nginx/conf.d/*.conf; include /etc/nginx/sites-enabled/*;`
* Just to be clear: are you viewing your working webpage at localhost:4000? 
* *Should I run the proxy before starting my localhost?* That's a bit confusing. Do you mean start the proxy before starting nginx on the localhost? If so, then yes. If not: are you running the comment system on a different machine?

**Comment by raspatan** [comment]
@Libbum So, after a restart, I attempted to run nginx, getting error for the 80 only:

    nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)

Then, following [this answer](http://stackoverflow.com/a/15101745/3585386), I managed to start nginx. To confirm, this was the output of `sudo netstat -tulpn`:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      1391/smbd       
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2810/nginx: master 
tcp        0      0 127.0.0.1:9234          0.0.0.0:*               LISTEN      2818/Brackets --lan
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1595/dnsmasq    
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      2840/Brackets-node
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2810/nginx: master 
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      1391/smbd       
tcp        0      0 127.0.0.1:41221         0.0.0.0:*               LISTEN      2840/Brackets-node
tcp6       0      0 :::139                  :::*                    LISTEN      1391/smbd       
tcp6       0      0 :::80                   :::*                    LISTEN      2810/nginx: master 
tcp6       0      0 :::443                  :::*                    LISTEN      2810/nginx: master 
tcp6       0      0 :::445                  :::*                    LISTEN      1391/smbd       
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           2905/chrome     
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           903/avahi-daemon: r
udp        0      0 0.0.0.0:56012           0.0.0.0:*                           1595/dnsmasq    
udp        0      0 0.0.0.0:36267           0.0.0.0:*                           903/avahi-daemon: r
udp        0      0 127.0.1.1:53            0.0.0.0:*                           1595/dnsmasq    
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1585/dhclient   
udp        0      0 192.168.2.255:137       0.0.0.0:*                           1371/nmbd       
udp        0      0 192.168.2.17:137        0.0.0.0:*                           1371/nmbd       
udp        0      0 0.0.0.0:137             0.0.0.0:*                           1371/nmbd       
udp        0      0 192.168.2.255:138       0.0.0.0:*                           1371/nmbd       
udp        0      0 192.168.2.17:138        0.0.0.0:*                           1371/nmbd       
udp        0      0 0.0.0.0:138             0.0.0.0:*                           1371/nmbd       
udp        0      0 0.0.0.0:631             0.0.0.0:*                           2358/cups-browsed
udp6       0      0 :::37863                :::*                                903/avahi-daemon: r
udp6       0      0 :::5353                 :::*                                2905/chrome     
udp6       0      0 :::5353                 :::*                                903/avahi-daemon: r
```

So, all good. Then, I started my website server with `bundle exec jekyll serve`. Then, I started Isso, right after enabling the virtual environment:

```
source /opt/isso/bin/activate
isso -c /opt/isso/isso.cfg run
```

Then, I go to the browser (chrome, or firefox, no difference), and try to submit a comment. Nothing happens again. I access the wesbite either using `http://localhost:4000` or `http://127.0.0.1:4000/`. It makes no difference.

Then, I tried changing the order. First, started the server. Second, run nginx. Third, run isso. No improvement. In both cases there is no stdout feedback from isso.

The folder `/etc/nginx/conf.d/` is empty. The folder `/etc/nginx/sites-enabled/` links to `/etc/nginx/sites-available/` where the default file is as shown previously. 

No idea how to proceed. 

------------

In any case, I am now going to upload a sample page with isso to my github, to test this online. Let us see if I have better luck there. I will provide the link soon. In the meantime, aby other hint about what is wrong with my localhost would be very much welcome. Thanks!

**Comment by Libbum** [comment]
Huh. I can't see anything wrong there... If you netstat after you start the services you should also see jekyll on 4000 and isso on 8080 yes? Is there anything helpful in `/var/log/nginx/error.log`?

**Comment by posativ** [comment]
Your initial setup is wrong: `data-isso` should be the url to the Isso instance, not the Jekyll server. E.g. `http://127.0.0.1:8080/`.

**Comment by raspatan** [comment]
@Libbum I see jekyll in 4000 and python2 in 8080. I guess that is isso? Nothing interesting in the log.

@posativ does not seem to help. I tried all combinations could come up with. Btw, the nginx [configuration](https://posativ.org/isso/docs/quickstart/#running-isso) suggested in the website, with two set of `server {}` gives an error `nginx: [emerg] duplicate listen options for [::]:80 in /etc/nginx/nginx.conf:88`). One I eliminate the top one I can start nginx.

**Comment by posativ** [comment]
You don't need nginx to test this. If it doesn't work with Jekyll + Python, it still won't work with nginx doing basically the same thing. The nginx configurations are snippets, they do work if you know nginx works with different servers.

If you use Isso with `data-isso="http://127.0.0.1:8080/"` in your template and Isso is running on that port and uses `host = http://127.0.0.1:4000/` (via [Quickstart](https://posativ.org/isso/docs/quickstart/)), it will work. Don't forget to recompile your static site once you changed the integration bits.

**Comment by raspatan** [comment]
@Libbum Here is the online site: https://raspatan.github.io/test/blog/blog.html Now, not even the comment box appears.

@posativ I wrote to you on irc. If you prefer, I can write here too. Don't know how to proceed. Should have notice that I am very noob on all this.

**Comment by Libbum** [comment]
`https://raspatan.github.io/test/` is serving up your web page though, so the nginx config is not right here either. You see in the developer console you have 404 errors for a whole heap of stuff. So your root is either wrong or incomplete, but more importantly: you're trying to serve `/path/test/` as your main root, then attempting to hijack `/path/test/` with your proxy (`data-isso="//raspatan.github.io/test/"`). This is what posativ was saying above, you need to have you root set to your web page, and `data-isso` to some other point. Either make it a subdomain (which if you're using githubpages that doesn't make sense) or a directory *lower* in your hierarchy. So here, for example: Blog: `https://raspatan.github.io/test/blog/`, comments `https://raspatan.github.io/test/blog/isso/` <-- this is your `data-isso` and in nginx, if your root is `/path/test/` then the `location` for this is `/blog/isso`.
We'll need your new configs to see what you've done here.

**Comment by raspatan** [comment]
@Libbum Thanks. I am not using nginx anymore. One step at a time. The local server now works. Martin's comments helped me (after some interation on irc).

I made as you suggested. Created subfolder `https://github.com/raspatan/test/tree/master/blog/isso`. The config in the html page is:

```
<!-- comments enabled (isso) --> 
<div class="comments">
    <h2 class="isso-title">Comments</h2>   
    <script type="text/javascript" 
        data-title="Comments"
        data-isso="//raspatan.github.io/test/blog/isso/"
        data-isso-css="true"
        data-isso-lang="en"
        data-isso-reply-to-self="false"
        data-isso-require-author="false"
        data-isso-require-email="false"
        data-isso-max-comments-top="10"
        data-isso-max-comments-nested="5"
        data-isso-reveal-on-click="5"
        data-isso-avatar="true"
        data-isso-avatar-bg="#f0f0f0"
        data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 #2069b6 #486910 #e4bf80 #0f0f0f"
        data-isso-vote="true"
        data-vote-levels="[-5,5,15]"        
        src="//raspatan.github.io/test/blog/isso/js/embed.min.js"></script>    
    <section id="isso-thread"></section>

</div>    	
```

And the isso config uses:

```
host = https://raspatan.github.io/test/blog/
listen = http://raspatan.github.io/test/blog/isso/
```

However, I get this error when loading isso config file: 

```
Traceback (most recent call last):
  File "/usr/local/bin/isso", line 11, in <module>
    sys.exit(main())
  File "/opt/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 262, in main
    use_reloader=conf.getboolean('server', 'reload'))
  File "/opt/isso/local/lib/python2.7/site-packages/werkzeug/serving.py", line 736, in run_simple
    inner()
  File "/opt/isso/local/lib/python2.7/site-packages/werkzeug/serving.py", line 696, in inner
    fd=fd)
  File "/opt/isso/local/lib/python2.7/site-packages/werkzeug/serving.py", line 584, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/opt/isso/local/lib/python2.7/site-packages/werkzeug/serving.py", line 501, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
```

The problem is however more basic. The comment box does not appear! There might be a problem with the javascript? Apparently you need to source every js file in the github repository. Maybe this is why the comment box is not even there? I am in #isso freenode channel, if you fancy that method.

**Comment by Libbum** [comment]
(Sorry, I don't have time for a live chat right at the moment).
You're miss-understanding what the proxy portion means here. `/blog/isso` is a directory that doesn't physically exist, but it's where isso will populate its directory tree to. What you've done in your repository needs to be rolled back - don't have anything in `/blog/isso` at all.

So you've droped nginx and are just looking at localhost:4000 for your blog and localhost:8080 for isso yes? [This](https://posativ.org/isso/api/) is what you should see when you go to localhost:8080. Is that correct?

**Comment by raspatan** [comment]
@Libbum (btw, I managed to make it work locally, not in github). 

So, I rolled back the changes in the github repository. This is what I have attempted so far:

html code:

```
 <script type="text/javascript" 
        data-title="Comments"
        data-isso="//localhost:8080/"
        data-isso-css="true"
        data-isso-lang="en"
        data-isso-reply-to-self="false"
        data-isso-require-author="false"
        data-isso-require-email="false"
        data-isso-max-comments-top="10"
        data-isso-max-comments-nested="5"
        data-isso-reveal-on-click="5"
        data-isso-avatar="true"
        data-isso-avatar-bg="#f0f0f0"
        data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 #2069b6 #486910 #e4bf80 #0f0f0f"
        data-isso-vote="true"
        data-vote-levels="[-5,5,15]"        
        src="//localhost:8080/js/embed.min.js"></script>    
    <section id="isso-thread"></section>
```


isso config:
`
host = https://raspatan.github.io/test/
listen = http://localhost:8080
`

nginx config:
`
server {
    listen       [::]:80;
    listen       [::]:443 ssl;
    server_name  raspatan.github.io;
    root         ...;

    location /blog/isso {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Script-Name /blog/isso;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:8080;
    }
}
`

This shows no comment box, and in the developer tool, I can see the error is this:

    GET https://localhost:8080/js/embed.min.js net::ERR_SSL_PROTOCOL_ERROR

I also tried in the nginx with `server_name raspatan.github.io/test`, without difference (although I get an error message when starting nginx (`nginx: [warn] server name "raspatan.github.io/test" has suspicious symbols in /etc/nginx/nginx.conf:90`).

Finally, initializing isso works fine, but I get a message every other minute:

`2017-04-17 19:09:01,119 ERROR: 127.0.0.1 - - [17/Apr/2017 19:09:01] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\xc4\x01\x00\x00\xc0\x03\x03\x1b')`

Maybe there is a problem with permissions? Basically, isso cannot write in my website?

**Comment by Libbum** [comment]
That's getting closer.

`server_name  raspatan.github.io;` is what you need. But you need to add a `root`. As you need you blog to be at `raspatan.github.io/test/blog/`, you need `root /path/to/;`(/test/) if that makes sense? Your root needs to be the parent of the 'test' directory. 

In isso.conf, set

    host =
        http://raspatan.github.io/test/
        https://raspatan.github.io/test/

which may ease up your SSL protocol error ([refer to the **host** section here](https://posativ.org/isso/docs/configuration/server/)).

**Comment by raspatan** [comment]
@Libbum As per a previous question, I get the Bad Request message with http://localhost:8080/ but not with https://localhost:8080/. There, the message is:

```
This site can’t provide a secure connection

localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

I eliminated the previous SSL problem with your configuration, although not sure what to put in root. This is what I added there: `http://github.com/raspatan/test/`

Unfortunately, the comment box is not there, probably because the js does not exist. According to Inspect, the js code cannot be found, because the file `https://raspatan.github.io/test/blog/isso/js/embed.min.js` does not exist. So isso is not creating anything.

Maybe this boils down to permission problems?

**Comment by Libbum** [comment]
If you're serving what is in your github's test repo, you still have an isso folder there with foo.txt in it. That probably needs to be removed.
The js exists. It's just being served through the proxy - that is if the proxy worked. Root is the folder on disk that you want to serve up to your web page. I'm not sure how you have a web page working at the moment with no root variable. But since you do, there's going to be something else coming from another configuration fighting to serve the same thing. Please give me the full outputs of your nginx config files, isso.conf, /var/log/nginx/error.log and /opt/isso/notifications.log.

**Comment by raspatan** [comment]
@Libbum Eliminated the isso folder. No difference. I think the proxy is not working, because I add random characters to the websites and etc, and nothing changes. The error is the same, all messages the same. 

The website is hosted by github, and as such, all the files are in github, not in my machine. For example, the blog html is [here](https://github.com/raspatan/test/blob/master/blog/blog.html). Thus, for root, I don't know why I should put a local folder.

This is the last iteration of configuration I have:

- [isso](https://pastebin.ubuntu.com/24406113/)
- [nginx](https://pastebin.ubuntu.com/24406146/)
- [blog html](view-source:https://raspatan.github.io/test/blog/blog.html)
- nginx error log (all fine here. file only has: `2017/04/18 09:07:26 [notice] 3662#3662: signal process started` etc)
- isso notifications are in stdout. Nothing interesting here. Just: `connected to https://raspatan.github.io/test/blog/isso/`

Now, the thing is, how can I (or for that matter, anyone) simply affect my website by using a proxy and pushing an isso instance, with a particular commentary database? For instance, if this is ever going to work, what prevents you from serving an isso instance to my website? Don't you just need to point isso.cfg to my website? 

My ability to implement this make sense if I have writing permissions on a local folder which is serving my website, but if the files are hosted in github.com, I just can't see how isso will ever write something on github hosting. Nowhere I am being asked for authentication. But maybe I'm not understanding how all this proxy thing works.

Actually, if you fancy, feel free to clone my test repo and enable isso yourself. That might be quicker than email iterations.

**Comment by Libbum** [comment]
Right. I've never used github pages so I've been trying to get you to do things that seemingly just wont work. 
`root http://github.com/raspatan/test;` isn't going to work. It's a path on the machine that is serving the website. Isso is self hosted, meaning that you need to run your own webserver. Do you have another domain you control on a VPS that you are running nginx on or just the github pages subdomain? If not, are you planning to host your isso comment system on your home computer? Will it be on all of the time? Do you have it set up such that you can access it outside your home network? Is your firewall allowing access to port 8080?

**Comment by Libbum** [comment]
To answer your questions a little better - isso will never write something to github hosting. I'm not sure what github pages has running under the hood. For argument sake lets say it's running nginx and your files are hosted in /home/raspatan/test/ on disk on the github machine. Thus `root /home/raspatan/test/;` would serve up your webpage if you run nginx on the github server. Then, `https://localhost:8080` is the **github** server, not your machine (i.e. *localhost* relative to nginx). The proxy running at `/blog/isso` points not to /home/raspatan/test/blog/isso/ but to a completely different place on disk. Think of it as a soft link: `ln -s blog/isso /usr/lib/python2.7/dist-packages/isso/´ or something similar. For this to work, isso, nginx and your blog files all need to be on the same machine.

We can get the comments working from a different machine, it's just going to require a different setup. So first thing is first. On the machine you have nginx and isso running. If you look at it from the outside, ie not accessing it via *localhost:8080*, can you see  [this](https://posativ.org/isso/api/)?

**Comment by raspatan** [comment]
@Libbum Thanks for the clarifications. I am planning to buy a hosting, so there I will have (I imagine) a particular folder where I can upload stuff, setup proxy, etc. I will not use my own pc to set up a server. Will isso work in such system? Or am I just wasting my time with isso and should simply implement disqus? (btw, disqus works in github, but that is maybe because it is not self-hosted as isso?)

I guess I cannot really know the address where my files are on the github machine, nor know whether they use nginx or not.

Regarding your last question, how to "look at it from the outside"? Not sure what you mean by it. Total noob here.

**Comment by Libbum** [comment]
OK, now that I understand your situation better, this wont work in its current form no. 

Disqus has its own servers and you can connect to your github pages though that way - yes. So Disqus hosts your comments for you. Isso is 'self' hosted, so you have control over your own comments and ecosystem, and Disqus can't use that information or your website for its own revenue activities (e.g. advertising and information selling).

Even if you buy hosting this still may not work. There's a thing called "shared hosting" where you effectively get just a place to put files, and this is what github pages is. You have no control over what you do with the server, it just serves files. What you'll need is a VPS (virtual private server) that you can log in to, run nginx yourself, have isso running on it too and serve everything by yourself. Until you have something like that Disqus is a good solution for you, Isso is not unfortunately.

What I mean by the last question: your current github pages website `raspatan.github.io` is hosted on a machine called `github.map.fastly.net` (which *may* use nginx to serve up a page that would have settings perhaps along the lines of `server_name  raspatan.github.io; root /home/raspatan/test;`). It has an IP address of `151.101.84.133`. 

Say for argument that this machine was actually your home computer. If it was setup this way, you could access the webpages served on that machine by going to http://127.0.0.1/ or http://localhost/ or the **internal** IP address of your computer, usually given to you by your router. Most of the time that would be http://192.168.0.1/. However, you would be the only person that could access this. My *localhost* is not yours etc. By 'from the outside' I mean using your **external** IP address. So if you didn't have a domain pointing to your IP address you could access the websites via http://151.101.84.133/. If Isso was installed and working you should be able to access it both via an internal http://localhost:8080/ and external (from the outside) http://151.101.84.133:8080/.

**Comment by raspatan** [comment]
@Libbum Oh, I see. So I need to choose between standard web shared hosting (what I was planning to have) and VPS hosting. The latter would allow me to use isso. Clear now. 

Going to http://127.0.0.1/ or http://localhost/ show me the message:

```
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.
```

However, http://151.101.84.133:8080/ is permanently loading. Nothing happens. So I guess isso is not really working there. This probably confirms the issue of shared hosting under github. 

Since I managed to make isso work locally, and will not use github but probably some cheap vps for my website, I guess is not point trying to make it work in github (as it seems it won't work). I guess we should not be spending more time on this. If you think you know a way to make it work, I am happy to continue the discussion. I am learning a lot here.

**Comment by Libbum** [comment]
Indeed http://151.101.84.133:8080/ wont work because that was just a hypothetical. That's the IP address of a github machine. The easiest way you can see your own external IP just by typing "what is my IP" into google or most search engines. Then if you have port 80 open on your router and forwarded to your local machine, you should also see the nginx message. To see the Isso service you have running you also need to have port 8080 forwarded to you machine in your router. 

But this is getting off topic and I think you should close this issue as it's not related to Isso at all. I'm happy to keep answering your questions though - there's a lot to learn and it takes some time. &#116;&#105;&#109;&#064;&#110;&#101;&#111;&#112;&#104;&#105;&#108;&#117;&#115;&#046;&#110;&#101;&#116;

**Comment by posativ** [comment]
@Libbum thanks.

The initial issue have been resolved via IRC and the remaining setup is only partially related to Isso, hence I'll close this issue.
