### ISSUE TITLE
Feature request: Add short section about manual moderation to documentation

### ISSUE THREAD

**Issue by martinruenz** [posativ/isso#323]
In some cases it is helpful to edit the comments database manually, for instance, when the moderation email was not sent for some reason.

It would have saved me a bit of time to find a section like the following under **Configuration** > **Server**:

_The comments database can easily be edited manually using tools such as sqllite3. The following statements, for example, list all comments, show the text for a single comment with id 17, and then set this comment's moderation flag to accepted (1: accepted, 2: in moderation queue)._ 
```
/* Consider setting '.mode column' for better readability */
select * from comments;
select text from comments where id=17;
update comments set mode=1 where id=17;
```

**Comment by blatinier** [comment]
You found a bug and knowing the db schema helped you finding a 
workaround, but IMO, documentation is not really the place to explain 
the db schema...
What you really need is either a working moderation mail or something 
more like #10 I think (a real admin interface which is implemented in PR 
#256 ).

**Comment by martinruenz** [comment]
To be honest, I actually prefer not having an admin interface. Doing the same via sqllite3 is not (much) more effort and and admin interface just adds more complexity and potential bugs / vulnerabilities to the code-base.

**Comment by blatinier** [comment]
Closing since an interface might add some bug/vulnerabilities but it's a much better idea than messing around with the database (oups forgot/mistyped the where clause… etc…).

@jelmer @posativ if you disagree, please reopen.
Anyway admin interface is planned ( #10 ) and on it's way ( #256 ) so...
