### ISSUE TITLE
Error 403, forbidden

### ISSUE THREAD

**Issue by Thunderbottom** [posativ/isso#327]
When I try to post a comment on the site, I see this in the web console:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> (embed.min.js, line 19)
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>3 direct responses to /post/tensorflow/variables/</p>
```

**Comment by Thunderbottom** [comment]
Fixed, apparently I'm too dumb to read and I should just go and sleep.

**Comment by noisytoken** [comment]
I am facing the same issue. How did you resolved the issue ?

**Comment by Thunderbottom** [comment]
I don't really remember, it was 6 months ago!
