### ISSUE TITLE
The audit email article URL address error.

### ISSUE THREAD

**Issue by Hscpro** [posativ/isso#329]
If I set data-isso-id as a number (article ID).
![20170629_174044](https://user-images.githubusercontent.com/13926044/27681709-b595acc0-5cf2-11e7-907b-09593d00d62e.jpg)

The email post URL address has been changed. This change is the wrong address. Is there any way?
![20170629_174004](https://user-images.githubusercontent.com/13926044/27681492-0aed6bb4-5cf2-11e7-8d5e-8fe0ae6c7390.jpg)
The correct article address should be：http://test.hscbook.com/article/raspberrypi-seafile#isso-1

English is not my main language, please understand.
Thank you！

**Comment by Hscpro** [comment]
@posativ

**Comment by posativ** [comment]
The `data-isso-id` does not really work as intended. I've removed it from the documentation for now.
