### ISSUE TITLE
ERROR: No website(s) configured, Isso won't work.

### ISSUE THREAD

**Issue by olahivepriyanka** [posativ/isso#330]
i am installing from the source and i could run till 
'python setup.py develop' in virtualenv
but when i execute 'isso run' it is saying ERROR: No website(s) configured, Isso won't work.. where do i need to set this?

**Comment by Tetsumaki** [comment]
You have configured "host =" in isso.conf ?

**Comment by posativ** [comment]
Yup, that's an incomplete configuration.
