### ISSUE TITLE
Improve Accessibility of the Comment Textfield

### ISSUE THREAD

**Issue by austinseraphin** [posativ/isso#338]
The accessibility of the textfield for leaving a comment could use a little improving. A label would help identify it, as with the other fields. Also, for some reason, Firefox on Linux gets confused by it and reads a blank line, but Safari on a Mac has no problem identifying it as a textfield.

**Comment by ix5** [comment]
Some basic approaches mentioned in https://github.com/posativ/isso/pull/353#issuecomment-346217728

**Comment by ix5** [comment]
Should be fixed by https://github.com/posativ/isso/pull/861
