### ISSUE TITLE
[support] Keep getting 404 for the Javascript

### ISSUE THREAD

**Issue by Konzertheld** [posativ/isso#340]
Hi, I can't get isso to run because I keep getting 404s on my JavaScript file.

Nginx conf:
```
server {
    listen [::]:80;
    server_name test.konzertheld.de;

    location / {
        proxy_pass http://localhost:8081;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Isso conf:
```
[general]
dbpath = /home/christian/virtualenvs/isso/user/comments.db
host = https://konzertheld.de
[server]
listen = http://localhost:8081/
```

Startup command:
`isso -c ~/virtualenvs/isso/user/isso.conf run`

Executing
`wget localhost:8081/js/embed.min.js`

on the server works (file is downloaded).

The configs are almost exactly copied from the doc. Still https://test.konzertheld.de/js/embed.min.js returns 404. What did I miss?

**Comment by posativ** [comment]
Isso doesn't seem to be proxied here. You seem to have a wild card HTTP -> HTTPS redirection and your configuration uses HTTP for Isso.

**Comment by Konzertheld** [comment]
Yes, I have. So that is a problem for proxying? I just tried to run the Isso server on https, but that leaves me with

```
Traceback (most recent call last):
  File "/usr/local/bin/isso", line 11, in <module>
    sys.exit(main())
  File "/home/christian/virtualenvs/isso/local/lib/python2.7/site-packages/isso/__init__.py", line 270, in main
    wsgi.SocketHTTPServer(sock, make_app(conf)).serve_forever()
  File "/home/christian/virtualenvs/isso/local/lib/python2.7/site-packages/isso/wsgi.py", line 203, in __init__
    HTTPServer.__init__(self, sock, SocketWSGIRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 110, in server_bind
    self.server_name = socket.getfqdn(host)
  File "/usr/lib/python2.7/socket.py", line 141, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
TypeError: gethostbyaddr() argument 1 must be string without null bytes, not str
```

**Comment by posativ** [comment]
What is your Isso configuration? It seems that you were trying to run Isso on a socket, previously you used `http://localhost:8081`.

**Comment by Konzertheld** [comment]
Yes, my Isso config is the same as posted above except I changed http to https. Just a guess that was wrong apparently :)

**Comment by ix5** [comment]
Looking at https://konzertheld.de/, seems this is fixed.
