### ISSUE TITLE
Possibility to use Local Sendmail?

### ISSUE THREAD

**Issue by late-in-autumn** [posativ/isso#346]
I wounder if I can actually use my local `sendmail` daemon (which pipes system-wide mail to an external SMTP server) with isso? The config file only demonstrated with SMTP, and I would like to know if `sendmail` support is possible.

**Comment by blatinier** [comment]
This is linked to the syscall pr. Y ou can try it by cloning the pr or wait for it to be reviewed and merged.

**Comment by Konzertheld** [comment]
I was curious about this, too, I think this PR is meant https://github.com/posativ/isso/pull/457

**Comment by ix5** [comment]
This might be implemented during a more comprehensive overhaul of the whole logging and notification architecture. Closing as stale since no one wants to work on this.
