### ISSUE TITLE
Not finding the embed.js file

### ISSUE THREAD

**Issue by rawsh** [posativ/isso#352]
wget localhost:8001/js/embed.min.js gives a 404. Isso has the host=https://www.devpy.me and listen on http://localhost:8001 with nothing else changed. What's going on?

https://www.devpy.me/isso/js/embed.min.js/

**Comment by rawsh** [comment]
Any updates on this?

**Comment by jelmer** [comment]
What version of isso are you using? Do you have a embed.min.js or embed.dev.js file installed?

**Comment by rawsh** [comment]
@jelmer I was using the git version from source. The pip version works now

**Comment by rawsh** [comment]
I'm not sure if I should leave this open as it's an issue with the git version but not the release

**Comment by jelmer** [comment]
If you're running the git version, you need to run "make init" as documented in docs/docs/install.rst (https://posativ.org/isso/docs/install/)

**Comment by rawsh** [comment]
@jelmer I get ReferenceError: hu is not defined
embed.min.js:18:23854

**Comment by jelmer** [comment]
That should be fixed in current master.
