### ISSUE TITLE
run isso without proxy on localhost

### ISSUE THREAD

**Issue by pauledd** [posativ/isso#360]
Hi there
I want to test isso on a localhost without any proxy? Is this possible?
Ive installed lighttpd as my local webserver. I can reach my index.html at
http://localhost. My /etc/isso.conf looks like this:
```
[general]
dbpath = /tmp/comments.db
host = http://localhost
[server]
listen = http://localhost:1234/
```
I run "isso -c /etc/isso.conf run"
`2017-12-05 20:47:00,805 INFO: connected to http://localhost`
but when I try to check with curl I get this:
curl http://localhost:1234/js/embed_min.js
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```
shouldnt it return some javascript?
any ideas anyone what I am doing wrong?

**Comment by artur-shaik** [comment]
Try this url: http://localhost:1234/js/embed.min.js

**Comment by pauledd** [comment]
Sorry, I had a typing error. Of cause I used:
`curl http://localhost:1234/js/embed.min.js`
So it seems my installation is somehow faulty...
I will try to install isso in a VM and see how it behaves there.
I am on gentoo and we dont have isso in the package manager.

**Comment by pauledd** [comment]
Damn Yes but obviously I made a mistake somewhere. I just deleted everything, did a "pip install --user isso" again, and symlinked ~/.local/bin/isso to /usr/bin/isso and viola:
curl http://localhost:1234/js/embed.min.js
```
/**
 * @license almond 0.3.1 Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved.
 * Available via the MIT or new BSD license.
 * see: http://github.com/jrburke/almond for details
 */

/*
  Copyright (C) 2013 Gregory Schier <gschier1990@gmail.com>
  Copyright (C) 2013 Martin Zimmermann <info@posativ.org>

  Inspired by http://codepen.io/gschier/pen/GLvAy
*/

/*
 * Copyright 2014, Martin Zimmermann <info@posativ.org>. All rights reserved.
 * Distributed under the MIT license
 */

!function(){var requirejs,
.......
.......
```
Thanks for the hint and closed :)
