### ISSUE TITLE
Is it possible to install isso on another computer?

### ISSUE THREAD

**Issue by somenxavier** [posativ/isso#362]
Perhaps you [assume](https://posativ.org/isso/docs/quickstart/#configuration) that isso and web server are in the same computer. Can we install isso in another computer? My specific question is: if I have a web page in Github and isso installed in dynamic web host [http://something.dynu,com], how can I configure it?

Thanks,

**Comment by SnorlaxYum** [comment]
Take a peek at this: https://posativ.org/isso/docs/quickstart/#integration

So it is possible to do this (My site is a living example of a web page in Github and isso installed in another server), just edit the script code: 
`<script data-isso="http://something.dynu,com/"
        src="http://something.dynu,com/js/embed.min.js"></script>`

It is okay to use the `embed.min.js` from any other web as long as it is suitable, like this:
`<script data-isso="http://something.dynu,com/"
        src="http://another.com/the/path/embed.min.js"></script>`

Remember the `data-isso` has to be your isso web url.
BTW, take a peek at the documentation before asking.

**Comment by somenxavier** [comment]
OK.
