### ISSUE TITLE
404 for JavaScript files

### ISSUE THREAD

**Issue by nemani** [posativ/isso#365]
I installed isso from source. (current master)
I made a file demo.html served on localhost:8000 using python HTTP Simple Server
```
<script src="//localhost:8080/js/embed.min.js"></script>
    <section id="isso-thread"></section>
</body>
```
My nginx config:
```
	server {
	    listen 8080;
	    server_name localhost;

	    location / {
	        proxy_pass http://localhost:1234;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_set_header Host $host;
	        proxy_set_header X-Forwarded-Proto $scheme;
	    }
	}
```
isso.cfg
```
[general]
dbpath = /home/arjun/isso_demo/comments.db
host = localhost:8000
[server]
listen = http://localhost:1234/
```

Log when script source is localhost:8080
```
$ isso -c isso.cfg run
2017-12-18 17:26:24,660 INFO: connected to localhost:8000
127.0.0.1 - - [2017-12-18 17:26:29] "GET /js/embed.dev.js HTTP/1.0" 404 625 0.000662
127.0.0.1 - - [2017-12-18 17:28:20] "GET /js/embed.min.js HTTP/1.0" 404 625 0.000501
127.0.0.1 - - [2017-12-18 17:29:36] "GET /js/embed.js HTTP/1.0" 404 625 0.000600
```

Log when script source is localhost:1234
```
$ isso -c isso.cfg run
2017-12-18 17:29:41,223 INFO: connected to localhost:8000
127.0.0.1 - - [2017-12-18 17:29:44] "GET /js/embed.dev.js HTTP/1.1" 404 606 0.000538
127.0.0.1 - - [2017-12-18 17:30:00] "GET /js/embed.min.js HTTP/1.1" 404 606 0.000522
127.0.0.1 - - [2017-12-18 17:30:36] "GET /js/embed.js HTTP/1.1" 404 606 0.000381
```

Am I missing something?

**Comment by nemaniarjun** [comment]
@posativ any help?

**Comment by hamoid** [comment]
I'm having the same issue. I did run `make js`. If I do it again it says `Nothing to be done for 'js'`.

Interestingly, I can access /admin and see the comments there.

![image](https://user-images.githubusercontent.com/108264/79046990-4d856780-7c14-11ea-815b-88d166961cb4.png)

But there's no static files. Aren't both accessed via the same URL? In my case, an https to my server, then nginx talking to http://127.0.0.1:8080/isso/...

In my nginx log I see this:

    2020/04/11 15:15:32 [error] 12082#12082: *2211750 connect() failed (111: Connection refused)
    while connecting to upstream, client: 87.117.159.123, server: foo.org, request: 
    "GET /isso/js/embed.min.js HTTP/2.0", upstream: "http://127.0.0.1:8080/isso/js/embed.min.js",
    host: "foo.org", referrer: "https://foo.org/bar.html"

Where should I poke? :)

**Comment by hamoid** [comment]
I just pulled the latest changes today and I think the fix to the headers in nginx solved it. 

https://github.com/posativ/isso/commit/080ee3637108d985a0bd97dc1db99cc4f3a16f2e

My comments are back :)

**Comment by ix5** [comment]
@nemani is this still current?

**Comment by nemani** [comment]
I haven't looked at it in quite some time, feel free to close it if you want to.
