### ISSUE TITLE
Change placeholder text

### ISSUE THREAD

**Issue by rabas007** [posativ/isso#366]
How, where to change placeholder text "Type comment here (at least 3 chars)"???

**Comment by isaac-philip** [comment]
You would get the text in the following two files on the second line,

1. isso/js/app/i18n/en.js 
2. isso/js/app/i18n/da.js

Changing in **en.js** should suffice.

Let us know if you face any issues.

**Comment by rabas007** [comment]
@isaac-philip - Hi ... thank you for reply.

I do not have these files... I use Docker image and how I currently have it set up is following...

How and where to make the changes you suggest?

`<script data-isso="https://isso.mydomain.com/" src="https://isso.mydomain.com/js/embed.min.js"></script>

<script data-isso="/prefix/" data-isso-css="false" data-isso-lang="en" data-isso-reply-to-self="true" data-isso-require-author="true"
    data-isso-require-email="true" data-isso-max-comments-top="3" data-isso-max-comments-nested="5" data-isso-reveal-on-click="2"
    data-isso-avatar="true" data-isso-avatar-bg="#f0f0f0" data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 ..." data-isso-vote="true"
    data-vote-levels="" src="/prefix/js/embed.js"></script>`

**Comment by x43x61x69** [comment]
I edited the `/usr/local/lib/python3.6/dist-packages/isso/js/app/i18n/en.js` and restart isso. It's still the same tho. 

Any possible steps I could have missed?

**Comment by blatinier** [comment]
You need to compile js again I think.
Run `make js` in the folder where the Makefile is

**Comment by mdehghani65** [comment]
i found using a javascript approach easier. you may use this script in your website to change the default placeholder string:

`function waitForElement(qstring, callBack){
    window.setTimeout(function(){
      var element = document.querySelector(qstring);
      if(element){
        callBack(qstring, element);
      }else{
        waitForElement(qstring, callBack);
      }
    },500)
  }
  
  waitForElement("#isso-thread > div.isso-postbox > div > div > div.textarea.placeholder",function(qs,el){
      el.innerHTML = "your desired customized placeholder string ... " 
  });`
