### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by rawsh** [posativ/isso#367]
With disqus, commenters will receive an email on reply. Does this exist in isso or does only the author get notifications? My use case is that emails are required and smtp is set up

**Comment by blatinier** [comment]
There is a PR open for this but not merged yet since some optout mecanism is missing. You can install isso from this PR, it is working if I remember well. I let you find tge PR, it's not easyon my phone with my connection :)
null

**Comment by blatinier** [comment]
I saw you found the PR. I close here.
