### ISSUE TITLE
how can i use isso in django?

### ISSUE THREAD

**Issue by supertpx** [posativ/isso#368]
hello there, i wanna use isso in my blog, which is build by django,  can u give me some help?

**Comment by blatinier** [comment]
Integrating isso in Django is no different than in any other tech. Go through https://posativ.org/isso/docs/install/ and the quickstart. 
The isso server is standalone, db too.
The html tags are to be placed in your templates.
Feel free to ask more precise question if you have trouble with the doc.

**Comment by blatinier** [comment]
I close this issue and let you open something more specific when needed.

**Comment by ogurec-ogurec** [comment]
@supertpx hi, have you figured out how to install isso on django?)
