### ISSUE TITLE
Uncaught TypeError in embed.js

### ISSUE THREAD

**Issue by RedL0tus** [posativ/isso#372]
![image](https://user-images.githubusercontent.com/16459559/35136940-7c8d9ba6-fc9b-11e7-91f2-9f74b94d1f10.png)

`Uncaught TypeError: $(...).append is not a function`

Code around the error:

    domready(function() {

        if (config["css"]) {
            var style = $.new("style");
            style.type = "text/css";
            style.textContent = css.inline;
            $("head").append(style);
        }

        count();

        if ($("#isso-thread") === null) {
            return console.log("abort, #isso-thread is missing");
        }

        $("#isso-thread").append($.new('h4')); // This line
        $("#isso-thread").append(new isso.Postbox(null));
        $("#isso-thread").append('<div id="isso-root"></div>');

        api.fetch($("#isso-thread").getAttribute("data-isso-id"),
            config["max-comments-top"],
            config["max-comments-nested"]).then(
            function(rv) {
                if (rv.total_replies === 0) {
                    $("#isso-thread > h4").textContent = i18n.translate("no-comments");
                    return;
                }

It's the newest version in pip source.

**Comment by ix5** [comment]
Should be fixed by linked PR.
