### ISSUE TITLE
add rel=nofollow to links

### ISSUE THREAD

**Issue by noisytoken** [posativ/isso#373]
Is there any easy way to add `rel='nofollow'` to links?

**Comment by SnorlaxYum** [comment]
Edit the `embed.min.js` u r using.
That's the only possible way to do this.
It's not that hard. I added a 'target="_blank"' to the link through this way.

**Comment by noisytoken** [comment]
There is no such default option, as far as I know.

**Comment by skorokithakis** [comment]
This is rather critical, I keep getting a lot of link spam because people have figured out that there's no "nofollow" on the links.
