### ISSUE TITLE
Unable to run with the latest version of ghost

### ISSUE THREAD

**Issue by tuxflo** [posativ/isso#381]
After upgrading to the latest version of ghost (version 1.20) I'm unable to get isso running.
When inserting the following code
`  
        <script data-isso="http://comments.webdnd.de" src="http://comments.webdnd.de/js/embed.min.js"></script>`
to the page.hbs file an empty box appears without any content.
Any ideas how to start debugging that?
I'm running isso on an uberspace host and the blog url is blog.webdnd.de

**Comment by Fryboyter** [comment]
You integrate Isso via http, but the blog is called up via https. The developer tools of my browser therefore complain as follows:

Mixed Content: The page at' https://blog.webdnd.de/verruckte-welt-wenn-windows-programme-unter-linux-besser-laufen/' was loaded over HTTPS, but requested an insecure script' http://comments.webdnd.de/js/embed.min.js'. This request has been blocked; the content must be served over HTTPS.

What happens if you integrate Isso via https?

**Comment by tuxflo** [comment]
Hi and Thanks for the quick reply.
I changed the URL to https and it is shown now, however I still receive the following error messages
```
Failed to load https://comments.webdnd.de/count: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://blog.webdnd.de' that is not equal to the supplied origin. Origin 'https://blog.webdnd.de' is therefore not allowed access.
```
when ghost is trying to get the current count of the comments.
Any ideas to add the domain "comments.webdnd.de" to the allowed sources?

**Comment by Fryboyter** [comment]
Currently something is going wrong with the SSL certificate on your site. Instead of Let's Encrypt the certificate is used by Uberspace. I think it would make sense if you could solve the problem first. Then I'll be happy to see if I can help you with Isso. :-)

**Comment by tuxflo** [comment]
Ok, I fixed the SSL problems (hopefully), funny that the certificate just expired, when I created this issue here. Current problems with isso:
1. I receive errors like 
```
GET https://comments.webdnd.de/?uri=%2Fdigikam-automatisch-xmp-dateien-importieren%2F&nested_limit=5 404 (NOT FOUND)
```
on every post page, old comments are not shown on the pages (maybe ghost changed the URLs with the update?)
2. The "count" function does not work anymore, before the update the number of comments was shown in the Post list (Home page)

**Comment by Fryboyter** [comment]
Sorry for the late reaction. I had the problem with error 404 once when the Isso server configuration did not fit. If I remember correctly, the host entries under[General] were wrong. Maybe that's the problem here too. But it's a guess. What I would check is whether the service for Isso is running.

**Comment by M4a1x** [comment]
Hey,
this sounds like the problem in #409 maybe something there works? 
Since you're on uberspace my solution was to add `DirectoryIndex disabled` to the `.htaccess` file for the isso server domain.

**Comment by ix5** [comment]
Is this still current? If so, would some uberspace user feel compelled to write a bit of documentation concerning how you solved your issue?

**Comment by ix5** [comment]
For the record: https://github.com/posativ/isso/commit/07ce742b7798a1140abcb292aebecd31ff242ac5 inserts M4a1x's suggestion into the docs.
