### ISSUE TITLE
Persian translation doesn't work

### ISSUE THREAD

**Issue by msudgh** [posativ/isso#382]
I'm trying to use isso with Persian translation but after reviewing javascript build file I got that it doesn't exist in the build file.

what's wrong?

**Comment by blatinier** [comment]
Isso has not yet been translated to Persian/Farsi.
If your are able to do it, it would be a great addition to the project!

**Comment by blatinier** [comment]
If you installed isso through pip, it's "normal". The persian has been added in the current in development release. You could install isso from the repo by cloning it `git clone git@github.com:posativ/isso` and then install it `cd isso && pip install .`

**Comment by msudgh** [comment]
Great, when the new version will be released with translations?

**Comment by blatinier** [comment]
That's up to @posativ who owns the package.
Any though about it @posativ if you happen to see this?

**Comment by blatinier** [comment]
@msudgh I close the issue since it's ok in the code but just pending publication.
If you are in a rush you can clone this repo and install it from the source.
