### ISSUE TITLE
Stop testing on Wheezy which reaches EOL in May?

### ISSUE THREAD

**Issue by cclauss** [posativ/isso#385]
* https://wiki.debian.org/LTS
* https://github.com/posativ/isso/blob/master/tox.ini#L25-L29
* https://github.com/posativ/isso/blob/master/.travis.yml#L12-L13

**Comment by jelmer** [comment]
Seems reasonable to me.

On 31 January 2018 14:10:54 GMT, cclauss <notifications@github.com> wrote:
>* https://wiki.debian.org/LTS
>* https://github.com/posativ/isso/blob/master/tox.ini#L25-L29
>* https://github.com/posativ/isso/blob/master/.travis.yml#L12-L13
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/posativ/isso/issues/385

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
https://www.jelmer.uk/

**Comment by blatinier** [comment]
Ok for me too.
