### ISSUE TITLE
Preview comments

### ISSUE THREAD

**Issue by TobiGr** [posativ/isso#398]
Hello everybody,

first of all, thanks for that great project. It is really useful.

We have a blog running with isso comments and many users would like to preview their comments before sending them. Is there any build in function for this or do I have to write the preview functions myself?

**Comment by blatinier** [comment]
No built-in for this I'm afraid. But feel free to contribute! 
We are a bit slow on merging PR but still grateful to include users contributions.

**Comment by TobiGr** [comment]
My idea is to use [showdown.js](https://github.com/showdownjs/showdown). I'll take a look at it, but I can't promise a PR.

**Comment by blatinier** [comment]
Just if you happen to create a PR, the philosophy of the project is to rely as much as possible on no dependencies. Keeping that in mind, the idea is to include new deps as optionnal and the feature activated via config and/or package presence.

**Comment by vincentbernat** [comment]
The rendering from showdown.js may be different from the one from Hoedown. Maybe an additional endpoint could render the preview.

**Comment by vincentbernat** [comment]
I just noticed there is a `/preview` endpoint that could be used for this...

**Comment by vincentbernat** [comment]
See #416.

**Comment by blatinier** [comment]
I merged @vincentbernat PR adding a preview to the system.
