### ISSUE TITLE
Difference between github release and pypi release

### ISSUE THREAD

**Issue by ycpei** [posativ/isso#404]
Hello,

I noticed that the [github](https://github.com/posativ/isso/releases/tag/0.10.6) and the [pypi](https://pypi.python.org/pypi/isso) releases of 0.10.6 are different. Why?

I am asking because with the same configuration, the github release does not seem to work, but the pypi one does.

**Comment by blatinier** [comment]
I don't have a good answer to that, all I can say is that @posativ who is the only one who can publish to pypi is not often available and pypi package tends to stay behind… On github @jelmer and I have some write right and use it a bit more but still not super active too.
