### ISSUE TITLE
Moderation: 404 not found

### ISSUE THREAD

**Issue by ycpei** [posativ/isso#405]
I'm using version 0.10.6 from pypi.

When I enter the url of the moderation link in the browswer, I get 404. For example here is such a url:
https://domain.tld/id/2/activate/spA.hBHlVLUW3Mg.DaAsSmUvrV (I randomly edited the key in case it is sensitive).

Where domain.tld is the domain on which I use isso.

Any idea how to debug this problem?

I can elaborate if needed. Thanks in advance.

**Comment by blatinier** [comment]
I never used mail moderation (I added the admin interface which is currently in master for that) but could you tell us which URL you use to include isso? Is it running on https?

**Comment by ycpei** [comment]
@blatinier Thanks for replying. I made some progress. My configuration binds https://domain.tld/comments, so https://domain.tld/comments/id/2/activate/spA.hBHlVLUW3Mg.DaAsSmUvrV works. I wonder whether it is a bug or if I missed something in my configuration, that caused the urls in the email to miss the /comments. I have the line
`host = https://domain.tld/comments`
in `isso.conf`, is this what you mean by which URL I use to include isso?

Oh wow there's an admin interface now? Any screenshots?

**Comment by ycpei** [comment]
I think the problem might be the same as #401.

I also use an apache2 reverse proxy setting for sub uri with the same config snippet in that issue.

**Comment by blatinier** [comment]
Yes that's probably related to #401 you're right.
I will close here as a duplicate then.

As for the screenshots:

Login:
![Login](https://www.melmelboo.fr/img/isso/login.png)

Header:
![Header](https://www.melmelboo.fr/img/isso/header-admin.png)

Comment item:
![Comment item](https://www.melmelboo.fr/img/isso/comment-item.png)
