### ISSUE TITLE
Comment feed: Links to comments are not working

### ISSUE THREAD

**Issue by mdosch** [posativ/isso#437]
I am running the master pulled from yesterday and so far it works nice and comment feeds are great as finally users have the possibility to stay updated but I found a malfunction.

In the [comment feed](https://blog.mdosch.de/fcgi-bin/isso/feed?uri=%2F2018%2F05%2F04%2Fseite-fuer-xmpp-einsteiger-sucht-unterstuetzer%2F) for [this site](https://blog.mdosch.de/2018/05/04/seite-fuer-xmpp-einsteiger-sucht-unterstuetzer/) you don't get to the comment if you click on a comment link as there is a wrong URL shown.

Maybe it is due to me using relative links everywhere to make my site also work as hidden service without changing links in the compiled website. Or maybe I made something wrong while [updating](https://blog.mdosch.de/2018/05/06/aktuellen-master-von-isso-auf-uberspace-6-nutzen/) as this was try and error.

**Comment by blatinier** [comment]
Could you post your `isso.conf`?

**Comment by mdosch** [comment]
```
[general]
dbpath = /home/md85/etc/isso/comments.db
host =
    https://blog.mdosch.de/
    http://blog.mdosch.de/
notify = smtp
max-age = 2h
log-file = /home/md85/isso.log

[smtp]
host = localhost
port = 25
security = none
to = REDACTED
from = "Kommentarsystem blog.mdosch.de" <no-reply@mdosch.de>

[guard]
enabled = true
ratelimit = 5
direct-reply = 10
reply-to-self = false

[moderation]
enabled = false
purge-after = 30d

[rss]
base = /
limit = 100
```

Looking at the config I am pretty sure I *** it up with `base = /`.

**Comment by vincentbernat** [comment]
When using `base = /`, `//2018/...` get interpreted as an URI whose host is `2018` as an IP address. Maybe you could use `base = ../..`?

**Comment by mdosch** [comment]
Didn't help but with `base = .` the links look like https://blog.mdosch.de/fcgi-bin/isso/2018/05/04/seite-fuer-xmpp-einsteiger-sucht-unterstuetzer/#isso-605 so I am one step closer as I only have to get rid of `/fcgi-bin/isso/` in between.

**Comment by mdosch** [comment]
I'm sorry, I tried again with `../..` and it works now. Maybe it was a caching issue that it didn't work earlier.
Thank you very much for your incredible fast help.

**Comment by blatinier** [comment]
That's a great news! I close then.

**Comment by pozitron57** [comment]
I set `data-isso-feed="true"` for client and configured server with `limit=100`. However it seems that the `base` setting has no effect on the place where "Atom feed" link points. Do I need to do something else?
