### ISSUE TITLE
Feature request: Opt-In to cookies

### ISSUE THREAD

**Issue by mdosch** [posativ/isso#439]
As I try to make my blog as privacy friendly as possible (no external scripts/css/media, no tracking etc.) I'd appreciate to have a option to have commenters opt-in to cookies. Like a checkbox "remember my data" that saves the data with a cookie only when ticked (not ticked by default).

**Comment by vincentbernat** [comment]
The name, email and website are saved in local storage, not cookies. They are not transmitted unless you post a new comment. The cookie is used to modify or delete a comment, so the checkbox should be "let me edit/delete my comment", which would be a bit odd.

I am blocking cookies using `max-age = 1s` in Isso configuration and the following snippet in nginx configuration:

```
  proxy_hide_header Set-Cookie;
  proxy_hide_header X-Set-Cookie;
  proxy_ignore_headers Set-Cookie;
```

**Comment by mdosch** [comment]
>"let me edit/delete my comment", which would be a bit odd.

That would indeed look weird.

Then I will also set max-age for a reasonable time, as getting totally rid of cookies is not worth losing ability to edit comments.

**Comment by blatinier** [comment]
@mdosch should I close this or do you still need have a request regarding cookies?

**Comment by mdosch** [comment]
I am fine with closing.
