### ISSUE TITLE
textarea class conflicts with CSS libraries

### ISSUE THREAD

**Issue by mycahp** [posativ/isso#442]
Just a suggestion:

the `textarea` class conflicts with some CSS libraries. In my case, Bulma. It caused the actual textarea to not expand when content was being entered into the box.

I fixed this by adding `-isso` to all the `textarea` class references in the embed.js file. 

You might consider adopting a more specific class name like this so that it CSS libraries don't cause this type of behavior.

**Comment by ix5** [comment]
Heads up: Changing existing isso CSS will break many user setups who extend or replace isso's CSS with their own.

**Comment by ix5** [comment]
Tracked in # 816
