### ISSUE TITLE
Admin interface can not be used when using Sub-URI

### ISSUE THREAD

**Issue by Jinxiapu** [posativ/isso#444]
Beacuse  src in [templates](https://github.com/posativ/isso/tree/master/isso/templates) use an absolute address, Admin interface can not be used when using Sub-URI.
Maybe  `"/css/admin.css"`  -> `"./css/admin.css"`?

**Comment by craigphicks** [comment]
I had the same problem and fixed this with https://github.com/posativ/isso/pull/458

**Comment by blatinier** [comment]
#458 merged
