### ISSUE TITLE
Wrong URL to accept/decline moderated mails

### ISSUE THREAD

**Issue by schiessle** [posativ/isso#449]
I run isso under `https://mydomain.com/isso` and everything works great, but the links send to me by mail to accept/decline comments look like this `http://mydomain.com/id/...`, correct would be `https://mydomain.com/isso/id...`. Is there a way to configure the root of isso so that the links for the moderation mails are constructed the right way? I couldn't find anything in the documentation.

**Comment by craigphicks** [comment]
Change the line:

        uri = self.general_host + "/id/%i" % comment["id"]

to 

        uri = local.host + "/id/%i" % comment["id"]

in *isso/ext/notifications.py*, or wait for a fixed version.

**Comment by blatinier** [comment]
You can now use the `public-endpoint` configuration in the `[general]` section of isso config. It should solve your problem.
(Newly merged in master)
