### ISSUE TITLE
*almost* got isso working, but need help crossing the finish line (404) on /count

### ISSUE THREAD

**Issue by erikbethke** [posativ/isso#451]
Sorry to be a burden and ask for help.  I have read all of the documentation.  I have also read through all of the issues going back to the beginning of the project.  Quite a few questions I had were addressed with earlier issue reports and answers by positiv and others.  Thank you positiv for this amazing python comment solution - I cannot wait to get it up and running!

I followed the setup instructions from: https://stiobhart.net/2017-02-24-isso-comments/ as well as the documentation here.

# Problem:
The isso server seems to be running fine without errors in the log, I can render the isso comment box (as long as I supply the embed.min.js) and yet clicking on Submit does nothing.

## Count Failing
https://sailadastra.netlify.com/posts/isso_comments/sailadastra.netlify.com/isso/count
the server responded with a status of 404 ()

https://sailadastra.netlify.com/posts/isso_comments/sailadastra.netlify.com/isso/?uri=%2Fposts%2Fisso_comments%2F&nested_limit=5
the server responded with a status of 404 ()

After clicking on the submit button
https://sailadastra.netlify.com/posts/isso_comments/sailadastra.netlify.com/isso/new?uri=%2Fposts%2Fisso_comments%2F
the server responded with a status of 404 ()

## Client-Side code:
```
    {{ "<!-- isso -->" | safeHTML }}
    <script data-isso="sailadastra.netlify.com/isso/" src="{{ .Site.BaseURL }}js/embed.min.js"></script>
    {{ "<!-- end isso -->" | safeHTML }}

```

and the actual comment bit:
```
      {{"<!-- begin comments //-->" | safeHTML}}
      <section id="isso-thread">
      </section>
      {{"<!-- end comments //-->" | safeHTML}}
```

# Additional Context:

## Redirecting from Netlify
Site is a HUGO static site being built and served from Netlify

Netlify's redirection instruction in netlify.toml:
```
[[redirects]]
  from = "/isso/*"
  to = "http://35.237.78.217:8181/"  
  status = 200
  force = true
```

## ISSO Running on a google compute engine
ISSO is running on a virtual compute engine on google's cloud Ubuntu 18

With a firewall ingress for tcp:8181
And a firewall egress for tcp:80

## Could not solve SMTP connection
Despite having good credentials for the SMTP credentials and testing with some test python code:
```
import smtplib
server = smtplib.SMTP('sub5.mail.dreamhost.com', 587)

#Next, log in to the server
answer = server.login("info@sailadastra.com", "some really good password")

#Send the mail
msg = "Hello from PDC!" # The /n separates the message from the headers
answer2 = server.sendmail("info@sailadastra.com", "erikbethke@gmail.com", msg)

print(answer)
print(answer2)
```

I kept getting timeout errors in the iss.log, so I turned off moderation and set output to stdout
```
Traceback (most recent call last):
  File "/home/erikbethke/.local/share/virtualenvs/isso-1X4e4EMV/lib/python3.6/site-packages/isso/ext/notifications.py", line 43, in __init__
    with self:
  File "/home/erikbethke/.local/share/virtualenvs/isso-1X4e4EMV/lib/python3.6/site-packages/isso/ext/notifications.py", line 64, in __enter__
    timeout=self.conf.getint('timeout'))
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
connected to https://sailadastra.netlify.com/
```

## Using HTTP server seems happy:
```
[general]
host =
    http://sailadastra.netlify.com/

[server]
listen = http://10.142.0.2:8181/
```

Server is up and running with this happy note in the log file:
```
connected to https://sailadastra.netlify.com/
````
## ISSO does not like my HTTPS
However, *IF* I try to use https in the isso.cfg:
```
[general]
host =
    https://sailadastra.netlify.com/

[server]
listen = https://10.142.0.2:8181/
```

I get this error:

```
In my isso.cfg I get this error id I try to use https:
  File "/home/erikbethke/.local/share/virtualenvs/isso-1X4e4EMV/bin/isso", line 11, in <module>
    sys.exit(main())
  File "/home/erikbethke/.local/share/virtualenvs/isso-1X4e4EMV/lib/python3.6/site-packages/isso/__init__.py", line 270, in main
    wsgi.SocketHTTPServer(sock, make_app(conf)).serve_forever()
  File "/home/erikbethke/.local/share/virtualenvs/isso-1X4e4EMV/lib/python3.6/site-packages/isso/wsgi.py", line 203, in __init__
    HTTPServer.__init__(self, sock, SocketWSGIRequestHandler)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "/usr/lib/python3.6/socket.py", line 669, in getfqdn
    name = name.strip()
AttributeError: 'int' object has no attribute 'strip'

```

## On the embed.js
Manually hitting the dynamic js
http://sailadastra.netlify.com/isso/embed.min.js
Produces the missing uri query error page, which I believe means that ISSO is up and running, but simply grumpy because no API parameters are being sent

But, interestingly, if I try to hit the js manually at:
http://35.237.78.217:8181/js/embed.min.js
It does return the *dynamically* generated js!

## Trying data-isso variations
Tried this variation on the send:
'''
    <script data-isso="https://sailadastra.netlify.com/isso/" src="{{ .Site.BaseURL }}js/embed.min.js"></script>
'''

https://sailadastra.netlify.com/isso/count
the server responded with a status of 405 ()
https://sailadastra.netlify.com/isso/?uri=%2Fposts%2Fisso_comments%2F&nested_limit=5
the server responded with a status of 404 ()
https://sailadastra.netlify.com/isso/new?uri=%2Fposts%2Fisso_comments%2F
the server responded with a status of 405 ()

## Trying hitting the isso-server directly
And manually hitting the static ip address for
http://35.237.78.217:8181/new?uri=%2Fposts%2Fisso_comments%2F
Failed to load resource: the server responded with a status of 405 (METHOD NOT ALLOWED)

# Here is my isso.cfg
```
; |||||||||||| general settings ||||||||||||||
[general]
;database location. automatically created if doesn't already exist
dbpath = /home/erikbethke/isso/comments.db

;this will be the 'X-Script-Name' we proxy server requests to [later!]
name = isso

; your website or blog [not the location of Isso]
host =
    http://sailadastra.netlify.com/

; logfile. might need to create this first
log-file = /home/erikbethke/isso/isso.log

; get notifications by email 
notify = stdout

;||||||||||| server section ||||||||||
[server]
;port to listen on. choose a number you like!
listen = http://10.142.0.2:8181

;||||||||| smtp section [for notifications] |||||
[smtp]
;these are the details for the 'from' address Isso uses to send notifications
;you might want to use a dedicated email account for this
username = xxxx
password = xxxx
host = sub5.mail.dreamhost.com
port = 587
timeout = 10
security = starttls
;this is the 'to' address Isso sends notification emails to
to = info@sailadastra.com
;from address as shown on emails. should correspond to sender account above
from = "isso comments" <info@sailadastra.com>

;|||||| guard –Isso's basic spam protection |||||||
[guard]
enabled = true
;no. of allowed comments per minute
ratelimit = 2
;no of direct replies allowed
direct-reply = 3
;can people reply to their own comments while edit window still open
reply-to-self = false
;do commenters need to leave a name
require-author = true
;do commenters need to provide an email
require-email = false
;allowed markdown in comments. [uses misaka markdown]

[markup]
;default options allow most 'unharmful' markdown
options = strikethrough, superscript, autolink
;default allowed = a, blockquote, br, code, del, em, h1, h2, h3, h4, h5, h6, hr, ins, li, ol, p, pre, strong, table, tbody, td, th, thead, ul
;allowed-elements =
;default allowed = align, href
;allowed-attributes
;creates identicons for users across isso installations

[hash]
;OK to use this salt
salt = Eech7co8Ohloopo9Ol6baimi
algorithm = pbkdf2
;comments must be moderated before publication
;NOTE: requires "notify = smtp" to be set in the [general] section

[moderation]
enabled=false
```

**Comment by erikbethke** [comment]
Also I have these screenshots from the network inspection:
<img width="1390" alt="screen shot 2018-06-04 at 4 32 38 pm" src="https://user-images.githubusercontent.com/3238191/40946194-e84c5d54-6821-11e8-9f38-4bd066d9b4bf.png">
<img width="1391" alt="screen shot 2018-06-04 at 4 32 11 pm" src="https://user-images.githubusercontent.com/3238191/40946195-e92c5b02-6821-11e8-8499-5599ec319fb2.png">

**Comment by Feuerfuchs** [comment]
Wow, that's a lot of information and it's honestly hard to grasp what your actual problem is now.

But I'm very sure I know what's wrong. Your redirect doesn't map the request path to the isso API, so that all requests are redirected to http://35.237.78.217:8181/, with the rest of the path missing.
So when you request https://sailadastra.netlify.com/isso/js/embed.min.js, you get http://35.237.78.217:8181/. When you request https://sailadastra.netlify.com/isso/new?uri=%2Fposts%2Fisso_comments%2F, you get http://35.237.78.217:8181/?uri=%2Fposts%2Fisso_comments%2F.

What you have to use in your redirect is a "splat", [according to the Netlify documentation](https://www.netlify.com/docs/redirects/#splats):

> An asterisk indicates a splat that will match anything that follows:
> 
> You can use the splat in your rewrites or redirects like this:
> 
>     /news/*  /blog/:splat
> 
> This would redirect paths like /news/2004/01/10/my-story to /blog/2004/01/10/my-story

**Comment by erikbethke** [comment]
Wow Feuerfuchs!

Thank you so much, I just had a sip of coffee checked my mail and saw your on target direction.
A few seconds later and my netlify deploy completed and BAM!  Working comments!

Thank you so much, as you can see I was trying everything I could think of and yet couldn't get there.

Warm cheers,
-Erik

**Comment by MrCappuccino** [comment]
Hello, I am having a very similar issue with netlify [I created an issue for it](https://github.com/posativ/isso/issues/573) any ideas what I might be doing wrong?
