### ISSUE TITLE
avatar_url - how to use?

### ISSUE THREAD

**Issue by kurt-o-sys** [posativ/isso#454]
As far as I can see, one should be able to customize the avatars used in the comments. I'd like to use robohashes, so I should add `gravatar_url=https://robohash.org/{}?set=set2` somewhere... 
I added it to `config.production.json` and to isso config file, but that doesn't work. So, how can I customize the `gravatar_url`?

**Comment by SHA-256** [comment]
That's what I'd like to know. With my own avatars I could adapt Isso even further to my web design.

**Comment by kurt-o-sys** [comment]
well, hard coding it can work pretty easily. I'd prefer to have it as a configuration...

**Comment by rocka** [comment]
Please refer to https://github.com/posativ/isso/blob/master/docs/docs/configuration/server.rst#general

put `gravatar-url` under `[general]` section of the config file
