### ISSUE TITLE
Which Python versions must Isso support?

### ISSUE THREAD

**Issue by craigphicks** [posativ/isso#459]
I've submitted a [pull](https://github.com/posativ/isso/pull/457) but I'm not clear on what Python versions any submitted change must support.  2?  3.4?, or is 3.5 OK.

**Comment by blatinier** [comment]
On this I'd rather let @posativ answer. If by any chance he gets the time.

**Comment by autoferrit** [comment]
according to [setup.py](https://github.com/posativ/isso/blob/master/setup.py#L11)
```
if sys.version_info < (2, 7):
    raise SystemExit("Python 2 versions < 2.7 are not supported.")
elif (3, 0) <= sys.version_info < (3, 4):
    raise SystemExit("Python 3 versions < 3.4 are not supported.")
```
and [tox.ini](https://github.com/posativ/isso/blob/master/tox.ini#L1)
```
[tox]
envlist = py27,py34,py35,py36
```
only python 2.7, and 3.4+ will work, and only 2.7, and 3.4 to 3.6 are supported and tested against

**Comment by jelmer** [comment]
As autoferrit mentions, the current answer to this is "2.7 and >= 3.4".
