### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by StructByLightning** [posativ/isso#462]
```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#/' is not a valid selector.
```

I believe Isso is trying to use the page's url as a selector, but since it contains a # it doesn't work. The full url is [https://codexserial.com/#/](https://codexserial.com/#/) and it has the # because I'm using React's HashRouter.

The comments seem to work okay though, even after the error is thrown. So this doesn't seem to be a critical bug, just something that's a little odd and might be causing an internal problem that isn't immediately apparent.

The error is thrown at line 19 of embed.min.js, if that's at all helpful.

**Comment by ix5** [comment]
Is this still current?
