### ISSUE TITLE
Release new versions

### ISSUE THREAD

**Issue by rawsh** [posativ/isso#475]
Last release was in 2016.

**Comment by Fryboyter** [comment]
https://github.com/posativ/isso/issues/388

I suspect the problem that only @posativ can publish new versions and he has no time for it still exists.

**Comment by blatinier** [comment]
That's the issue yeah. I would take a few minutes to publish if I had the rights.

**Comment by hamoid** [comment]
@blatinier Is he not willing to share this responsibility with others? I'm thankful that he originally created isso, but I've been concerned for a while about the project being stuck and people loosing interest to contribute. I wish isso would grow and spread eating some of those data mining disquses out there :)

**Comment by blatinier** [comment]
I'd be glad about sharing the publish responsibility but numerous mentions of @posativ in github had no reactions. It seems that he hasn't been available for quite some time… And still isn't

**Comment by blatinier** [comment]
Done

**Comment by Fryboyter** [comment]
If he doesn't answer, would it be imaginable that you release an unofficial version (e.g. isso-devel) on PyPi?

**Comment by blatinier** [comment]
If no answer comes from @posativ before next week I'll consider pushing a pypi version isso-devel.
If I can manage to get some time for it of course :)

**Comment by posativ** [comment]
Hi there,

I've given maintainer access to @blatinier and @jelmer to release & manage versions on PyPi. Sorry for the hassle.

**Comment by Fryboyter** [comment]
Thank you, Martin. :-)

**Comment by jelmer** [comment]
There appear to be a lot of failing tests, which we should probably fix before doing any kind of release.

**Comment by will76** [comment]
Looking forward to new releases!

**Comment by jelmer** [comment]
Tests have all been fixed, so we should be in a good shape now to do a release.

**Comment by audas** [comment]
So is there an update coming for this ? I am slightly confused as to what has transpired, it appears others have taken over the project and an update is forthcoming ?

**Comment by jelmer** [comment]
I've pushed out 0.11.0. Please let me know of any issues.

**Comment by abnd90** [comment]
Tried the new release, the new release is missing js/embed.min.js and hence broke my site. Did the release fail to minify embed.js?

**Comment by jelmer** [comment]
I've uploaded a new release with minified embed.js included. Please let me know if that works better.

**Comment by abnd90** [comment]
Tried 0.11.1 and works well, thanks! 

@hamoid Thanks, I deploy with docker so I just reverted to an older container version.
