### ISSUE TITLE
Import disqus xml file failed

### ISSUE THREAD

**Issue by tareefdev** [posativ/isso#477]
I installed `isso` by setup virtual environment using `pipenv`, following this [guide](https://stiobhart.net/2017-02-24-isso-comments/).
When I'm trying to import my disqus xml file, I got this error:

```
Traceback (most recent call last):
  File "/home/tareef/isso/.venv/bin/isso", line 11, in <module>
    sys.exit(main())
  File "/home/tareef/isso/.venv/lib/python3.6/site-packages/isso/__init__.py", line 238, in main
    migrate.dispatch(args.type, mydb, args.dump, args.empty_id)
  File "/home/tareef/isso/.venv/lib/python3.6/site-packages/isso/migrate.py", line 279, in dispatch
    cls(db, dump).migrate()
  File "/home/tareef/isso/.venv/lib/python3.6/site-packages/isso/migrate.py", line 107, in migrate
    'email': post.find('{0}author/{0}email'.format(Disqus.ns)).text,
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by jelmer** [comment]
Do you have an example discus file with this problem (perhaps from a site without privacy-sensitive comments)?

**Comment by tareefdev** [comment]
I sent you an email with my XML file. Thanks for your interest.

**Comment by jelmer** [comment]
It looks like the issue is that the <author> elements in your disqus XML file don't have an email set.

**Comment by blatinier** [comment]
We could consider multiple solutions:
- Setting a default email if none present → I don't know the implications it will have on the result isso DB, will it work?
- Not importing comments without email → seems like not the feature users would want
- Importing comments anyway by setting a "isso-anon-email@isso.com"?

**Comment by tareefdev** [comment]
Importing comments by setting a default email sounds good.

**Comment by jelmer** [comment]
Do we need a default email? It's possible to comment without setting a proper email address.
