### ISSUE TITLE
API error message content-type ignores Accept header

### ISSUE THREAD

**Issue by sundbry** [posativ/isso#487]
When I hit the comment limit using the API, the error messages are coming back as HTML. I am using the API directly from custom javascript. 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>3 direct responses to my-test-post</p>
```

The request headers include Content-Type: application/json and _Accept: application/json_ so the server should be responding with only JSON. A simple response like {"message": "3 direct responses to my-test-post"}  should allow clients to read the reason for the error.

**Comment by ix5** [comment]
Fixed by #488
