### ISSUE TITLE
Admin interface unusable

### ISSUE THREAD

**Issue by Pofilo** [posativ/isso#494]
Hello, I just upgrade from the 0.10.5 to 0.11.1 and have some problems with the admin interface.

Here is a capture of what I get:
![image](https://user-images.githubusercontent.com/7527594/48060349-0d6abb80-e1bc-11e8-9e9e-b4f68eb29992.png)

The buttons `Edit`, `Cancel` ... at the bottom are not clickable.

I remember few months ago, I tried this interface and it was "beautifuler". Is it a CSS problem ? Is it related to https://github.com/posativ/isso/pull/458 ?

**Comment by blatinier** [comment]
Could you open the console (F12) and tell us about errors you could see and in the network part requests that return 4xx or 5xx ?

**Comment by Pofilo** [comment]
Okay, this is solved by fixing the `public-endpoint` parameter in the server configuration.
Http was used instead of https.
