### ISSUE TITLE
Email subject line missing and crazy from address label...

### ISSUE THREAD

**Issue by neocogent** [posativ/isso#497]
Just installed and tested isso. First worked ok with default moderation (off). But want to use email moderation. After hours of messing with it the best I can get is still showing no subject line and replaces the from "label" with "Ich schrei sonst!". 

This may be somewhere along the line it's wanting an email from like `XXX <xxx@yyy.com>` but I tried using a from value like that and it didn't work for me. The raw msg source has a from address but the label has been set as "Ich schrei sonst!". Google translating that comes out as: "I scream otherwise!"

Also, tried debugging the subject string and saw it is making a subject and passing to email Header() function. Seems like some problem there as in the received raw message source there is no subject inserted. 

----
As an aside - I can't figure out why when I use `systemctl status` I see log entries for each request but they do not show up in the isso.log file I've set. There is core log entries like "connect", but no requests. Where do they go then? systemctl knows where to get them so maybe emitted as stdout but then why not to the log file I have configured?

**Comment by jelmer** [comment]
Bug #139 may be relevant.

**Comment by neocogent** [comment]
That seems likely in some way. I am using this on a Pelican generated static blog site. It probably doesn't account for the strange "from" address. I don't see a fix presented for that bug or maybe I got lost in comments. I quick on a sample blog page shows no H1 being used. The test comment in threads table has a blank last column value. Not sure how to fix though.

**Comment by neocogent** [comment]
Oh. I just saw that "Ich schrei sonst!' is actually the German meaning of Isso (from overview page). I had no idea. So I guess on that aspect of my problem I'd like some way to have the From address on emails show up as something I'd understand like "Isso Admin" or whatever (in English). Is there a way to set his in config file? I tried what I thought may be obvious, eg. `from="Isso Admin <myuser@mysite.com>"` but that did not work.

**Comment by neocogent** [comment]
Ok. After more digging I managed to find you could set the `data-title` attribute on the embed tag. I tried this on my pelican template and (after some experimenting) it worked out ok. So I now have a subject line. I wonder if maybe it's a good idea to add a default subject when sending the notify email? So in notifications.py when the subject is empty add a value like "Isso Comment Moderation" or something. I'd be willing to make a PR for that is it's going to be accepted. I guess it needs to be translatable text too.

I think my issues here are resolved and are mostly about figuring out the docs on things that aren't very explicit. Speaking of explicit docs - I see there is some kind of "admin" interface now. I tried /isso/admin and got a page. Presumably a password needs to be set somewhere but I have not found that info yet. Any clues how I might use the admin panel? Otherwise can close this issue.

**Comment by jelmer** [comment]
Help to improve the admin panel further would be great. I'm not aware of anybody currently working on it apart from the PR that I have out for review.

**Comment by mmarif4u** [comment]
Hi @neocogent , did you find any solution to the email subject line. I am currently looking around but can't find anything to make it work.

**Comment by wswr** [comment]
@mmarif4u , add data attributes `data-title` (data-title="YOUR-POST-TITLE") in Client [Configuration](https://github.com/posativ/isso/blob/63cc15a96214c8e753bfcee141e0d505059b24de/docs/docs/configuration/client.rst#client-configuration).

If you use the static site generator like hugo, there is an [example](https://github.com/wswr/LowEntropy/blob/2e7f92cab1e1f24d290deb83942cfd14c4d16b98/themes/LE-base16/layouts/partials/isso.html#L4)(My blog.)

**Comment by neocogent** [comment]
@mmarif4u,
Yes. As mentioned by wswr the data-title attribute worked for me. In my case with Pelican I changed my comment section in the comments.html include file to be:

`<section id="isso-thread" data-title="{{ article.title|striptags }}"></section>`

**Comment by mmarif4u** [comment]
Thanks a lot, @neocogent and @wswr . I will check it out.
