### ISSUE TITLE
[admin]: Trailing slash in public-endpoint (was: 404 on admin page)

### ISSUE THREAD

**Issue by angristan** [posativ/isso#498]
I am running 0.11.1, and I get this error on my admin page:

> Not Found
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

I try to access `https://my-isso.tld/admin/`. I have `admin_password` and `public-endpoint` set in my config.

**Comment by jelmer** [comment]
Note that public-endpoint doesn't determine where the admin page gets served, it's just used when isso redirects to itself.

**Comment by angristan** [comment]
OK, what else should I be checking?

**Comment by angristan** [comment]
Yes it's still working great, it's been running for months on my blog. I've upgraded to the latest version so 1.11.1.

**Comment by jelmer** [comment]
Do you mean 0.11.1 ? There is no 1.11.1 release.

**Comment by angristan** [comment]
Oops, yes, 0.11.1

**Comment by frenchvandal** [comment]
I have a different issue: I can access the admin interface (no 404 error) but when I type the password (the one set in the conf file) I am still on the login page. Same version as @angristan and no other issues (comments are showing fine on my Ghost posts).

![isso](https://user-images.githubusercontent.com/42499534/49757956-f0933d80-fcbd-11e8-81f4-a4580688e568.jpg)

**Comment by blatinier** [comment]
@frenchvandal what does the Network panel tells you when you try to log in? (F12 → click on network to access this panel)

**Comment by angristan** [comment]
Adding:

```ini
[admin]
enabled = true
password = xxxx
```

While keeping

```ini
[generic]
admin_password = xxxxx
```

I get 

```
isso    | 2018-12-10 23:33:08,453 WARNING: no such option: [admin] password
isso    | 2018-12-10 23:33:08,453 WARNING: no such option: [admin] enabled
```

*But* I don't have a 404 anymore:

<img width="678" alt="screenshot 2018-12-11 at 00 36 16" src="https://user-images.githubusercontent.com/11699655/49768603-21369f80-fcdd-11e8-9844-993497659005.png">

Trying to login:
<img width="394" alt="screenshot 2018-12-11 at 00 38 36" src="https://user-images.githubusercontent.com/11699655/49768604-2267cc80-fcdd-11e8-98e1-405b8b2acbdf.png">

I read in https://github.com/posativ/isso/issues/506 that 

> The configuration variable name has changed slightly since 0.11.1; in master the name is admin/password, in 0.11.1 the name was general/admin_password.

I'm confused 🤷‍♂️

**Comment by frenchvandal** [comment]
@blatinier thanks to @angristan I did what was said in #506 (in the conf, removed password from [admin] , added admin_password in [general]).
Now the interface access is just fine.
Sorry for the thread hijacking!

**Comment by angristan** [comment]
Removing the trailing `/` in my `public-endpoint` fixed the issue in my last comment,

**Comment by jelmer** [comment]
isso should probably either

1) Fix that trailing slash for you
2) Warn you

**Comment by ix5** [comment]
Relevant: https://github.com/posativ/isso/pull/519, but this truncation should also be applied more widely
