### ISSUE TITLE
Placeholder Text

### ISSUE THREAD

**Issue by x43x61x69** [posativ/isso#505]
I edited the `/usr/local/lib/python3.6/dist-packages/isso/js/app/i18n/en.js` and restart isso. It's still the same.

Any other steps I could have missed?

**Comment by Jinxiapu** [comment]
Just [make](https://posativ.org/isso/docs/install/#install-from-source) again. You change the js source and you need to make to get a new embed.js

**Comment by x43x61x69** [comment]
I was installed via pip and the only way to do it was reinstall from source?

I would rather edit `embed.min.js` as they were just strings. But seems editing the one in `/usr/local/lib/python3.6/dist-packages/isso/js/app/` wasn't make any difference either.
