### ISSUE TITLE
third-party libraries

### ISSUE THREAD

**Issue by posativ** [posativ/isso#51]
Third-party libraries essential for Isso (and unlikely to be rewritten from scratch):
### Build dependencies
- [Jade](http://github.com/visionmedia/jade), precompile templates to JS for client execution.
- [Almond](https://github.com/jrburke/almond) – create a single file JS
- [RequireJS](http://requirejs.org/) – AMD file loader and build system
- [RequireJS' Text](https://github.com/requirejs/text) – compile non-Js resources into JS
### Runtime dependencies
- [Jade](http://github.com/visionmedia/jade) – tiny runtime.js for precompiled templates
- [werkzeug](https://github.com/mitsuhiko/werkzeug) – WSGI toolkit
- [itsdangerous](https://github.com/mitsuhiko/itsdangerous) – store signed data on untrusted clients
- [misaka](http://misaka.61924.nl/) – fast Markdown processor written in C
- [html5lib](https://github.com/html5lib/html5lib-python) – HTML(5) parser and sanitizer
#### Optional
- [passlib](http://pythonhosted.org/passlib/) – PBKDF2 implementation fallback if werkzeug 0.8
#### Python 2
- [ipaddr](http://code.google.com/p/ipaddr-py/)
- [configparser](https://pypi.python.org/pypi/configparser)

**Comment by Leryan** [comment]
Why not adding `werkzeug` to `setup.py`?

Also adding `ipaddr` and `configparser` to the list with this test might do the job: `import sys; if sys.version_info < (3,): requires.extend(['ipaddr', 'configparser'])`
