### ISSUE TITLE
Cannot activate reply-notifications

### ISSUE THREAD

**Issue by foreveryo** [posativ/isso#512]
Hello!

I've been using isso for a while on an older version previous to the "reply-notifications" update. I saw the new feature and I upgrade to the version 0.11.1 to use it.

 I have configured server side:
`reply-notifications = true`

and client side:
`data-isso-reply-notifications="true"`

but I didn't see any checkbox or anything to select the reply-notifications. Do I need to do something else?

Thanks for your help :-)

**Comment by foreveryo** [comment]
Yes, I know. I've been checking the code ;-)

**Comment by brad** [comment]
@foreveryo Any errors in the JS console? 0.11.1 is working for me. As soon as there is any text in the email field, the "reply notifications" checkbox appears

**Comment by foreveryo** [comment]
Ok, I find out the issue... It was a mistake on my side. Drupal + CDN caches were not aligned with the latest code. Now it's working fine!

Thanks for your time.
