### ISSUE TITLE
no such option: [admin] enabled

### ISSUE THREAD

**Issue by SnorlaxYum** [posativ/isso#517]
Dec 26 13:06:09 localhost isso[6592]: 2018-12-26 13:06:09,842 WARNING: no such option: [admin] password
Dec 26 13:06:09 localhost isso[6592]: 2018-12-26 13:06:09,847 WARNING: no such option: [admin] enabled

**Comment by SnorlaxYum** [comment]
$ isso --version
isso 0.11.1

**Comment by SnorlaxYum** [comment]
No such option?

**Comment by chrissly90** [comment]
But how can I remove Illegal comments from my site, without an Admin Password?

**Comment by jelmer** [comment]
You need to set an admin password to manage comments.
