### ISSUE TITLE
Browsers without language set won't display Isso comments

### ISSUE THREAD

**Issue by 0-1** [posativ/isso#521]
If a browser has no default language set, Isso won't work.

TypeError: undefined has no properties.
embed.min.js:formatted:245

Points to this line:
`lang: (navigator.language || navigator.userLanguage).split('-') [0],`

You might want to set a default language for isso if you need it.

**Comment by ix5** [comment]
Closing since https://github.com/posativ/isso/pull/674 was merged recently.
@0-1 feel free to re-open in case this is still an issue.
