### ISSUE TITLE
Fails to render Postbox if require-email = true

### ISSUE THREAD

**Issue by rocka** [posativ/isso#524]
I upgraded my isso instance to git master branch nowadays, only to find that the Postbox won't be rendered; there is an error in the console:

```
Uncaught TypeError: Cannot read property 'replace' of null
```

After some research, I found that bacause of #356, Postbox `<input>`s does not have `placeholder` attributes now. But following code:

https://github.com/posativ/isso/blob/4fe24296a2235de8d063cc3df7a93a54cc9d077f/isso/js/app/isso.js#L55-L64

requires the input to have a placeholder to work. We should either change this, or revert #356

**Comment by jelmer** [comment]
@mpchadwick thoughts?

**Comment by Laul0** [comment]
same issue ?

```
TypeError: null is not an object (evaluating 'e("[name='email']",m).getAttribute("placeholder").replace')
```

**Comment by jelmer** [comment]
Rather than trying to fix this and get it wrong again, I've just reverted it. Open to new merge proposals re-swapping placeholders for labels after 0.12.2.
