### ISSUE TITLE
Need to check whether the new comment and it's parent are in same thread

### ISSUE THREAD

**Issue by budui** [posativ/isso#531]
I am porting `isso` from Python to [Go](https://github.com/RayHY/go-isso). While testing I noticed that if I specify a wrong parent(existed but different thread) for the new comment, the new comment will be added successfully but can't be retrievaled with uri.

Maybe we need to check whether the `tid` of new comment and parent's `tid` are consistent
https://github.com/posativ/isso/blob/6092881bb205c999a8f7f086dd5d20f686d641ea/isso/db/comments.py#L49-L52

**Comment by ix5** [comment]
@budui would you mind submitting a Pull request to address this?

Btw, nice work on go-isso, but I see you've found that it's hard to maintain a project all by yourself...

**Comment by ix5** [comment]
Closing in favor of https://github.com/posativ/isso/issues/765
