### ISSUE TITLE
Reply e-mail notifications should not contain the e-mail address of commenters

### ISSUE THREAD

**Issue by Kwpolska** [posativ/isso#533]
I’d prefer not to send e-mail addresses of commenters to random people. The e-mail address should be included only in admin notifications.

(The easiest solution would be to change [the condition](https://github.com/posativ/isso/blob/c2136ce10a9b9cfe036cc5a5f6246f73246c9dc3/isso/ext/notifications.py#L112) to `if admin and comment["email"]:`, unless a decision is made to make this behavior configurable.)

**Comment by vincentbernat** [comment]
I don't think this needs to be configurable. Could you make a PR with your suggestion?

**Comment by Kwpolska** [comment]
Sure, see #535.
