### ISSUE TITLE
Isso not loading in firefox/Brave due to "unsafe scripts"

### ISSUE THREAD

**Issue by Mikeb30** [posativ/isso#538]
My subdomain: blog.mydomain.com has a certificate that I obtained when I installed ghost blog.

Apparently, when I visit my blog with firefox/brave it shows the "unsafe scripts" blocked message and when I allow it to load the comment section comes out but throws blog.mydomain.com out of SSL and shows up as unsecured, when it has a certificate.

My `/etc/nginx/conf.d/isso.conf`

> server {
>     listen 80;
>     listen [::]:80;
>     server_name isso.mydomain.com;
> 
>     access_log  /dev/null;
>     error_log /dev/null;
> 
>     access_log /var/log/nginx/isso-access.log;
>     error_log  /var/log/nginx/isso-error.log;
> 
>      location / {
>            proxy_set_header Host $http_host;
>            proxy_set_header X-Real-IP $remote_addr;
>            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>            proxy_set_header X-Forwarded-Proto $scheme;
>            proxy_pass http://localhost:8080;
>     }
> }

https://blog.mydomain.com is listed under the isso.conf file. Can anyone point me in the right direction to get this working?

Thanks.

**Comment by jelmer** [comment]
Can you give more specifics? What does the developer console in your browser say ?

**Comment by Mikeb30** [comment]
I know it's because there isn't any SSL cert, but is there any way to avoid this? I can't setup SSL because of acme.sh is hard-wired to my ghost blog installation and I can't install acme.sh standalone because it's already installed via ghost.

> (index):1 Mixed Content: The page at 'https://blog.mydomain.com/' was loaded over HTTPS, but requested an insecure script 'http://isso.mydomain.com/js/embed.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by jelmer** [comment]
That's not really an isso question, but a general JavaScript question.

Search the Web for Content Security Policy.

**Comment by Mikeb30** [comment]
Don't think it's that.

I am trying to serve isso over my main domain, blog.mydomain.com
Following this: https://posativ.org/isso/docs/setup/sub-uri/ I still get an error:

`Failed to load resource: the server responded with a status of 404 ()`

Been at this for days lol.. seriously exhausted as I've had to deal with a disruptive ghost blog/ssl generating due to the faulty cli.
Is there nothing else I could od?
