### ISSUE TITLE
Problem starting isso service

### ISSUE THREAD

**Issue by thergn** [posativ/isso#541]
I set up my isso service and while checking the status with` sudo systemctl status isso` it gave me a problematic error

isso.service - Isso Commenting Server
   Loaded: loaded (/etc/systemd/system/isso.service; enabled; vendor preset: ena
   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-03-02 16
  Process: 9309 ExecStart=/home/isso/.local/bin/isso -c /home/isso/isso.conf (co
 Main PID: 9309 (code=exited, status=1/FAILURE)

Mar 02 16:17:05 theergn systemd[1]: isso.service: Unit entered failed state.
Mar 02 16:17:05 theergn systemd[1]: isso.service: Failed with result 'exit-code
lines 1-8/8 (END)

While testing installation

rnf@theergn:~$ /home/isso/.local/bin/isso -c /home/isso/isso.conf
Traceback (most recent call last):
  File "/home/isso/.local/bin/isso", line 11, in <module>
    sys.exit(main())
  File "/home/isso/.local/lib/python3.5/site-packages/isso/__init__.py", line 237, in main
    join(dist.location, dist.project_name, "defaults.ini"), args.conf)
  File "/home/isso/.local/lib/python3.5/site-packages/isso/config.py", line 135, in load
    parser.read(user)
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1063, in _read
    lineno)
configparser.DuplicateSectionError: While reading from '/home/isso/isso.conf' [line 48]: section 'moderation' already exists

**Comment by jelmer** [comment]
Do you perhaps have a duplicate 'moderation' section in your configuration file, per the error message on the last line?
