### ISSUE TITLE
405 Method Not Allowed on Admin Interface

### ISSUE THREAD

**Issue by OmisNomis** [posativ/isso#546]
Version: `isso 0.12.2`

Config:
```
[general]
dbpath = /opt/isso/comments.db
host = https://mywebsite.co.uk/

[server]
listen = http://localhost:8001/

[admin]
enabled = true
password = omitted
```

Navigating to `/isso/admin` works fine:

![image](https://user-images.githubusercontent.com/14848394/55009413-6788e380-4fda-11e9-9792-42d0987f9e64.png)

Entering the password returns a 405 error:

![image](https://user-images.githubusercontent.com/14848394/55009459-796a8680-4fda-11e9-9979-3989587512d3.png)

**Comment by OmisNomis** [comment]
Looking at the Dev console it's making a GET request to `/login` for some reason

```
GET https://codetips.co.uk/isso/login 405 (METHOD NOT ALLOWED)
```

**Comment by OmisNomis** [comment]
This wasn't an Isso problem. Looking at this in a bit more detail - because I was using an endpoint (`/isso`) instead of a subdomain (`comments.codetips.co.uk`) my NGINX configuration was diverting the traffic from HTTP - HTTPS and providing a 301 redirect in the process. 

I moved the call to the subdomain and it worked fine.

Is there an option to make Isso work under HTTPS?

**Comment by MrCappuccino** [comment]
I am having the same issue, however I'm hosting my blog on netlify, but isso on my VPS with Nginx, is there a way to solve this issue? I'm also getting redirected to myvps.ml/isso/login with:
```
Method Not Allowed

The method is not allowed for the requested URL.
```

**Comment by OmisNomis** [comment]
If you're getting redirected, you'll be calling the endpoint with a GET request, which isn't allowed. 

Check your NGINX config, somewhere you're redirecting. Perhaps from HTTP to HTTPS? 

Look at my comment above

**Comment by MrCappuccino** [comment]
> If you're getting redirected, you'll be calling the endpoint with a GET request, which isn't allowed.
> 
> Check your NGINX config, somewhere you're redirecting. Perhaps from HTTP to HTTPS?
> 
> Look at my comment above

Yes, I am redirecting from 80 to 443, http to https, should I just remove the port 80 directive? I'm not quite sure what I am supposed to do.

**Comment by OmisNomis** [comment]
When you do a 301 redirect it changes the request to a GET, which is not a supported method on /login. 

As far as I know isso doesn't support HTTPS, so you need to let the endpoint be hit by HTTP without redirecting. 

I did this using a subdomain rather than a new endpoint.

**Comment by MrCappuccino** [comment]
I removed the redirect and now it seems to be working... That's a shame that it's only over http.

**Comment by heavyimage** [comment]
Agreed with @NullSense!  Any more movement on this since then?

**Comment by heavyimage** [comment]
Wait!  this seems to be what the `public-endpoint` directive is for; setting public-endpoint to https://example.tld seems to fix the issue :-)
