### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by OmisNomis** [posativ/isso#547]
I keep getting CORS errors which are preventing me from adding comments to my website...

Version: `isso 0.12.2`

Config:

```
[general]
dbpath = /opt/isso/comments.db
host =  https://codetips.co.uk/

[server]
listen = http://localhost:8001/
```

errors in console:

```
Access to XMLHttpRequest at 'https://codetips.co.uk/isso/count' from origin 'https://www.codetips.co.uk' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://codetips.co.uk' that is not equal to the supplied origin.
```

```
Access to XMLHttpRequest at 'https://codetips.co.uk/isso/?uri=%2Fwhat-is-syntax%2F&nested_limit=5' from origin 'https://www.codetips.co.uk' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://codetips.co.uk' that is not equal to the supplied origin.
```

**Comment by derdritte** [comment]
Hi there!

I do not have a huge amount of experience with this, but I believe this is because you are trying to access 'https://codetips.co.uk/isso/count' from the site 'https://www.codetips.co.uk'. This is a common issue as CORS is supposed to protect you from resources being loaded from sites you did not authorize.
There is a bit of specific documentation for isso for this:
https://posativ.org/isso/docs/configuration/server/#environment-variables
In your case I would assume you would want to add your domain both with and without the 'www'.
Hope that helps.

**Comment by OmisNomis** [comment]
I thought I'd tried that, but I'll happily add them again.

Weirdly the CORS issue went away about 20 minutes after posting this issue, without me doing anything.

-------- Original message --------

**Comment by OmisNomis** [comment]
@derdritte I looked at this again this morning and you're absolutely right. It didn't just "go away" after 20 minutes yesterday, I just stopped using the `www.` prefix without realising. 

I changed my config to have the following domains whitelisted:

```
host =
    https://codetips.co.uk/
    https://www.codetips.co.uk/
    https://codetips.co.uk
    https://www.codetips.co.uk
    http://codetips.co.uk/
    http://www.codetips.co.uk/
    http://codetips.co.uk
    http://www.codetips.co.uk
```

Which didn't work, so I set the `ISSO_CORS_ORIGIN` environment variable in my systemd file:

```
[Service]
User=ubuntu
Environment="ISSO_SETTINGS=/opt/isso/isso.conf"
Environment="ISSO_CORS_ORIGIN=*codetips.co.uk"
ExecStart=/usr/local/bin/isso -c $ISSO_SETTINGS run
```

But the site is still getting CORS errors when using the `www.` prefix. 

Any ideas?

**Comment by OmisNomis** [comment]
OK, this was my own fault. I'd previously added a workaround to my NGINX config from [here](https://github.com/posativ/isso/issues/347) and I was specifying the `Access-Control-Allow-Origin` header as below. 

I tried adding another header, with `www.`, but then I got more errors because I had multiple headers. Decided to try commenting it all out and trying with the ISSO configuration, and now it works a charm.


```
       if ($request_method = 'OPTIONS') {
         add_header 'Access-Control-Allow-Origin' 'https://codetips.co.uk';
         add_header 'Access-Control-Allow-Methods' 'HEAD, GET, POST, PUT, DELETE';
         add_header 'Access-Control-Allow-Credentials' 'true';
         add_header 'Access-Control-Allow-Headers' 'Origin, Referer, Content-Type';

            # Tell client that this pre-flight info is valid for 20 days

          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
       # }
```

**Comment by derdritte** [comment]
Okay, if you are satisfied with this not being an isso-related bug, you can go ahead and close this issue!

**Comment by mdehghani65** [comment]
In may case I forgot to add different variations of my site domains and subdomains to the host section of isso.conf. (no need to manipulate cors settings).
