### ISSUE TITLE
translation to Portuguese

### ISSUE THREAD

**Issue by janiosarmento** [posativ/isso#548]
Hello,

I'm new to Isso and just created a language JSON for Portuguese (`pt.js`). If I publish it in a gist, would some developer make use of it for a future release?

**Comment by blatinier** [comment]
Hello @janiosarmento 
If you publish it here we could include it in the project.
Even better if you know to do it you could fork this repo, commit your translations and create a pull request. :+1:

**Comment by janiosarmento** [comment]
[https://gist.github.com/janiosarmento/7eabb68542ad45aa352323a66e53592d](Here is the gist)

Unfortunately, I am not GitHub savvy, and right now I'd rather have my contribution added by someone else. :-)

Also, I installed Isso using `apt-get`. I added `pt.js` and edited `isso/js/app/i18n.js` accordingly (to register my script). But my instances keep appearing in English. What am I missing?

**Comment by blatinier** [comment]
You might need to go to the root of the project and launch `make js` to compile js and include your trad
