### ISSUE TITLE
Reply comment Error

### ISSUE THREAD

**Issue by mizbanpaytakht** [posativ/isso#554]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>edit time frame is still open</p>

**Comment by jelmer** [comment]
Please provide some more context - are you seeing this error in the isso logs as well? Are you running isso behind a reverse proxy?

**Comment by Lucas-C** [comment]
Could be related to https://github.com/posativ/isso/issues/224

**Comment by ix5** [comment]
Invalid, not enough info.
