### ISSUE TITLE
List the latest comments (no matter the URI)

### ISSUE THREAD

**Issue by facundobatista** [posativ/isso#556]
I have a blog and I'm using Isso (thanks for this software, is great!!).

I want to implement a section in my blog that should show the latest 10 comments I got in the whole blog, with a link to the original post).

For that, I'd need to list all the comments, not filtering by a specific URI. Of course, not *all* the comments, the latest N.

Is there a current way of doing this?

If not, I'd propose to extend the API, add a new endpoint "/latest/N" where the N is limit (it's mandatory! it doesn't make sense to get *everything*). 

I would work on adding this new endpoint, but I'd love to get some feedback about this proposal, ideas, etc.

Thanks!!

**Comment by jelmer** [comment]
FWIW That seems like a reasonable feature to have to me.

**Comment by facundobatista** [comment]
A different API design could be to support current `/` but not making the `uri` mandatory (however, in that case `limit` would be).

So, it would be something like: `https://commentserver/?limit=10`.

What do you think about this one?

**Comment by jelmer** [comment]
I think you should add a separate endpoint, so perhaps something like:

     /all?limit=10

rather than adding it to the root.

**Comment by facundobatista** [comment]
For a separate endpoint, what do you think about `/latest`? It transmits the idea of time sorting, which is a key feature of this.

**Comment by jelmer** [comment]
/latest seems like a reasonable name for the endpoint.

**Comment by Konzertheld** [comment]
I would like to see this feature, too. It could propably also be used for a feed of all comments (or at least parts of its code). No hard opinion on the name of the endpoint but I agree it should not be done by calling the existing endpoint with / as the URI, because / does not actually have any comments.

**Comment by fluffy-critter** [comment]
If this feature gets added, please make it opt-in. I'm using Isso for the comments on my website which includes private posts (which have hard-to-guess URIs) and I don't want just any random person to be able to retrieve the list of all comments on my site.

**Comment by facundobatista** [comment]
Proposed this to fulfill this issue: #610
