### ISSUE TITLE
Feature request: Add config option to ignore self-signed certificates

### ISSUE THREAD

**Issue by Konzertheld** [posativ/isso#560]
Isso currently can't connect to a website if it has an invalid / self-signed certificate. Some people might want to ignore that. I was one of them as I tried to test SSL issues for #558 locally.

The relevant line is here: https://github.com/posativ/isso/blob/master/isso/utils/http.py#L44

A context can be passed to ignore certificates like this
```
import ssl as ssls

...

self.con = http(host, port, timeout=self.timeout, context=ssls._create_unverified_context())
```

Note that I used `as ssls` because there is already a local variable called `ssl`.

**Comment by Enteee** [comment]
A similar option would also be handy on when connecting to a mail server with invalid certificate.

**Comment by ix5** [comment]
Wouldn't a workaround for that be to import your self-signed certs into your system cert store?

I'm afraid what you're asking for is a very specific request which would further complicate Isso's myriad of config options.

**Comment by ix5** [comment]
Accepting self-signed certs _not_ inside the system/user keystore would be implemented in one of two ways, neither of which is pretty:
1. Not validating certs altogether
2. Keeping a cert fingerprint (maybe cert SHA1 or something similar) inside Isso's config

This is not something that makes sense to have and is incredibly error-prone.

If you want to improve the documentation and show ways to import self-signed certs into the system store, here are some hints:
- `$ sudo trust anchor --store ~/.mitmproxy/mitmproxy-ca-cert.cer`
- [mitmproxy docs: Certiticates](https://docs.mitmproxy.org/stable/concepts-certificates/)
