### ISSUE TITLE
Links and Threads Not Working

### ISSUE THREAD

**Issue by joshcsullivan** [posativ/isso#566]
Hello,

I've had Isso running for a few months now and love it, but I have one issue that I cannot seem to solve myself. My blog, https://blog.joshsullivan.io/ is hosted on https://blot.im/ a SSG, so I do not host the blog on a server myself and therefore Isso cannot be served as blog.joshsullivan.io/isso/. I instead created an Isso instance on a VPS at isso.joshsullivan.io but now links in Isso Admin point to https://isso.joshsullivan.io/correct-ending-of-url and the threads in Isso admin don't work at all, I assume because it is trying to find the comment path at the isso.joshsullivan.io address instead of the blog.joshsullivan.io.

Is there any way to correct this so threads and links in the admin panel work correctly?

I've set the hosts to

```
https://blog.joshsullivan.io/
http://blog.joshsullivan.io/
https://isso.joshsullivan.io/
http://isso.joshsullivan.io/
```

Cheers,
Josh

**Comment by ix5** [comment]
At the moment, isso only stores *relative* URLs for threads - it is not multi-site-aware.

The client only sends the `pathname`, see [api.js](https://github.com/posativ/isso/blob/78997f491044b7d694ac7170edc32030544095b7/isso/js/app/api.js#L6).

If you want to change that behaviour, you will have to account for people already using isso:
Either, make a migration script for existing entries in the database to use the full URL, or write a clause for both cases, something like this (pseudo-code):

client:
```
host = window.location.host;
pathname = window.location.pathname;
```

Example thread for this purpose: `blog.joshsullivan.io/my-thread`
Hosts in config: `https://blog.joshsullivan.io/`, `http://blog.joshsullivan.io/`

server:
```
def sanitize_host(hostname):
    return hostname.lstrip("http://").lstrip("https://").rstrip("[\w]/")

hosts = list(set(map(sanitize_host, hosts)))

thread_host = get_from_request_params("host")
thread_uri = get_from_request_params("pathname")

if get_from_db(thread=thread_uri, host=thread_host):
    return_comments_and_stuff

# Legacy
for host in hosts:
    if get_from_db(thread=thread_uri, host=host):
        return_comments_and_stuff()
        break
```

**Comment by ix5** [comment]
This is the workaround I use for now
https://github.com/ix5/isso/commit/bc6f0a0cf24f3ef038ee5a14b837d76e065b677a

With a monkey-patched `embed.min.js`: 
```
i=function(){return window.location.host+window.location.pathname}
[...]
o.fetch(l.getAttribute("data-isso-id")||location.host+location.pathname
```

**Comment by EchedeyLR** [comment]
Did you try to submit a pull request about this?

**Comment by ix5** [comment]
The way I described in this thread is not suitable for prime time.

**Comment by EchedeyLR** [comment]
Reference: https://github.com/posativ/isso/pull/711#issuecomment-788161527

Let's continue the discussion here better.

I am with the same issue as @joshcsullivan but in this case is related to issue that would have the main site if I embed the Isso as a sub-path with entries and other urls.

**Comment by ix5** [comment]
Isso should prepend the value of the (first) `host` from the `[general]` config section to `comment.uri`.

https://github.com/posativ/isso/blob/5ad5a08a7369e11363fb779360eba81b9f25c892/isso/templates/admin.html#L81

**Comment by EchedeyLR** [comment]
I have public-endpoint set to comments.masfloss.net and host to masfloss.net. If I don't set public-endpoint, I have an issue with CORS rendering the masfloss.net site.

In the admin page I see the reference to every blog entry in masfloss.net as comments.masfloss.net/whatever-entry instead of masfloss.net/whatever-entry

**Comment by ix5** [comment]
I'm sorry, I wasn't being clear when I said "isso should"; I meant that we should change isso to act that way.

You said you "[..] don't know how to solve this issue since [you] don't understand the structure of Isso at all."

The two files I posted should give you a good starting point to fix this issue:
- Look for the `conf.general.host` value
- Pass it to the template
- Prepend `{{ host }}` to `{{comment.uri}}`

**Comment by ix5** [comment]
Closing as duplicate as this is very similar to #647 
Please continue discussions there
