### ISSUE TITLE
Admin comment edits strips new lines

### ISSUE THREAD

**Issue by skylord123** [posativ/isso#570]
When I edit comments from the admin UI it removes all newlines that were in the comment before I modified it. It's strange because you will save it and it will show the newlines but once you refresh it will show the same comment with them removed. 

Admin editor should match the same functionality as the client side one.

As a work-around you have to convert all newlines to `<br />` and it will work then. This is real annoying.

**Comment by ix5** [comment]
As a crutch, you could wrap the area with `<pre>` tags and strip them before submitting.
But bringing the client-side editor into the admin area would be nicer.

**Comment by ix5** [comment]
Do give https://github.com/posativ/isso/pull/604 a try.

**Comment by hamoid** [comment]
Here an example of how a comment looks in admin. All line breaks are gone in the admin, but not in the comment shown publicly. If I edit and save in the admin, the one-lineness is saved :(

![2020-04-23-123246_1120x201_scrot](https://user-images.githubusercontent.com/108264/80089817-c8c51280-855e-11ea-878d-7d3fa5df58bf.png)

So there are two aspects: one is how comments are shown in the admin list, and the other is how it is shown in the admin editor (and later saved).

**Comment by ix5** [comment]
@skylord123 fixed by #604, would you mind closing this?
