### ISSUE TITLE
[API] Allow uploading custom avatar

### ISSUE THREAD

**Issue by mardy** [posativ/isso#572]
Hi there!
  I'm working on implementing [webmention](https://www.w3.org/TR/webmention/) support in my isso-powered blog: once a webmention has been submitted, parsed and accepted, the webmention engine would use the `/new` API endpoint to submit the webmention as an isso comment.

Sometimes after parsing the webmention I will also get a URL for the photo or avatar of the author, and it would be nice if I could use that instead of the identicon. So, to get to the point: what do you think about the possibility of adding an optional `avatar_url` parameter to the `/new` endpoint, where the caller could specify an URL for the avatar?

If you don't object, I'm willing to invest some time and hopefully provide a patch.

**Comment by fluffy-critter** [comment]
One way to possibly hack it in would be to abuse the email field to provide the h-card's `u-photo` URL in some way and then register its md5sum with your own local media endpoint (which would either download or forward as appropriate).

If you just want an easy way of doing webmention-only comments on your blog, you could use webmention.io as your endpoint and one of the several Javascript embeds to use that instead. You wouldn't get threading but I'm not sure how threading would even work in a webmention context anyway (maybe people doing a mention of the individual comment URL?).

**Comment by mardy** [comment]
Thanks @fluffy-critter for your suggestions! I would really like to have my own storage for webmentions, and I'm already at a good point with [my homebrew solution](https://gitlab.com/mardy/bussator), in that I can now see webmentions being reported as isso comments, so I'm quite fond of the idea of seeing the poster's avatar in isso :-)

You first suggestion is more interesting, but then I'd lose the e-mail field. It's not a big issue, but if I can avoid it, it's better :-)

**Comment by fluffy-critter** [comment]
Oh, that endpoint looks pretty nice! You can also self-host a webmention.io instance (source is at https://github.com/aaronpk/webmention.io) but with your own endpoint it shouldn't be that difficult to express a similar embedding API that could be used by webmention.js things.

If you do want to keep the email field then it probably wouldn't be that hard to add an avatar-url column to the database.

**Comment by ix5** [comment]
Seems this might better be implemented in some kind of the aforementioned activitypub/webmention format, externally.

Allowing file uploads seems kind of out of scope for isso, IMO. Closing - feel free to ping if you feel this is still a viable issue.
