### ISSUE TITLE
[Feature Request] integration with telegram instead of emails.

### ISSUE THREAD

**Issue by thepenguinthatwants** [posativ/isso#574]
I've always wanted this to work without the needs to use emails but using chat systems.

**Comment by hamoid** [comment]
By using the API from https://github.com/42wim/matterbridge you could integrate to most chat systems. matterbridge is a single binary written in go. You need a configuration file to talk to a chat.

Broadcasting to all configured chat systems is just a simple http POST request:
https://github.com/42wim/matterbridge/wiki/Api#send-message-post-apimessage

**Comment by ix5** [comment]
This should be taken care of by either webhooks (might be merged soon) or by an external program such [isso-telegram-notifier](https://github.com/mskian/isso-telegram-notifier) as mentioned in https://github.com/posativ/isso/pull/724#issuecomment-939299481
