### ISSUE TITLE
comments do not load : buttons provide no action. 

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [posativ/isso#580]
Thanks for isso. I do not succeed to load comments on page. Here is my isso.conf: (in /home/isso/):

[general]
dbpath = /home/isso/comments.db
host =
      https://vidal-rosset.net
      https://www.vidal-rosset.net   
max-age = 15m
notify = smtp
log-file = /home/isso/isso.log

[moderation]
enabled = false

[server]
listen = http://localhost:8080
reload = off
profile = off
[guard]
enabled = true
ratelimit = 2
direct-reply = 3
reply-to-self = false
require-author = false
require-email = false
[smtp]
username = educasup.philo@gmail.com
password = ********
host = smtp.gmail.com
port = 587
security = starttls
to = joseph.vidal.rosset@gmail.com
from = educasup.philo@gmail.com

isso is correctly running: 
● isso.service - lightweight Disqus alternative
   Loaded: loaded (/etc/systemd/system/isso.service; enabled; vendor preset: ena
   Active: active (running) since Sat 2019-11-02 14:58:55 CET; 13min ago
 Main PID: 334 (isso)
    Tasks: 1 (limit: 4696)
   Memory: 41.5M
   CGroup: /system.slice/isso.service
           └─334 /usr/bin/python3 /home/isso/.local/bin/isso -c /etc/isso.conf r

Nov 02 14:58:55 sd-118693 systemd[1]: Started lightweight Disqus alternative.

cat /home/isso/isso.log
connected to SMTP server
connected to https://vidal-rosset.net

In my html page here: https://www.vidal-rosset.net/Anselm's_Argument_in_First_Order_Logic.html  the code is this one:

<script data-isso="/vidal-rosset.net/"
        data-isso-id="thread-id"
        data-isso-lang="en"
        src="https://www.vidal-rosset.net/js/embed.min.js"></script>
<section id="isso-thread" data-title="Foo!" data-isso-id="/vidal-rosset.net/"></section>

There is something wrong, but I do not succeed to solve the problem. Your help would be very welcome. 

Best wishes, 

Jo.

**Comment by lmburns** [comment]
Did you ever figure this out?

**Comment by ix5** [comment]
Judging by the fact that [vidal-rosset.net](https://vidal-rosset.net/) seems to have a functioning commenting system based ostensibly on Isso as of 2022-02-06, I'd consider this issue resolved.
