### ISSUE TITLE
support for reviews with star ratings

### ISSUE THREAD

**Issue by core-code** [posativ/isso#582]
this is not a bug report but a feature request. we'd be interested in the option for users to leave star ratings with their comment, e.g. as  you can do on amazon where you also rate the product with your comment.

here are some examples how your 'competitors' implement this:
https://widgetpack.com/review-system
https://blog.disqus.com/introducing-star-ratings

**Comment by ix5** [comment]
Very similar to https://github.com/posativ/isso/issues/286
