### ISSUE TITLE
Install Isso on GCP/GAE

### ISSUE THREAD

**Issue by zippy84** [posativ/isso#583]
Is it possible to install Isso on Google Cloud Platform/Google App Engine?

**Comment by ix5** [comment]
It would be possible to install Isso on any given service if the [requirements](https://posativ.org/isso/docs/install/#install-from-pypi) are met.

It seems someone has managed to get it running on a static website using GAE as a backend, see https://github.com/posativ/isso/issues/451 and maybe ask them for further help.

Closing as duplicate.
