### ISSUE TITLE
When Isso starts, log the path of the database and of the config file

### ISSUE THREAD

**Issue by jwatt** [posativ/isso#585]
I initially made some mistakes when using Isso and it was harder to debug than it might have been. Can I suggest that when Isso starts it outputs log messages for:

 * either "No configuration file specified", or else "Using configuration file </full/path.cfg>"
 * "The configuration file </full/path.cfg> does not exist" rather than silently ignoring if the specified configuration file doesn't exist (preferably also abort after logging this error message)
 * "Using database at </full/path.db>"

**Comment by ix5** [comment]
@jwatt @jefft would you like to tackle this?

**Comment by ix5** [comment]
Related: https://github.com/posativ/isso/issues/673 (on the client side)

**Comment by ix5** [comment]
Tracked in #854
