### ISSUE TITLE
`cgi.parse` is depricated and removed in Python 3.8

### ISSUE THREAD

**Issue by shimmy1996** [posativ/isso#599]
[`cgi.parse`](https://docs.python.org/3.7/library/cgi.html#cgi.escape) is deprecated since Python version 3.2, and is removed in version 3.8. 

https://github.com/posativ/isso/blob/2e8cb81179209a6921f58f13c4d5aa002e5a1fb6/isso/views/comments.py#L266

The suggested replacement is [`html.escape`](https://docs.python.org/3.8/library/html.html#html.escape), and the aforementioned line can be modified to work on version 3.8 and other currently supported versions (2.7 and post 3.3) without change in functionality like so
```python
                if hasattr(cgi, "escape"):
                    data[field] = cgi.escape(data[field])
                else:
                    data[field] = html.escape(data[field], quote=False)
```

Happy to make a pull request if such a change is desired.

**Comment by jelmer** [comment]
A pull request would be great.

On 9 December 2019 23:30:51 GMT, Shimmy Xu <notifications@github.com> wrote:
>[`cgi.parse`](https://docs.python.org/3.7/library/cgi.html#cgi.escape)
>is deprecated since Python version 3.2, and is removed in version 3.8. 
>
>https://github.com/posativ/isso/blob/2e8cb81179209a6921f58f13c4d5aa002e5a1fb6/isso/views/comments.py#L266
>
>The suggested replacement is
>[`html.escape`](https://docs.python.org/3.8/library/html.html#html.escape),
>and the aforementioned line can be modified to work on version 3.8 and
>other currently supported versions (2.7 and post 3.3) without change in
>functionality like so
>```python
>                if hasattr(cgi, "escape"):
>                    data[field] = cgi.escape(data[field])
>                else:
>                    data[field] = html.escape(data[field], quote=False)
>```
>
>Happy to make a pull request if such a change is desired.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/posativ/isso/issues/599

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
