### ISSUE TITLE
Ngnix server config with cloudflare https

### ISSUE THREAD

**Issue by lunawen** [posativ/isso#601]
Hi,
I have a ubuntu 18.04 server running on DigitalOcean, and I have a static blog using Hugo as the generator.
I really want to embed isso into my blog and let people comment on my posts.
I have followed the steps from [this tutorial](https://therandombits.com/2018/12/how-to-add-isso-comments-to-your-site/) , and since I am using Ngnix as the webserver, I followed [the other tutorial](https://angristan.xyz/add-comments-to-your-blog-with-isso/) to config isso.
But I haven't added the https part in config because I'm not using LetsEncrypt for https, I use Cloudflare to enable https for my domain.

Here's my config:

```
server {
        listen 80;
        listen [::]:80;
        server_name forum.lunawen.com
        return 301 https://$server_name$request_uri;
        location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://localhost:8080;
        }
        access_log  /dev/isso_access.log;
        error_log /dev/isso_error.log;
}
```

And here is the sample from the tutorial:
![image](https://user-images.githubusercontent.com/34984218/70903672-7a08e880-2053-11ea-9deb-c94955c82d02.png)

I'm getting the error 400 Bad Request when try to access the forum site.
![image](https://user-images.githubusercontent.com/34984218/70903714-9016a900-2053-11ea-8f4f-d09526e2b46f.png)

And help would be appreciated. Thanks!

**Comment by lunawen** [comment]
Update:
I realized that I need to use domain/admin to access the admin page..
And I can see isso on my post page, but I tried to submit a comment, it doesn't do anything after the button press.
I have set the admin enabled = true in the config file, but it seems still not working.
![image](https://user-images.githubusercontent.com/34984218/70906899-9577f180-205b-11ea-9c8c-79dfc1d0e028.png)

**Comment by angristan** [comment]
Hi!

The missing URI query is normal, there is nothing on `/`.

For your second error I think you're missing the `public-endpoint` param in `[server]`. 

Hope it helps.

**Comment by ix5** [comment]
@lunawen can you close this issue?
