### ISSUE TITLE
isso comments visible to bots, SEO

### ISSUE THREAD

**Issue by albertbn** [posativ/isso#602]
hi, 

this is a question, not an issue

are isso comments visible to bots?

the question relates to SEO obviously, I need the comments to be indexed by search engine bots,

in the isso main page demo (https://posativ.org/isso/) they are not in the source code

thanks in advance

**Comment by jelmer** [comment]
That depends on the bot and whether it evaluates JavaScript. There's nothing in isso that intentionally tries to hide comments from bots.

**Comment by albertbn** [comment]
bots don't index javascript really - it's a myth 

I still curse myself for doing my site with a js framework several years ago. had to to a 'bot version' especially, ending up with maintaining 2 versions for 1 thing

but could I just fetch the comments content from the sqllite db and show them to bots?
