### ISSUE TITLE
Installation on mutualised server

### ISSUE THREAD

**Issue by waldo2188** [posativ/isso#608]
Hi! 

Just a little question. 
How to install isso on a server who I can only drop file via an FTP Client?
It’s a simple mutualised server with apache, without ssh access.

**Comment by jelmer** [comment]
You'll need to be able to start isso somehow; if not through SSH then through some other means. FTP alone is not sufficient.

On 7 January 2020 15:08:27 GMT, Waldo <notifications@github.com> wrote:
>Hi! >
>>
>Just a little question. >
>How to install isso on a server who I can only drop file via an FTP
>Client?>
>It’s a simple mutualised server with apache, without ssh access.>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/posativ/isso/issues/608

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
