### ISSUE TITLE
0.12.2 version in PyPI is broken

### ISSUE THREAD

**Issue by facundobatista** [posativ/isso#617]
If you go now and do `pip install isso`, it's broken as it ends up installing `werkzeug 1.0.0` which has deprecated old imports.

Installing isso like `pip install git+https://github.com/posativ/isso.git` works just fine.

**Comment by NikolaiT** [comment]
yes, same issue here. Please fix the documentation ASAP. Otherwise users will be frustrated and will not be using this excellent software.

**Comment by notflip** [comment]
> If you go now and do `pip install isso`, it's broken as it ends up installing `werkzeug 1.0.0` which has deprecated old imports.
> 
> Installing isso like `pip install git+https://github.com/posativ/isso.git` works just fine.

Thanks, I tried your method but when I run the `isso` in the commandline after I get the error
`-su: /usr/bin/isso: No such file or directory` Any idea if I'm forgetting something?

**Comment by jelmer** [comment]
Unfortunately, building the javascript doesn't work for me anymore - so I can't do a release until that's fixed.

(i.e. try running "make init all")

**Comment by notflip** [comment]
@NikolaiT @facundobatista I'm getting  `Command 'isso' not found` after trying using 
`pip install git+https://github.com/posativ/isso.git`

**Comment by zpoley** [comment]
I was also just getting started with isso and ran into problems with master/0.12.2 trying to build the Docker image.

I was able to get isso working in Docker/compose by checking out the 0.12.1 tag, and locking workzeug==0.9.0 in setup.py, in case it helps anyone else.

**Comment by ReyNow** [comment]
I just uninstalled Werkzeug 1.0 and installed the previous version. Afterwards it worked.

**Comment by facundobatista** [comment]
> > If you go now and do `pip install isso`, it's broken as it ends up installing `werkzeug 1.0.0` which has deprecated old imports.
> > Installing isso like `pip install git+https://github.com/posativ/isso.git` works just fine.
> 
> Thanks, I tried your method but when I run the `isso` in the commandline after I get the error
> `-su: /usr/bin/isso: No such file or directory` Any idea if I'm forgetting something?

I think you're not executing the one in the virtualenv. Or how did you install it? I do not do `sudo pip install` ever, too mess in the system...

**Comment by facundobatista** [comment]
It looks the werkzeug incompatibility was fixed in master, however 0.12.2 is still the latest in PyPI. 

When a new version will be released? Thanks for this great software!!

**Comment by JimCircadian** [comment]
Not sure how things are going with this but initially werkzeug installed at 1.0.1 and breaks isso import. Excuse the terminal dump. This is an ansible built install to begin with so the dependencies have been sourced from pypi (I'm writing an isso role at the mo, very keen to give it a whirl!) 

```
(isso) [root@staging-vps conf.d]# python
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import isso
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/opt/wsgi/.virtualenvs/isso/lib/python3.6/site-packages/isso/__init__.py", line 60, in <module>
    from werkzeug.wsgi import SharedDataMiddleware
ImportError: cannot import name 'SharedDataMiddleware'
>>> 
(isso) [root@staging-vps conf.d]# pip freeze
bleach==3.2.1
cffi==1.14.3
html5lib==1.1
isso==0.12.2
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
misaka==2.1.1
packaging==20.4
pycparser==2.20
pyparsing==2.4.7
six==1.15.0
webencodings==0.5.1
Werkzeug==1.0.1
(isso) [root@staging-vps conf.d]# pip install Werkzeug==0.16.1
Collecting Werkzeug==0.16.1
  Downloading Werkzeug-0.16.1-py2.py3-none-any.whl (327 kB)
     |████████████████████████████████| 327 kB 1.5 MB/s 
Installing collected packages: Werkzeug
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 1.0.1
    Uninstalling Werkzeug-1.0.1:
      Successfully uninstalled Werkzeug-1.0.1
Successfully installed Werkzeug-0.16.1
(isso) [root@staging-vps conf.d]# python
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import isso
>>> 
```

**Comment by jelmer** [comment]
@JimCircadian did you install isso from Git rather than release? Because there's no release out yet that supports werkzeug 1.0 due to comment https://github.com/posativ/isso/issues/617#issuecomment-590018453

**Comment by JimCircadian** [comment]
@jelmer I did it from release rather than git, unfortunately it pulled whatever version of werkzeug was available as a dependency from PyPI, so anyone trying to use this from PyPI will run into the same issue! Apologies if that came across as noise, I just wasn't sure if this issue was still being looked into. :-)

**Comment by jelmer** [comment]
The new version of isso on pypi should address this.
