### ISSUE TITLE
Polish language doesn't work

### ISSUE THREAD

**Issue by pawo1** [posativ/isso#619]
Isso works with data-isso-lang set for "en", "ru", "cs" but when I set "pl" it shows english description

**Comment by jelmer** [comment]
There is a Polish translation file, but "pl" appears to be missing from isso/js/app/i18n.js - patches to add it welcome.

**Comment by pawo1** [comment]
i checked i18n.js and there is pl in catalouge and function, have you any idea what i should change?

**Comment by jelmer** [comment]
ah, yeah - it's there in master, but only added ~recently. See f1dcd17e37bccfe3ec38001ac97ac43b0db54d0f

**Comment by pawo1** [comment]
Yes it's exactly what i have in this file, but still no pl language in isso

**Comment by ix5** [comment]
@pawo1 could you verify this is still current?

I just set my browser "accept" language to `pl` and Isso displays labels in Polish on the latest master branch.

**Comment by pawo1** [comment]
Sorry, I forgot to close this issue. Building source again solved the problem.
