### ISSUE TITLE
Feedback on custom Docker build

### ISSUE THREAD

**Issue by frenchvandal** [posativ/isso#620]
Hello,

I have been using successfully Isso via the well known Wonderfall image.

Lately I have been trying to create my own image using Gunicorn, following the [Deployment](https://posativ.org/isso/docs/extras/deployment/) section of the documentation.

It seems that my image is not parsing my isso.conf, causing CORS issues.

Here is my Dockerfile:

```
FROM alpine:latest

ENV GID=4242 UID=4242

RUN apk upgrade --update \
 && apk add -t build-dependencies \
    python3-dev \
    libffi-dev \
    build-base \
 && apk add \
    python3 \
    sqlite \
    libressl \
    ca-certificates \
 && pip3 install --upgrade pip \
 && pip3 install isso==0.12.2 \
 && pip3 uninstall Werkzeug -y \    #temporary fix
 && pip3 install Werkzeug==0.9 \   #temporary fix
 && pip3 install gunicorn[gevent] \
 && apk del build-dependencies \
 && rm -rf /tmp/* /var/cache/apk/*

VOLUME /db /config

EXPOSE 8080

CMD gunicorn -k gevent -b 0.0.0.0:8080 -w 5 --worker-connections 5000 --worker-tmp-dir /dev/shm --preload isso.run
```
I get this warning in the logs:

```
isso    | 2020-03-08 20:49:43,586 WARNING: unable to connect to your website, Isso will probably not work correctly. Please make sure, Isso can reach your website via HTTP(S).
isso    | [2020-03-08 20:49:43 +0000] [1] [INFO] Starting gunicorn 20.0.4
isso    | [2020-03-08 20:49:43 +0000] [1] [INFO] Listening at: http://127.0.0.1:8080 (1)
isso    | [2020-03-08 20:49:43 +0000] [1] [INFO] Using worker: gevent
isso    | [2020-03-08 20:49:43 +0000] [7] [INFO] Booting worker with pid: 7
isso    | [2020-03-08 20:49:43 +0000] [8] [INFO] Booting worker with pid: 8
isso    | [2020-03-08 20:49:43 +0000] [9] [INFO] Booting worker with pid: 9
isso    | [2020-03-08 20:49:43 +0000] [10] [INFO] Booting worker with pid: 10
isso    | [2020-03-08 20:49:43 +0000] [11] [INFO] Booting worker with pid: 11
```
What am I missing?

Any help is welcome 😃

**Comment by rouja** [comment]
Hi,

I think your container is OK. According to the [documentation](https://posativ.org/isso/docs/configuration/server/#general) :

> If Isso is unable to connect to at least one site, you’ll get a warning during startup and comments are most likely non-functional.

**Comment by frenchvandal** [comment]
I have solved my issue!

`CMD gunicorn -k gevent -b 0.0.0.0:8080 -w 5 --worker-connections 5000 --worker-tmp-dir /dev/shm --preload isso.run
`
This final command alone is not enough. I need the run.sh from the image I have forked:

```
COPY run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh

CMD ["run.sh"]
```

run.sh is:
```
#!/bin/sh
chown -R $UID:$GID /db /config
exec su-exec $UID:$GID /sbin/tini -- isso -c /config/isso.conf run
```
And then in my docker-compose.yml, I added;

`command: gunicorn -k gevent -b 0.0.0.0:8080 -w 5 --worker-connections 5000 --worker-tmp-dir /dev/shm --preload isso.run`

I am not a Docker expert, I do not know if it is optimal, but it works so I keep it like that!
