### ISSUE TITLE
Hide "No Comments Yet" headline

### ISSUE THREAD

**Issue by schiessle** [posativ/isso#623]
is there a way to hide or change the "No Comments Yet" headline and the comments count? I tried the `data-title=""` attribute but it seems to do something different.

**Comment by Fryboyter** [comment]
If you do not need the line at all, you can hide it with CSS. To do this, search for the following entry

```
#isso-thread > h4 {
    color: #555;
    font-weight: bold;
}
```

You then extend it as follows

```
#isso-thread > h4 {
    color: #555;
    font-weight: bold;
    display: none;
}
```

**Comment by blatinier** [comment]
The CSS override is a good solution for that. I close this issue.
