### ISSUE TITLE
Possible to do multiple line comments with Markdown?

### ISSUE THREAD

**Issue by poblabs** [posativ/isso#625]
Hi there, when trying to leave a multiple line comment using the markdown triple backticks doesn't seem to be working. 

```
for
example
```

Is this available in isso?

**Comment by poblabs** [comment]
Looks like if you prepend each line with 4 spaces, it'll do a multi line block code. Would be nice to have the backticks work as well if possible?

**Comment by ix5** [comment]
Markdown parsing depends on the `misaka` package. You can see its options on the [official documentation](https://misaka.61924.nl/).
What I think you want is the `fenced-code` extension, see [API: Extensions](https://misaka.61924.nl/#html-render-flags). You can specify the extensions used [in your `isso.conf`](https://github.com/posativ/isso/blob/master/share/isso.conf#L193).

Now I don't know whether the example conf has the wrong syntax, underlined (`fenced_code`) vs dash (´fenced-code` ). I'll look into that later.

**Comment by stefangehn** [comment]
If isso was built with misaka 1.x then it's `fenced_code` (the Debian 10 package of isso still uses misaka 1.x).
If issa was built with misaka 2.x (i.e. the current version in master or if you installed it via pip) then it's `fenced-code`.

**Comment by ix5** [comment]
Tried to improve the docs regarding that issue, see https://github.com/posativ/isso/pull/684

By default, Isso 0.12.2+ already have fenced-code enabled for you @poblabs.

**Comment by ix5** [comment]
Hi @poblabs, I tried reproducing your issue but I cannot. With `options = [...], fenced-code` and current isso, code blocks delimited by triple backticks render just fine.

**Comment by poblabs** [comment]
Yes that works and has worked since your reply in 2020. Thanks for checking in. 😄

**Comment by ix5** [comment]
Happy to hear that!
