### ISSUE TITLE
How will isso work if my permalinks change?

### ISSUE THREAD

**Issue by randomshinichi** [posativ/isso#628]
Sorry for making an issue out of this, I didn't know where else to ask.

How does isso actually refer to hugo posts? I haven't decided how my permalink structure will look.

**Comment by frenchvandal** [comment]
You can try to adapt the solution described [here](https://angristan.xyz/2020/02/migrate-dated-permalinks-ghost-isso/).

**Comment by ix5** [comment]
@randomshinichi by default, Isso uses the URL it is being loaded from as an identifier.

You could also set `data-isso-id` for each post in hugo, e.g. insert a new field into your front matter of each post and then render it as a value to the isso javascript call.
