### ISSUE TITLE
Code fences/indented blocks not working correctly

### ISSUE THREAD

**Issue by fluffy-critter** [posativ/isso#629]
I'm having an issue where code-fence blocks (` ``` `) are having HTML sanitization applied to them, incorrectly; for example:

    ```c++
    #include <map>
    int main() {
        ...
    }
    ```

renders as:

```
#include
int main() {
    ...
}
```

And the same happens if the block is indented by four characters. It seems that Isso's Markdown processor isn't properly handling code blocks/fences. However, it's only angle brackets which are being processed incorrectly; other Markdown primitives seem to be correctly passed through.

My isso markup configuration is:

```
[markup]
options=strikethrough, autolink, fenced-code, no-intra-emphasis, superscript, highlight, quote, tables
allowed-elements=mark, sup, sub
```

The rest of my website also uses misaka as its Markdown processor and the fenced-code extension is operating correctly there. Both are on misaka version 2.1.1.

**Comment by fluffy-critter** [comment]
Failing test added to `test_html.TestHTML`:

```python
    def test_code_blocks(self):
        convert = html.Markdown(extensions=('fenced-code',))
        examples = [
            ("```c++\nThis is a code-fence. <hello>\n```", "<p><pre><code class=\"c++\">This is a code-fence. &lt;hello&gt;\n</code></pre></p>"),
            ("    This is a four-character indent. &lt;hello&gt;", "<p><pre>This is a four-character indent. &lt;hello&gt;</pre></p>")]

        for (input, expected) in examples:
            self.assertEqual(convert(input), expected)
```

At present, the first test case fails, because the `<hello>` remains unescaped. If I change `html.Unofficial.blockcode` to use `html.escape` on the content, the second test case fails, because the `<hello>` gets double-escaped to `&amp;lt;hello&amp;gt;`.

**Comment by fluffy-critter** [comment]
Wait, I just realized that I had already escaped the `<hello>` in the four-space indent and that should have been double-escaped. Whoops.

**Comment by ix5** [comment]
Fixed by https://github.com/posativ/isso/pull/631

**Comment by fluffy-critter** [comment]
Yep, don't know why the merge didn't automatically close the issue. Oops.
