### ISSUE TITLE
Isso backend accepts comments with non-existent URI

### ISSUE THREAD

**Issue by babakRz63ai** [posativ/isso#630]
You can use `curl` to post a comment for a thread which is not actually there in your website. You only need to mention a `title` field in the JSON. like this:
```
curl -v -d '{"text": "Hello, World!", "author":"anon1", "title":"Crap"}' -H "Content-Type: application/json" "http://localhost:8181/new?uri=%2FNonExisting%2F"
```
This bug is caused by this part of comments.py:

```python
if uri not in self.threads:
                if 'title' not in data:
                    with http.curl('GET', local("origin"), uri) as resp:
                        if resp and resp.status == 200:
                            uri, title = parse.thread(resp.read(), id=uri)
                        else:
                            return NotFound("URI does not exist '%s'" % uri)
                else:
                    title = data['title']

                thread = self.threads.new(uri, title)
                self.signal("comments.new:new-thread", thread)
            else:
                thread = self.threads[uri]
```

As you can see, if there is a 'title' in the post data, then isso won't check the URI and accepts the comment.

**Comment by rouja** [comment]
Hi,
I'm not sure if it's a bug or a feature. Personally I use this for multi language blogs to have the same comments thread for the same article but in different languages with different uris.

**Comment by babakRz63ai** [comment]
It seems more of a bug to me, and I'm going to modify this behaviour in a branch of [my fork](https://github.com/babakRz63ai/isso).

**Comment by fluffy-critter** [comment]
If any change around this goes into mainline Isso, please make it an option; detecting based on HTTP status code of the page will fail on pages which require authorization (error code 401) as well as other things.

Also, if someone wants to post a comment to a thread that doesn't exist and never will be seen except maybe by the site moderator, more power to them?

**Comment by jelmer** [comment]
I'm also not very convinced about the usefulness of checking whether the URL actually exists, other perhaps than perhaps giving the user a more reasonable error rather than letting their comment disappear in the void.

Either way, the logic to only check whether the URL exists if title is set seems wrong to me. Either it should always check, or never check or check if a particular configuration option is set - but I don't see why that behaviour should be conditional upon the presence of the title.
