### ISSUE TITLE
404 Errors JS

### ISSUE THREAD

**Issue by raviolican** [posativ/isso#643]
HI Im getting 404 errors for JavaScript files...

https://raviolican.com/isso/info

{"version": "0.12.3.dev0", "host": "https://raviolican.com/isso", "origin": "https://raviolican.com", "moderation": false}

https://raviolican.com/isso/admin **200**

> ; |||||||||||| general settings ||||||||||||||
> [general]
> ;database location. automatically created if doesn't already exist
> dbpath = comments.db
> 
> ;this will be the 'X-Script-Name' we proxy server requests to [later!]
> name = isso
> 
> ; your website or blog [not the location of Isso]
> host = https://raviolican.com/
> 
> ; logfile. might need to create this first
> 
> 
> ; get notifications by email
> notify = stdout
> 
> ;||||||||||| server section ||||||||||
> [server]
> ;port to listen on. choose a number you like!
> listen = http://localhost:8181/ 
> [admin]
> enabled = true
> password = fummelpummepl
> 
> ;||||||||| smtp section [for notifications] |||||
> [smtp]
> ;these are the details for the 'from' address Isso uses to send notifications
> ;you might want to use a dedicated email account for this
> username = yourusername
> password = yourpassword
> host = smtp.yourmailhost.com
> port = 587
> security = starttls
> 
> ;this is the 'to' address Isso sends notification emails to
> to = you@youremail.com
> 
> ;from address as shown on emails. should correspond to sender account above
> from = "isso comments" <yourusername@yourmailhost.com>
> timeout = 10
> 
> ;|||||| guard –Isso's basic spam protection |||||||
> [guard]

> enabled = ffalse
> ;no. of allowed comments per minute
> ratelimit = 2
> ;no of direct replies allowed
> direct-reply = 3
> ;can people reply to their own comments while edit window still open
> reply-to-self = false
> ;do commenters need to leave a name
> require-author = true
> ;do commenters need to provide an email
> require-email = false
> 
> ;allowed markdown in comments. [uses misaka markdown]
> [markup]
> ;default options allow most 'unharmful' markdown
> options = strikethrough, superscript, autolink
> ;default allowed = a, blockquote, br, code, del, em, h1, h2, h3, h4, h5, h6, hr, ins, li, ol, p, pre, strong, table, tbody, td, th, thead, ul
> ;allowed-elements =
> ;default allowed = align, href
> ;allowed-attributes
> 
> ;creates identicons for users across isso installations
> [hash]
> ;OK to use this salt
> salt = Eech7co8Ohloopo9Ol6baimi
> algorithm = pbkdf2
> 

Nginx:

>     location ~ /isso(.*)$ {
>         proxy_pass http://127.0.0.1:8181$1;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Script-Name /isso;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
>

**Comment by hamoid** [comment]
Which version of isso? I had to get the latest from github (a few days ago) to not get 404s for javascript files.

**Comment by raviolican** [comment]
i pulled it today

**Comment by hamoid** [comment]
Did it work before or is it your first install? Did you build the JavaScript files?

**Comment by raviolican** [comment]
No first installation. How to build the JS files?

**Comment by hamoid** [comment]
Did you follow the steps at https://posativ.org/isso/docs/install/ ? `make js` should do it (after all the other steps ;) )

**Comment by raviolican** [comment]
make this start the c compiler..^^

**Comment by ix5** [comment]
Please close.
