### ISSUE TITLE
Wrong IP adress of comment author in email message

### ISSUE THREAD

**Issue by pawo1** [posativ/isso#645]
Hello,
I saw that IP in email always has "0" as last digit. Which is wrong. For example i chceck true IP and it ends at "99" but in email I get "0". The rest of the numbers are correct (tested with some IP numbers of friends computers). Thats why I think it's problem with isso.

PS I use nginx

**Comment by vincentbernat** [comment]
The IP address is anonymized by removing the last digit to not store personal information. This is not a behavior that you can disable with a configuration setting.

**Comment by pawo1** [comment]
Oh, I See.
Sorry I thought it's bug or something. 

So there are no option to disable comment for somebody who spams or break commenting rules? I ask in theory

**Comment by vincentbernat** [comment]
No option. You can look at the code, search for `anonymize`. Look at https://github.com/posativ/isso/blob/master/isso/utils/__init__.py#L26-L44 to disable that by patching the code.

**Comment by pawo1** [comment]
Okey
Thanks for your time
I think we can close this issue
