### ISSUE TITLE
Ways to donate?

### ISSUE THREAD

**Issue by yixuan** [posativ/isso#648]
I really like Isso and want to support its development. I myself am not familiar with web programming, so do you accept any financial donation?

**Comment by jelmer** [comment]
@posativ

**Comment by posativ** [comment]
Not sure if *I* want donations, the website hosting costs not much and I do not need financial support there. As a collaborator @jelmer do you need something in that direction? Is there a donation platform that the collaborators and/or contributors can use?

**Comment by jelmer** [comment]
Same here. If you have specific features you'd like to see then bountysource may be an option. If you're looking to donate without a specific request then there are a number of other projects that isso is built on top of that are set up to take donations - e.g. werkzeug, jinja2, misaka, sqlite3.

**Comment by yixuan** [comment]
Sounds great. I'll look into those options. Again thanks for your great works. 👍
