### ISSUE TITLE
Better error message when config file isn't readable

### ISSUE THREAD

**Issue by jefft** [posativ/isso#651]
When `isso.conf` isn't readable by the user isso is running as, then on startup we get:
```
ERROR: No website(s) configured, Isso won't work.
```
This is a bit confusing (see #330). It would be nice if isso printed 'cannot read config file' instead.

**Comment by ix5** [comment]
@jefft would you mind creating a PR that addressed this? You should add a suggestion to copy the default `isso.conf` and mention that the `host` field must be configured.

**Comment by ix5** [comment]
Very similar to https://github.com/posativ/isso/issues/585, closing in favour of that PR
