### ISSUE TITLE
Build environment could use some documentation

### ISSUE THREAD

**Issue by fluffy-critter** [posativ/isso#658]
Hi, I'd like to work on some changes for isso but unfortunately the README doesn't provide sufficient information to get started with the build environment. Is there a simple set of instructions about what I need to install so that the Makefile works? I'm not as well-versed in the Javascript ecosystem as in Python, so I'm not quite sure how to get, for example, `make js` to actually work.

Thanks!

**Comment by jefft** [comment]
Agreed, it could.

Doing what the [Dockerfile](https://github.com/posativ/isso/blob/master/Dockerfile) does is a good general rule. The Dockerfile begins with `node:` OS image, i.e. one where `npm` is available. So the first step is to get a [Node binary distribution for your OS](https://github.com/nodesource/distributions/blob/master/README.md). Then follow the Dockerfile commands (`npm install -g ...`).

**Comment by ix5** [comment]
I've tried making the install from source section more clear in https://github.com/posativ/isso/pull/703

**Comment by jelmer** [comment]
Closing this now that #703 has landed.
