### ISSUE TITLE
latest release 0.11.1 but in debian it is 0.12.x??

### ISSUE THREAD

**Issue by damnms** [posativ/isso#662]
https://github.com/posativ/isso/releases lists 0.11.1 as latest release
but

root@server:/etc/isso.d/enabled# dpkg -l | grep isso
ii  isso                            0.12.2-2                     all          lightweight web-based commenting system

???

when i go to the latest releases page and click on "newer releases" i see 12.2 - whats the difference to the other releases? why are they not listed "normal" like all other releases?

**Comment by jelmer** [comment]
See the tags page; I don't know why github insists on having a separate page for releases, but I've created a separate item on the releases page now using the UI.
