### ISSUE TITLE
Dead link to systemd scripts in docs

### ISSUE THREAD

**Issue by pawamoy** [posativ/isso#670]
Namely:

```
systemd (Isso + Gunicorn): https://github.com/jgraichen/debian-isso/blob/master/debian/isso.service
SysVinit (Isso + Gunicorn): https://github.com/jgraichen/debian-isso/blob/master/debian/isso.init
```

These two links result in 404 on GitHub :slightly_smiling_face: 

Do you know a place where we can find a copy of these files?

**Comment by jefft** [comment]
Following that repo's [README](https://github.com/jgraichen/debian-isso/blob/master/README.md), the new debian upstream source is: 
https://salsa.debian.org/jelmer/isso/-/blob/master/debian/isso.service
https://salsa.debian.org/jelmer/isso/-/blob/master/debian/isso.init
