### ISSUE TITLE
Could we hook (or trigger) a javascript function when we click the "Submit" button with docker-versioned isso?

### ISSUE THREAD

**Issue by huskier** [posativ/isso#675]
We want to record who commented one specific page or article. For now, the isso is anonymous for comments. So, we want to hook (or trigger) a javascript function when we click the "Submit" button with docker-versioned isso. In that way, we could save the user who commented the target content.

Thanks.
Youbao

**Comment by ix5** [comment]
You can hook the `submit` function, but you have to re-compile the generated javascript.
https://github.com/posativ/isso/blob/08703d03ace7089f157fbdf5d560209c66d713e1/isso/js/app/isso.js#L83-L114

You would have to fork the isso repo to make your changes though and update your Dockerfile to point to your fork.

**Comment by huskier** [comment]
Thank you ix5.
Could we make this "hook the submit function" an official function?
Thanks.
Youbao

**Comment by ix5** [comment]
You can just add a listener for the submit button in your custom javascript. It makes no sense to bake any of this into isso.
