### ISSUE TITLE
Isso response is very slow

### ISSUE THREAD

**Issue by staeff777** [posativ/isso#676]
I'm using a quite cheap server.. nevertheless the cpu utilization is very low:
![grafik](https://user-images.githubusercontent.com/534957/100144572-435c6480-2e97-11eb-9b6b-e1109617e65a.png)

sadly, querying the comments of a page is extremely slow (total count of comments is less than 10):
![grafik](https://user-images.githubusercontent.com/534957/100144745-84ed0f80-2e97-11eb-9309-08335bff9d4e.png)
(It states a response time of 60s)

Is there something i could test to find the source of this problem? 

Edit:
I tried curl 127.0.0.1:8001/admin and it timed out several times, but then suddenly worked as fast as it should.

**Comment by stefangehn** [comment]
I don't think there is anything isso does that would explain such delays, it's probably a badly overbooked VM host.

**Comment by ix5** [comment]
Isso always responds in under 0.001s for me. Have you tried using the `profile` option to trace the issue?

**Comment by staeff777** [comment]
Thank you very much. I found the issue. The issue came from werkzeug https://werkzeug.palletsprojects.com/en/1.0.x/serving/#troubleshooting . I tried to use the wrong interface.

Sorry for not coming back to close it.
