### ISSUE TITLE
Feature request: Implement inline code with backtick

### ISSUE THREAD

**Issue by eabase** [posativ/isso#677]
It could be really great if it would also support single backtick to highlight a code or command with a fixed width "terminal font" like this:

* `command --with option="123"`

**Comment by vincentbernat** [comment]
This is already the case.

**Comment by eabase** [comment]
@vincentbernat 

> This is already the case.

Oh! Well, that certainly wasn't clear from the README.  
So what other markup options are already implemented?
(And where are they documented?)

**Comment by vincentbernat** [comment]
❦ 17 décembre 2020 12:49 -08, eabase:

>> This is already the case.
>
> Oh! Well, that certainly wasn't clear from the README.  
> So what other markup options are already implemented?
> (And where are they documented?)

The backend is Misaka (using Hoedown) with the following extensions
enabled by default:

 - "strikethrough",
 - "superscript",
 - "autolink", and
 - "fenced-code".

And you can add more in the configuration.

**Comment by ix5** [comment]
This can be closed then.

**Comment by eabase** [comment]
> This can be closed then.

Well it look to me that you still need to install several extensions and use a particular back-end. So that is not clear at all from the README or any related install pages. We need a step-by-step installation instructions.

**Comment by ix5** [comment]
@eabase I've tried to improve the documentation for you. Maybe there should be a concise "What markup can I use by default?" section somewhere in the docs.
