### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by fluffy-critter** [posativ/isso#679]
The `/id` endpoint makes it way too easy for someone to download all comments on a site, even ones on pages which aren't from publicly-known URIs. This is a potential privacy concern for folks using isso in a semi-private context, such as comments on friends-only posts, and this is made much worse by the use of auto-incrementing comment IDs (see the recent Parler privacy fiasco for a perfect example of why this is bad).

It looks like the frontend uses this endpoint for the purpose of rendering a submitted comment, but it seems like this could be better done by the `POST` submission API providing the rendered HTML (which would also help with issue #673), or by requiring the authentication cookie to prevent fetching random messages, or even just requiring the thread's page URI as a safety measure.

It's notable that this endpoint is not documented on the [API docs](https://posativ.org/isso/docs/extras/api/) which implies that it's not intended to be known about, but security through obscurity is no security at all.

So, I have two suggestions, both of which should be implemented:

1. Stop using auto-incrementing comment IDs
2. Don't allow arbitrary retrieval based only on the comment ID

**Comment by ix5** [comment]
1. Is comparatively easy to implement, you will have to change the DB schema (and implement a migration) though to implement UUID-based comment `id`s. The schema is defined in [isso/db/comments.py](https://github.com/posativ/isso/blob/944e4846847abc9b252f9b016158e336ffb77443/isso/db/comments.py#L39).

2. Can be implemented in an easy and a hard way.
  - The easy way would check if the requesting URI matches the thread associated with the comment id.
  - The hard way would be to hide your private post comments behind a password, which would entail isso gaining password functionality. I'd rather avoid that.

In general, isso is gaining complexity rapidly. I think people want it to do way too much - it was intended for "slap some comments on this single blog" and has outgrown its roots a fair bit.

**Comment by fluffy-critter** [comment]
I also don't think isso is gaining complexity, but its design is kind of simplistic in a way that has made it much more difficult to extend in the ways that people want it to be extended. I had adopted it out of expediency in needing to get off of Disqus, but I've run into too many places where its design assumes things that just don't work for my site and I think it's time for me to just design my own embeddable comment system for my particular set of requirements.

Isso's still great for the intended purpose of quickly getting a self-hosted Disqus-like blog comment engine, though!

**Comment by ix5** [comment]
The thread checking is the easiest to implement for now. You will have to add the thread URI to a lot of places though, since the `/id` endpoint is manipulated directly quite often.
Do you want to have a go at it? I could handle the python side if you want.

**Comment by fluffy-critter** [comment]
I'd be much more comfortable working on the python side. But from the javascript side I only saw one place where the `/id` GET path was touched directly, namely in rendering the submitted comment (which would be better served as a payload that comes directly from the comment submission response, at https://github.com/posativ/isso/blob/944e4846847abc9b252f9b016158e336ffb77443/isso/js/app/isso.js#L271). What am I missing?

Note that the `/id` endpoint *name* is used for a bunch of things but it's an overloaded name; it's only the `GET` path that has a privacy problem, as far as I can tell.

**Comment by fluffy-critter** [comment]
Oh wait I see, the `api.view` call isn't even used to render the edited comment, but to get the raw Markdown that was originally submitted. I think that it'd be fine to just protect that with the same auth cookie that is present for the edit submission as well.

**Comment by ix5** [comment]
Another aspect just popped into my head: You're gonna break `order_by=id` by switching to UUIDs.
https://github.com/posativ/isso/blob/944e4846847abc9b252f9b016158e336ffb77443/isso/db/comments.py#L201

Ordering by `id` is used e.g. for the feed, so it'd be better to switch it to `created` or `modified` in the relevant places.

**Comment by fluffy-critter** [comment]
> Another aspect just popped into my head: You're gonna break `order_by=id` by switching to UUIDs.
> 
> https://github.com/posativ/isso/blob/944e4846847abc9b252f9b016158e336ffb77443/isso/db/comments.py#L201
> 
> Ordering by `id` is used e.g. for the feed, so it'd be better to switch it to `created` or `modified` in the relevant places.

Good point. Ordering by `id` is generally useless anyway, since it doesn't really have any bearing on what any site user is going to care about (and in the case of e.g. Disqus imports, the ID is pretty much arbirarily-ordered anyway).

**Comment by stefangehn** [comment]
I had a different idea but didn't try it out in code yet:
- add a secret key to isso config
- generate a hash based on the database id and the secret key
- only work with the generated hash in the API, do not give out db identifiers

To make migrations from one url scheme to another still possible I would calculate the hash on the fly.
It might be that this approach is overkill after reading the previous discussion in here but I wanted to mention it nevertheless.

Regardless of which route is taken in the end, I would also be interested in getting bugfixes into isso (whose development seems to have stalled a bit).

**Comment by ix5** [comment]
> I had a different idea but didn't try it out in code yet:
> 
> - add a secret key to isso config
> - generate [encrypted ids] based on the database id and the secret key [via symetric key algo]
> - only work with the generated encrypted id in the API, do not give out db identifiers
> 
> To make migrations from one url scheme to another still possible I would calculate the hash on the fly.
> It might be that this approach is overkill after reading the previous discussion in here but I wanted to mention it nevertheless.

@fluffy-critter's current solution depends on the thread URLs being un-guessable to guard against scraping.

The general idea is that the comment id is they "key" and the thread uri is the "password". The "key" can always be derived from the password since everyone is able to fetch comments for any URI.

Your encryption of the key will not change that.



BTW, there's also a PR ongoing about [restricting access to a filter matching thread URLs](https://github.com/posativ/isso/pull/632). Not quite the same, but maybe @babakRz63ai would like this direction more. 

---

Another issue with UUIDs: Isso assumes comment `id`s will increase monotonically and returns the `id` of the newly created comment by checking `MAX(comment.id)` per thread in sql:
https://github.com/posativ/isso/blob/944e4846847abc9b252f9b016158e336ffb77443/isso/db/comments.py#L78

**Comment by fluffy-critter** [comment]
So FWIW I actually use a hashing scheme as part of the thread URI generation. Page URIs are decoupled from thread URIs. Obviously the thread URI is visible in the page source for anyone with access to the page but anyone who can see a page can see the thread anyway. Also for the sake of reply notifications I have my site set up to redirect the thread URI back to the page URI (the hashed thread URI includes enough information for the site routing system to determine the page URI from it). 

Signed requests are a pretty good way to do things too, but that feels like overkill for this particular situation.
