### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by Planetlinux-de** [posativ/isso#691]
Hello,

because there has been no reaction from the developers to the last issues such as #678, although some of them have been active on Github recently (for example @jelmer or @blatinier), I would like to ask about the status of the project.

Are the developers still interested in the Isso project? If so, is there anything that interested people can help with, for example to release a new official version after 2 years?

Please do not misunderstand me. My point is not to complain. There are certainly more important things in life than a commentary system. And priorities change (I can say this from my own experience). I'm more concerned with whether you can continue to rely on Isso or whether you'd rather use an alternative like Commento. Or whether it is perhaps conceivable that someone (not me), if the current developers have no desire or time to continue working on Isso, forks Isso. In short, I would just like an official statement on the status of the project. No matter whether this is positive (development continues) or negative (Isso is dead).

Greetings
Fryboyter

**Comment by jelmer** [comment]
FWIW I don't consider Commento an alternative for isso - it's not free software nor self-hosted.

That said, my priorities are elsewhere at the moment and I don't really have time to spend on isso unfortunately.

@posativ has been open to other people chiming in to help with maintenance in the past, and I suspect they would welcome more maintainers. 

I don't think the status of any free software project is boolean - it's certainly less active than it was in the past, but it does what it needs to do so is that a bad thing?

**Comment by Planetlinux-de** [comment]
Hello jelmer,

Thank you very much for your quick feedback.

>FWIW I don't consider Commento an alternative for isso - it's not free software nor self-hosted.

Commento is published under the MIT licence (https://gitlab.com/commento/commento/-/blob/master/LICENSE) and you can also host the system yourself (https://docs.commento.io/installation/self-hosting/) if you wish. But Commento was only the first best example of an alternative I could think of. :-)

>That said, my priorities are elsewhere at the moment and I don't really have time to spend on isso unfortunately.

Which, as noted in my post, is absolutely fine. :-)

>@posativ has been open to other people chiming in to help with maintenance in the past, and I suspect they would welcome more maintainers.

However, they would then need the necessary rights, for example, to integrate PR or to publish new versions. And that should only be possible with his or your help. Which is problematic if no one has time.

>it's certainly less active than it was in the past, but it does what it needs to do so is that a bad thing?

Isso definitely works at the moment. And as a user, I am grateful for that. However, when installing via pip, you have to downgrade the dependency "werkzeug" (#617). 

In my opinion, the problem addressed in #682 should also be solved as quickly as possible. Because if I have understood it correctly, this can limit (or even prevent) the function of Isso.

**Comment by jelmer** [comment]
> > FWIW I don't consider Commento an alternative for isso - it's not free software nor self-hosted.
> 
> Commento is published under the MIT licence (https://gitlab.com/commento/commento/-/blob/master/LICENSE) and you can also host the system yourself (https://docs.commento.io/installation/self-hosting/) if you wish. But Commento was only the first best example of an alternative I could think of. :-)
I stand corrected - I assumed it was proprietary and hosted from a quick glance at its homepage.

> > @posativ has been open to other people chiming in to help with maintenance in the past, and I suspect they would welcome more maintainers.
> 
> However, they would then need the necessary rights, for example, to integrate PR or to publish new versions. And that should only be possible with his or your help. Which is problematic if no one has time.
That does still happen. I do keep an eye on important changes that come in, and do merge requests where I can easily verify that they're correct. Unfortunately the test coverage in isso isn't great and so I err on the side of caution when it e.g. comes to new features.

> > it's certainly less active than it was in the past, but it does what it needs to do so is that a bad thing?
> 
> Isso definitely works at the moment. And as a user, I am grateful for that. However, when installing via pip, you have to downgrade the dependency "werkzeug" (#617).
This is actually fixed in trunk, but unfortunately my JavaScript knowledge is too limited to fix the JavaScript build - and nobody has stepped up to contribute a fix for that. Once the JavaScript build is fixed, we could do a release.

> In my opinion, the problem addressed in #682 should also be solved as quickly as possible. Because if I have understood it correctly, this can limit (or even prevent) the function of Isso.
If there is a fix for this, I'd be happy to merge it.

**Comment by stefangehn** [comment]
Is there a ticket about the javascript build failures? So far I haven't found out what the exact problem is.

I do have a local branch that gets rid of bower and uses npm to install the latest versions of all required dependencies and at least a local build works fine for me. I can turn that into a PR but held back with submitting that so far.

**Comment by jelmer** [comment]
I don't think there's a separate issue for it, but I mentioned it in #617 

Anything that makes the JavaScript build simpler is a win IMO, so I'd encourage you to submit that PR :)

**Comment by stefangehn** [comment]
> I don't think there's a separate issue for it, but I mentioned it in #617
> 
> Anything that makes the JavaScript build simpler is a win IMO, so I'd encourage you to submit that PR :)

there you go #695 is what I had in mind :)

**Comment by blatinier** [comment]
I think that with the discussion is now off topic :) 
@stefangehn The improvement of the js build process you did is great!
Another thing to would would be to bring this 90's flavored JS back to the present with some ES6, or maybe some modern framework (Vue, React, you name it…)
As for this issue I close it.
