### ISSUE TITLE
Add support for LMDB

### ISSUE THREAD

**Issue by farooqkz** [posativ/isso#705]
https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database

### Why LMDB?
 - Isn't key value store much less complicated than traditional sqlite?
 - It seems that according to benchmarks LMDB outperforms sqlite3
 - It is still a library DB and not dedicated.

**Comment by jelmer** [comment]
Performance should not really be a concern for most isso installations - it's meant to be small and self-hosted - and I haven't heard it being an issue in practice.

For the sort of data that isso stores, LDMB would actually make things more complicated as we now have to deal with some of the things that sqlite previously took care of - structured data.

We'd also have to introduce migration code to move all existing sqlite databases to LMDB.

What actual problems does LMDB solve that isso has today?

**Comment by blatinier** [comment]
@farooqkz According to the wikipedia page you linked: 
"Howard Chu ported SQLite 3.7.7.1 to use LMDB instead of its original B-tree code, calling the end result SQLightning"
Which closes the case right?

**Comment by blatinier** [comment]
My bad, I read wrong. It's a fork called [SQLighttning](https://github.com/LMDB/sqlightning)
But even thought the performance table linked at the bottom of the repo suggest better result for SQLightning, it seems like this is not maintained anymore (no modification made in 8 years)
There is LumoSQL which seems maintained but it looks like more an experiment than a real db for now (I couldn't even find an installation documentation that doesn't require compiling)
@farooqkz I think that LMDB is not the right candidate for an alternative DB connector.
To answer your question/remarks on "Why LMDB": 
 - kv-storage are "simpler" as they don't need relations, foreign keys etc… the down side of this is that all the relational logic is deported to your application and the hard consistency constraint you had in the DB are to be re-implemented in the app.
 - Performance: as stated by jelmer, most isso installation don't need outstanding performance. If it ever comes to be a problem I think that postgreSQL is a better candidate for the job as it keeps the relational part of the db paradigm and it can scale quite well. 
 - libraryDB vs not dedicated: If you face performance issues on your comment section I think that going for some dedicated DB is the least of your problem :D

**Comment by farooqkz** [comment]
Your point is well seen. I close this issue.
