### ISSUE TITLE
Admin panel login redirects to /admin even with subdirectory enpoint

### ISSUE THREAD

**Issue by AlphaJack** [posativ/isso#709]
Even with the public endpoint set like this

```ini
public-endpoint = https://example.org/comments
```

a successful login from https://example.org/comments/admin redirects to https://example.org/admin instead of https://example.org/comments/admin.

The login POST request is correctly sent to https://example.org/comments/login, and static assets are properly loaded from https://example.org/comments/css and https://example.org/comments/js.

**Comment by ix5** [comment]
Possible duplicate of https://github.com/posativ/isso/issues/653

**Comment by AlphaJack** [comment]
I saw that, but in that case the /isso/ part is kept, in my case it redirects directly to /.  
Pheraps it cuts off the last part of the URL (/blog/ in his case, /comments/ in mine)?

**Comment by ix5** [comment]
It would help if you posted your whole server configuration, including proxy section.

I've tested with `/isso` as sub-uri and nginx as described in [Sub-URI](https://posativ.org/isso/docs/setup/sub-uri/) and it works fine.

**Comment by AlphaJack** [comment]
Here is it:

Isso:
```ini
[general]
name =
host = https://example.org/

[admin]
enabled = true
password = XXXXXX

[server]
listen = http://localhost:1234/
public-endpoint = https://example.org/comments
reload = off
profile = off
trusted-proxies = 127.0.0.1
```

NginX:

```nginx
location /comments/ {
 proxy_pass http://127.0.0.1:1234/;
 proxy_set_header Host $host;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_set_header X-Forwarded-Server $host;
 proxy_set_header X-Real-IP $remote_addr;
}

# workaround for /comments/admin redirect
location /admin {
 rewrite ^ /comments/admin;
}
```

**Comment by ix5** [comment]
You're missing
```
            proxy_set_header X-Script-Name /isso; # Or /comments
```

Also, you can leave the trailing slashes

**Comment by AlphaJack** [comment]
Thank you, adding that proxy header fixed the issue

**Comment by schneidr** [comment]
A note for Uberspace users: It is not possible to set the `X-Script-Name` header for a web backend. I implemented the workaround by AlphaJack by adding this line to the .htaccess file in the document root of the site:

    Redirect 301 /admin/ /comments/admin/

**Comment by ix5** [comment]
> A note for Uberspace users: It is not possible to set the `X-Script-Name` header for a web backend. I implemented the workaround by AlphaJack by adding this line to the .htaccess file in the document root of the site:
> 
> ```
> Redirect 301 /admin/ /comments/admin/
> ```

@schneidr would be good of you to document this, either at the [Uberspace docs](https://lab.uberspace.de/guide_isso/) or [Isso's own docs](https://github.com/posativ/isso/tree/64374a8af978f1cfd4a91875c18a309122c7d9ca/docs/docs)
