### ISSUE TITLE
Avatar images are all the same for each comment

### ISSUE THREAD

**Issue by neutrino-bsd** [posativ/isso#712]
Hello! I got isso working, but all avatar pictures are the same, even if I left comments with various devices and IP addresses. 

Is there something obvious that I could have misconfigured ?

**Here is my client code:**

<script data-isso="http://comments.server.pw/"
        data-isso-require-author="true"
        data-isso-require-email="false"
        data-isso-reply-to-self="true"
        src="http://comments.server.pw/js/embed.min.js"></script>

<section id="isso-thread"></section>

**Here is my server config:**

[general]
dbpath = /home/_isso/blog.comments.db
host =
        http://blog.com/
        https://blog.com/
max-age = 15m
notify = stdout
log-file = /home/_isso/blog.log

[admin]
enabled = true
password = passwd

[moderation]
enabled = true
purge-after = 60d

[guard]
enabled = true
require-author = true
require-email = false
reply-to-self = true
direct-reply = 10
ratelimit = 4

[hash]
salt = Eech7co8Ohloopo9Ol6baikj
algorithm = pbkdf2

**Comment by neutrino-bsd** [comment]
I removed the [hash] section completely and restarted "isso" and it seems to have solved the issue. New comments now show different avatars.

**Comment by ix5** [comment]
Wild guess, you're not passing through the remote IPs in your proxy configuration and also not submitting email addresses.
This probably leads to every comment being assigned 127.0.0.1 as its only identifying hash.

https://github.com/posativ/isso/blob/d7b566656d1e7a6d8dc5667b15b0aa2ad52ebf26/isso/views/comments.py#L318

**Comment by neutrino-bsd** [comment]
Thank you for the reply. So the avatar (svg image) is not rendered based on the Author's name of the comment ? You are right, I was sending comments without entering email addresses. When I enter different addresses it generates different avatars. So a fix would be to make e-mail address mandatory to input comments.

I run isso on another domain and use relayd(8) to proxy the requests using gunicorn as explained in the multisite section of the documentation. So most likely my proxy is not setup as a transparent proxy.

**Comment by ix5** [comment]
Solved by setting `require-email = true` or running a transparent proxy.
