### ISSUE TITLE
A sphinx extension for integrating Isso

### ISSUE THREAD

**Issue by SilverRainZ** [posativ/isso#713]
Hello guys, I wrote a sphinx extension which can embed isso comment into document.
Please check out https://sphinx-notes.github.io/isso/ for details. Hope it is helpful to you.

**Comment by jelmer** [comment]
Can you perhaps create a pull request to add it to "Related projects" in docs/docs/extras/contribs.rst ?

**Comment by SilverRainZ** [comment]
See #714, It seems that the contribs.rst doesn't include in https://posativ.org/isso/docs/. And all links in "Related projects" section have wrong format.

**Comment by jelmer** [comment]
On Mon, Mar 15, 2021 at 03:34:17AM -0700, Shengyu Zhang wrote:
> See #714, It seems that the contribs.rst doesn't include in https://posativ.org/isso/docs/. And all links in "Related projects" section have wrong format.
The web site is updated manually I think, and that doesn't happen very
regularly.

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by SilverRainZ** [comment]
I also wrote a [github action](https://github.com/sphinx-notes/pages) for publishing sphinx document to github page, if isso want to use it, I can try to file a PR.
