### ISSUE TITLE
isso.dispatch does not work with the single site

### ISSUE THREAD

**Issue by gour** [posativ/isso#715]
Hello!

I've configured isso to render comments for *single* site - using latest isso/gunicorn installed (pip --user install)  on the Debian-10 server and launching with systemd's user.

Since I'd like to use isso as commenting engine for few sites, I've tried to invoke it with the `isso.dispatch`, but as soon as I switch the comments disappear and after restarting the service invoking `isso.run` the comments do reappear.

Any hint?

**Comment by stefangehn** [comment]
Setting up isso in multi-site mode adds a subdir in the isso URL for each site, did you adapt your website configuration accordingly?
See also https://posativ.org/isso/docs/setup/multiple-sites/

**Comment by gour** [comment]
> Setting up isso in multi-site mode adds a subdir in the isso URL for each site, did you adapt your website configuration accordingly?
> See also https://posativ.org/isso/docs/setup/multiple-sites/

Ahh, thanks for the pointer!

Now I modified webconfig  and I can e.g. access:  `https://tld/foo/admin` which e.g. does list my comments as `Valid`, but on the web site there is only empty comment form, but no old comments are rendered.

Any (further) hint?
