### ISSUE TITLE
Comments submitted cannot be displayed on my website

### ISSUE THREAD

**Issue by jerrylsu** [posativ/isso#718]
## **Issue Discription:**

I use ISSO with Apache2 and Pelican.The ISSO can be displayed on the website normally, but when I submit a comment, nothing happens.

![image](https://user-images.githubusercontent.com/18185325/112737694-38c1f100-8f97-11eb-8074-a775c1b0b8b4.png)

For ISSO server using `isso -c isso.cfg run`, and when I submit a comment, the ISSO server will receive the messages as below picture:

![image](https://user-images.githubusercontent.com/18185325/112737348-e67fd080-8f94-11eb-9964-7ac9af4ce81a.png)

**It looks like it is not written to the sqlite database.**

![image](https://user-images.githubusercontent.com/18185325/112737649-f5678280-8f96-11eb-8efe-7f9549976060.png)

## **Apache2 reverse proxy config:**

```
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	ServerName isso.jerrylsu.net

        DocumentRoot /var/www/blog/isso

        ProxyPreserveHost On
        ProxyRequests Off
        ProxyPass / http://localhost:8280/
        ProxyPassReverse / http://localhost:8280/
        <Proxy *>
                      Order Deny,Allow
                      Allow from all
         </Proxy>
         <Directory /var/www/blog/isso>
              Options -Indexes +FollowSymlinks
          </Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**/etc/hosts config:**

```
127.0.0.1	localhost
127.0.0.1	http://jerrylsu.net
127.0.0.1	http://isso.jerrylsu.net
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	e7cac75317f0
```

## **ISSO server config:**

![image](https://user-images.githubusercontent.com/18185325/112737868-cce08800-8f98-11eb-99fc-63e8c7f20898.png)

```
[general]
dbpath = /var/www/blog/isso/comments.db
name = jerry
host = http://jerrylsu.net
notify = stdout
log-file = /var/www/blog/isso/isso.log

[server]
listen = http://localhost:8280
public-endpoint = http://isso.jerrylsu.net/

[moderation]
enabled = true
purge-after = 30d

[smtp]

[markup]
options = strikethrough, superscript, autolink

[guard]
enabled = true
ratelimit = 3
direct-reply = 3
reply-to-self = true
require-author = true
require-email = true

[admin]
enabled = true
password = custom define

[hash]
salt = Eech7co8Ohloopo9Ol6baimi
algorithm = pbkdf2
```

## ISSO with Pelican blog

- SITEURL = 'http://www.jerrylsu.net'

- ISSO_SITEURL = "http://isso.jerrylsu.net"

- **base.html**

```
...
{% include 'include/isso_script.html' %}
...
```

- **iss_script.html**

```
{% if ISSO_SITEURL %}
    <!-- ISSO -->
<script data-isso="{{ ISSO_SITEURL }}/"
        data-isso-css="true"
        data-isso-lang="en"
        data-isso-reply-to-self="true"
        data-isso-require-author="false"
        data-isso-require-email="true"
        data-isso-max-comments-top="10"
        data-isso-max-comments-nested="5"
        data-isso-reveal-on-click="5"
        data-isso-avatar="true"
        data-isso-avatar-bg="#f0f0f0"
        data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 ..."
        data-isso-gravatar="true"
        data-isso-vote="true"
        data-vote-levels=""
        src="{{ ISSO_SITEURL }}/js/embed.min.js"></script>
    <!-- End ISSO Code -->
{% endif %}
```

- **article.html**

```
...
{% include 'include/comments.html' %}
...
```

- **comments.html**

```
{% if SITEURL and article.status != "draft" %}
<div class="comments">
  <h2>Comments</h2>
  {% if ISSO_SITEURL %}
    <section id="isso-thread"></section>
  {% endif %}
  <noscript>Please enable JavaScript to view the comments.</noscript>
</div>
{% endif %}
```

Thanks for any support!!!

**Comment by ix5** [comment]
Seems like it is failing at CORS preflight (OPTIONS sent but no response).
Can you post the entire contents of the browser console? (available by pressing Ctrl-Shift-K)

Also, you have non-www in your isso `host` config, but your pelican blog SITEURL is with www, is that desired?

**Comment by jerrylsu** [comment]
Hi @ix5 , this is indeed a problem caused by cross-domain resource sharing(CORS).
<img width="347" alt="CORS_error" src="https://user-images.githubusercontent.com/18185325/113080157-00294e00-9209-11eb-884c-e3af8d0886a8.png">

I've solved this problem by setting **host** as you mentioned. 
```
host =
    http://jerrylsu.net
    http://www.jerrylsu.net
```
Thank you very much!

At the same time thanks to this [issue: CORS errors](https://github.com/posativ/isso/issues/547) I also got inspiration.
