### ISSUE TITLE
Question: differentiation by query strings?

### ISSUE THREAD

**Issue by ntnsndr** [posativ/isso#719]
I'm sorry if this is not the right place to be asking this question: But I'm curious if Isso can distinguish between these two pages on a site:

example.com/?p=1
example.com/?p=2

Thanks so much for taking the time to consider this, and for your work on this project.

**Comment by ix5** [comment]
Isso uses `location.pathname` on the client side, which strips any query strings.
https://github.com/posativ/isso/blob/a7c1069cf5feab721a166e7796ce725287a46189/isso/js/embed.js#L56

You could set a custom `data-isso-id` per querystring in your CMS instead.

**Comment by blatinier** [comment]
@ix5 answer shows how it works and how QS could be used so I'm closing this. 
Feel free to re-open if you think it doesn't answer your question :)
