### ISSUE TITLE
Get signals in order to send a notification through a webhook

### ISSUE THREAD

**Issue by Guts** [posativ/isso#722]
From what I understand of the notification mechanism, signals are sent according to events (creation, deletion, etc.) (https://github.com/posativ/isso/blob/a7c1069cf5feab721a166e7796ce725287a46189/isso/ext/notifications.py).

Is it possible to listen to these signals to add additional notification possibilities?

My use case, concerns a webhook.

Thank you for your answer!

**Comment by ix5** [comment]
Since you already created the PR and thus answered yourself, would you mind closing this? ;)

**Comment by Guts** [comment]
> Since you already created the PR and thus answered yourself, would you mind closing this? ;)

As you wish but isn't the idea to wait until the PR is merged instead?
