### ISSUE TITLE
ticking block entity

### ISSUE THREAD

**Issue by skey35** [posativ/isso#723]
my minecraft crasht and  it says description ticking block entity.
what can i do about that??

**Comment by skey35** [comment]
-- Block entity being ticked --
Details:
	Name: storagenetwork:storage_kabel // com.lothrazar.storagenetwork.block.cable.link.TileCableLink
	Block: Block{storagenetwork:storage_kabel}[down=cable,east=inventory,north=cable,south=none,up=cable,west=none]
	Block location: World: (-1717,64,4702), Chunk: (at 11,4,14 in -108,293; contains blocks -1728,0,4688 to -1713,255,4703), Region: (-4,9; contains chunks -128,288 to -97,319, blocks -2048,0,4608 to -1537,255,5119)
	Block: Block{storagenetwork:storage_kabel}[down=cable,east=inventory,north=cable,south=none,up=cable,west=none]
	Block location: World: (-1717,64,4702), Chunk: (at 11,4,14 in -108,293; contains blocks -1728,0,4688 to -1713,255,4703), Region: (-4,9; contains chunks -128,288 to -97,319, blocks -2048,0,4608 to -1537,255,5119)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:473)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:164)


i have this but i don't know what i can do to fix it

**Comment by ix5** [comment]
@skey35 would please close this issue? It has nothing to do with the isso commenting system. Maybe you got here by mistake?
