### ISSUE TITLE
Disqus import failing if there are threads without titles

### ISSUE THREAD

**Issue by waqqasdadabhoy** [posativ/isso#728]
I'm getting the following error while importing a Disqus file:

```
Traceback (most recent call last):
  File "/usr/bin/isso", line 11, in <module>
    load_entry_point('isso==0.12.2', 'console_scripts', 'isso')()
  File "/usr/lib/python3/dist-packages/isso/__init__.py", line 249, in main
    migrate.dispatch(args.type, mydb, args.dump, args.empty_id)
  File "/usr/lib/python3/dist-packages/isso/migrate.py", line 367, in dispatch
    cls(db, dump).migrate()
  File "/usr/lib/python3/dist-packages/isso/migrate.py", line 137, in migrate
    self.insert(thread, res[id])
  File "/usr/lib/python3/dist-packages/isso/migrate.py", line 87, in insert
    self.db.threads.new(path, thread.find(
AttributeError: 'NoneType' object has no attribute 'strip'
```
 
I found that it occurs because there are some threads in the XML file without titles:

```
<thread dsq:id="1079336008">
<id />
<forum>redacted</forum>
<category dsq:id="435915" />
<link>http://localhost:4000/blog/2013/02/12/redacted/index.html</link>
<title />
<message />
<createdAt>2013-02-12T16:29:45Z</createdAt>
<author>
<name>Redacted</name>
<isAnonymous>false</isAnonymous>
<username>redacted</username>
</author>
<isClosed>false</isClosed>
<isDeleted>false</isDeleted>
</thread>
```

I have found that changing lines 87-88 in `migrate.py` to the following, to convert the `None` to an empty string, to convert the `None` to an empty string, fixes the problem (not being a Python programmer, I'm not sure if this is a proper solution):

```
            thread_title = thread.find(Disqus.ns + 'title').text or ''
            self.db.threads.new(path, thread_title.strip())
```

**Comment by ix5** [comment]
Nicely done! Would you mind submitting a Pull Request for your solution?

It seems that same "fix" would also be applicable to the WordPress and Generic importers.

My stylistic preference would be:
```python
thread_title = thread.find(Disqus.ns + 'title').text.strip() or ""
self.db.threads.new(path, thread_title)
```
Though I tend to prefer "Imported Thread" or some other default instead of just an empty string. Open to discussions...

If you like, creating a test case for your Disqus import (missing/empty titles) would also be appreciated.

**Comment by ix5** [comment]
Tracked in #855
