### ISSUE TITLE
Enabling Gravatars and Admin After the Fact?

### ISSUE THREAD

**Issue by madranet** [posativ/isso#729]
I've had Isso up and running for a few years now on my site: https://stiobhart.net

I've recently found out that it's now possible to use Gravatar avatars with Isso [this wasn't supported when I first installed it, many moons ago].

I want to enable this feature. So I've added the necessary lines to my `isso.cfg`

````
; use gravatar 
gravatar = true
; default url for gravatar. {} is where the hash will be placed
gravatar-url = https://www.gravatar.com/avatar/{}?d=identicon
````
and restarted Isso

````
$ sudo service isso restart
````

but I don't see any Gravatars. I've also opened my `comments.db` file and there's no `gravatar_image` field been added to `comments` [which the docs suggest will happen if  Gravatars are enabled in the config]... 

  >When set to true this will add the property "gravatar_image" containing the link to a gravatar image to every comment.

I've even tried manually editing a copy of my `comments.db` file and adding this field under comments [as a VARCHAR] to see if that would kick-start things. But no dice.

I also tried adding

````
[admin]
enabled = true
password = xxxxxxxx
````
to my `isso.cfg` to turn on the admin interface, which is another new feature, added since I first installed Isso. 

And, as with enabling Gravatars, I've done `sudo service isso restart`.  But, again, nothing changes. when I go to the admin page I see the _"Administration is disabled on this instance of isso. Set enabled=true in the admin section of your isso configuration to enable it."_ message.

It's like isso is not picking up changes I've made to the `isso.cfg` file and I can't understand why. I even restarted my webserver itself and still no change. It's left me wondering whether enabling Admin and Gravatars has to be done at initial setup and that's why it's not working with mine; because I'm trying to enable them on an Isso installation which is already up and running for a few years?

Is there something else I need to do, for Isso to pick up these new settings?

**Comment by mdehghani65** [comment]
i have the same question. I have configured .conf as follows:

gravatar = true
gravatar-url =https://www.gravatar.com/avatar/{}

**Comment by mdehghani65** [comment]
its kind of tricky. apparently in addition to backend settings you should enable gravatar in client settings and also disable avatar in client settings.

**Comment by ix5** [comment]
@madranet adding the `[admin]` section with both properties should be sufficient in addition to restarting the isso server.
Are you sure there are no typos? Maybe isso is complaining about an unknown config key on startup, should be in the log via `journalctl -u isso.service` (or whatever logging system you use).

For reference, that's what it should look like:
```conf
[admin]
enabled = true
password = strong_default_password_for_isso_admin
```

As for your gravatar issue, you also need to edit the client settings and set `data-isso-gravatar` to true as well as setting `data-isso-avatar` to false, as @mdehghani65 helpfully pointed out.

**Comment by madranet** [comment]
Thanks @ix5 and @mdehghani65 for trying to help with this.  My [admin] settings were already present and correct in _isso.cfg_ and there's nothing untoward in _journalctl_'s logging.

However I didn't have the client options set. I've done that now. But it's still not working. The default avatars have gone. But I'm getting nothing in their place:

![SS 2021-12-21 at 22 26 42](https://user-images.githubusercontent.com/669658/147006185-c545aa73-66e7-4a06-86c1-005f78d3f53a.png)

What should be the Gravatar image is _undefined_ in the source code:

![SS 2021-12-21 at 22 26 34](https://user-images.githubusercontent.com/669658/147006217-c433faae-1d5e-4cb4-89a2-819d04ad3943.png)

Looking at the browser dev tools console, it looks like Isso is looking for the Gravatar images on the local server, rather than on _gravatar.com_ [embed.min.js is the Isso script]:

```
undefined:1 GET https://stiobhart.net/2020-06-14-twatter-revisited/undefined 404 (Not Found)
Image (async)
n.htmlify @ embed.min.js:formatted:1428
d @ embed.min.js:formatted:1922
(anonymous) @ embed.min.js:formatted:2140
(anonymous) @ embed.min.js:formatted:2139
(anonymous) @ embed.min.js:formatted:1094
setTimeout (async)
(anonymous) @ embed.min.js:formatted:1093
resolve @ embed.min.js:formatted:1092
(anonymous) @ embed.min.js:formatted:1230
r @ embed.min.js:formatted:1158
s.onreadystatechange @ embed.min.js:formatted:1169
XMLHttpRequest.send (async)
s @ embed.min.js:formatted:1174
fetch @ embed.min.js:formatted:1229
p @ embed.min.js:formatted:2134
(anonymous) @ embed.min.js:formatted:2158
t @ embed.min.js:formatted:219
(anonymous) @ embed.min.js:formatted:223
```
This is what I have client side.  It's a Hugo site. Hence the Golang template syntax:

![SS 2021-12-21 at 22 35 28](https://user-images.githubusercontent.com/669658/147006497-b6448246-ad11-4974-942f-8d483ae44c20.png)

I showed my server config above. But here it is again:

```
; gravatar stuff
gravatar = true
; default url for gravatar. {} is where the hash will be placed
gravatar-url = https://www.gravatar.com/avatar/{}?d=identicon
```

```
[admin]
enabled = true
password = XXXXXXXXXXXX
```

**Comment by ix5** [comment]
A couple of observations:

1. You do not need to create an `gravatar_image` field in your database. It will not be utilized. Gravatar images (or rather, the URLs to the individual gravatars) are generated on-the-fly:
https://github.com/posativ/isso/blob/9e021cb6263e921ac519f52b82df3f66a297d3d1/isso/views/comments.py#L856-L864

2. There is no database setting that records whether you have the admin interface enabled or not. The option is read at startup by isso.

3. Are the other settings in your config file being honoured by isso? I have a feeling that you might be editing the wrong file/placing the file at the wrong place and isso using the default one instead.

4. To truly solve your issue, would you mind posting the following in full:
    - isso version and where you got it from (pypi, installed using git + manual make, from distro package repos, ...)
    - full isso config file (and where you placed it)
    - arguments you are running isso with. In case you are using debian's/ubuntu's isso package, everything inside `/etc/isso.d/*`, the systemd unit files or init.d stuff, basically any of the weird custom stuff debian packaging maintainers chose to add, see https://github.com/posativ/isso/issues/671
    - full client config - I see the following on stiobhard.net: `<script data-isso="https://stiobhart.net/isso/" src="https://stiobhart.net/isso/js/embed.min.js" data-isso-css="false" data-isso-gravatar="true" data-isso-avatar="false"></script>`
    - full logs of isso starting up, also the contents of the log file (as specified in `[general] -> log-file`) (in case you do not use `stdout` as `notify`)
    - any other part of your setup, e.g. which server you are running (though it should not have much bearing on isso's server configs, I see you running `nginx/1.18.0 (Ubuntu)`)

5. It seems rather than rendering `comment.gravatar_image`, your instance of isso is returning (on the server side) the string `undefined`. If I monkey-patch `_add_gravatar_image()` to return `item['gravatar_image'] = None`, the client receives e.g. the following:
 ```json
{
  "id": null,
  "total_replies": 3,
  "hidden_replies": 0,
  "replies": [
    {
      "id": 1,
      "parent": null,
      "created": 1640127975.8828285,
      "modified": null,
      "mode": 1,
      "text": "<p>test</p>",
      "author": "My namen",
      "website": null,
      "likes": 0,
      "dislikes": 0,
      "notification": 0,
      "hash": "4505c1eeda98",
      "gravatar_image": null,
      "total_replies": 0,
      "hidden_replies": 0,
      "replies": []
    }
  ]
}
```


That results in `<img src="null">`, in the rendered `jade` html, not `<img src="undefined">`. 
On stiobhart.net, I receive e.g. for `https://stiobhart.net/isso/?uri=%2F2020-06-14-twatter-revisited%2F&nested_limit=5` the following:
```json
{
  "id": null,
  "total_replies": 2,
  "hidden_replies": 0,
  "replies": [
    {
      "id": 131,
      "parent": null,
      "created": 1608033322.37563,
      "modified": null,
      "mode": 1,
      "text": "[...]",
      "author": "xxx",
      "website": "https://stiobhart.net",
      "likes": 3,
      "dislikes": 0,
      "notification": 0,
      "hash": "xxx",
      "total_replies": 0,
      "hidden_replies": 0,
      "replies": []
    }
  ]
}
```

Note the missing `gravatar_image` field. So it seems your server is not sending `gravatar_image` and thus not populating that field when sending the json data.
So yet another clue that your server config simply isn't being read. Maybe there's some kind of issue with it that the parser stops reading it midway through, maybe a mix of `#` and `;`-style `.ini` comments, could be anything. Or maybe you have the `gravatar` options in the wrong section? It belongs in `[general]`.

---

So my money's on you not having pointed isso to the correct config file. A simple `isso -c /path/to/your/isso.cfg run` should clear up things.

**Comment by madranet** [comment]
Halleleujah! --I've got it working:

![SS 2021-12-22 at 12 43 15](https://user-images.githubusercontent.com/669658/147094695-de84ee1d-305d-4779-bb5b-2c5c30c7b6c7.png)

Not for the first time, it was a [PEBKAC](https://en.wikipedia.org/wiki/User_error) problem.

I was convinced my _isso.cfg_ was being read correctly, because I was receiving notification emails when someone posted a comment.  However, when I examined my `/etc/systemd/system/isso.service` it turned out that the _isso.cfg_ file I was editing to add the Gravatar stuff was not the same _isso.cfg_ file the Isso service was using. 

I have a vague memory that, at some stage in the past, I re-installed Isso, after swapping my server from Debian to Ubuntu .  When I re-installed Isso, I installed it into a different directory than I had originally. So I actually still had the old inactive version on the server and, although I had been editing the config file in the new location, the Systemd service was still reading the old config from the previous location.

Phew! --got there in the end

Thanks for the help!
