### ISSUE TITLE
Dispatch returning a 404 leads to a spurious error message

### ISSUE THREAD

**Issue by vsajip** [posativ/isso#736]
Returning a 404 here
https://github.com/posativ/isso/blob/535c729cf3ef2ea2438a92ca1e06c517d34c286d/isso/dispatch.py#L49-L50
Leads to a spurious error message at startup when multiple sites are configured, due to this logic:
https://github.com/posativ/isso/blob/535c729cf3ef2ea2438a92ca1e06c517d34c286d/isso/__init__.py#L186-L194

Any reason why a 200 can't be returned instead of a 404 in this case? Isso works fine despite the misleading error message, as long as the CORS issue in #735 is handled correctly.

**Comment by ix5** [comment]
The decision to return a 404 was made in b15f1773 by the project author, probably with not too much thought about the correct response code.

I can't see any reason for not returning a 200 here, apart from semantics on whether an empty page _must_ be a 40X.

**Comment by ix5** [comment]
@vsajip submit a PR if you like, this is a 1-line fix.
No one has raised objections so far and again, I can't see any reason for keeping the current state, which probably wasn't intentional anyway.

**Comment by ix5** [comment]
Having visited this again, I'm not sure any "fix" is needed here.

If you have a multi-site setup, you'll have e.g.

`http://comments.foo/`, which is will return a 404 (or 200, if changed) with a list of all `name`s from `[general]`, e.g.
```
/foo
/bar
```
https://github.com/posativ/isso/blob/535c729cf3ef2ea2438a92ca1e06c517d34c286d/isso/dispatch.py#L49-L50

Then you'll have `http://comments.foo/foo` and `http://comments.foo/bar` with API endpoints such as `http://comments.foo/foo/admin` and `http://comments.foo/foo/js/embed.min.js`.

The host checker from `__init__` you posted will only iterate over the `hosts` from `[general]`, e.g. `http://my.site` and `http://other.site`.

You should not have `http://comments.foo` in your `host`s.

Unless I'm mistaken, there is no need to take any action (unless you still want to change the `name` enumeration to a 200 - but that part shouldn't be user-facing anyway).

**Comment by vsajip** [comment]
It's not end-user facing, but developers are users, too :slightly_smiling_face: and I was only thinking to avoid the spurious error message. Anyway, I think the multi-site hosting probably needs to be implemented differently using a single Isso instance, as discussed elsewhere IIRC.
