### ISSUE TITLE
Isso not able to connect to the host website

### ISSUE THREAD

**Issue by vegeta123254** [posativ/isso#737]
My website is running on one server and my isso service is running on another server. 

 WARNING: unable to connect to your website, Isso will probably not work correctly. Please make sure, Isso can reach your website via HTTP(S).
I am getting the above while I try to run the isso service.
This is my server config file,

[general]

; database location, check permissions, automatically created if not exists
dbpath = [path]

; Your website or blog address (not the location of Isso!)
; You can add multiple hosts for local development
; or SSL connections. There is no wildcard to allow
; any domain.
host = [website path]

;To moderate comments, either use the activation or deletion URL in the logs
;or use SMTP to get notified on new comments including the URLs
;for activation and deletion:
;notify = smtp

[moderation]
enabled = false
purge-after = 30d

[server]
listen = http://localhost:8081
reload = off
profile = off

[smtp]
host = localhost
port = 25
security = none
from = info@example.com
timeout = 10

[guard]
; Enable basic spam protection features, e.g. rate-limit per IP address
; (/24 for IPv4, /48 for IPv6).
enabled = true
ratelimit = 2
direct-reply = 3
reply-to-self = true

[markup]
options = strikethrough, superscript, autolink
allowed-elements =
allowed-attributes =

What could I be missing?

**Comment by SnorlaxYum** [comment]
the warning already told u about it.
make sure the website specified in `host` can be accessed by isso service on ur server. (maybe u entered wrong format? correct format could be like: https://ur-domain.tld/)  
anyway if u can reach ur deployed isso service on ur website, then it's not a problem (maybe just something with ur server network settings or whatever).
