### ISSUE TITLE
Is isso an http service : QUESTION

### ISSUE THREAD

**Issue by vegeta123254** [posativ/isso#738]
My host is running on an https server.
I have isso installed on another server.
In the isso.cfg
```
[server]
listen=http://example_server:80
```

Since host is https and isso service is http.
I get that request is blocked and content must be served over https.
I cannot change the host to http.
What to do?
Any ideas?

**Comment by SnorlaxYum** [comment]
why change it to http??
just get a certbot service working on ur server where u host ur isso service......
Their tutorial pretty good: https://certbot.eff.org/
with the certbot it's easy to power ur isso with https without having to renew the cert manually.

**Comment by vegeta123254** [comment]
@SnorlaxYum , so basically it runs on http endpoints only is it?

**Comment by SnorlaxYum** [comment]
> @SnorlaxYum , so basically it runs on http endpoints only is it?

depends on how u configure. can also run on a unix socket.
Then u can make nginx proxy it using `uwsgi_pass`.

**Comment by vegeta123254** [comment]
Can't we just,
```
[server]
listen=https://example_server:443
```
This seem to throw an error, while I run,
```
Traceback (most recent call last):
  File "/bin/isso", line 11, in <module>
    load_entry_point('isso==0.12.5', 'console_scripts', 'isso')()
  File "/usr/local/lib/python3.8/site-packages/isso/__init__.py", line 290, in main
    wsgi.SocketHTTPServer(sock, make_app(conf)).serve_forever()
  File "/usr/local/lib/python3.8/site-packages/isso/wsgi.py", line 203, in __init__
    HTTPServer.__init__(self, sock, SocketWSGIRequestHandler)
  File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/http/server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "/usr/local/lib/python3.8/socket.py", line 752, in getfqdn
    name = name.strip()
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by SnorlaxYum** [comment]
why expect isso to do the jobs of reverse proxy servers like nginx?
if u r not sure about what u r doing by checking the offical doc, just pick one of the [unofficial tutorials](https://github.com/posativ/isso/wiki/Tutorials) and read, then try following it.

**Comment by vegeta123254** [comment]
I am actually trying to integrate it with mkdocs material and hence the confusion

**Comment by SnorlaxYum** [comment]
no matter what website u r trying to integrate with isso, just get isso 
running on ur server first. Then the rest is super easy to complete.
