### ISSUE TITLE
Configure the client to connect to isso SQLite

### ISSUE THREAD

**Issue by WodenWang820118** [posativ/isso#740]
Hi, thanks for building the awesome commenting server. Since I have no experience with "server" stuff, I want to clarify something that I don't understand. I followed the documentation to run isso file, make the connection with it. The tutorials I found are all for Ubunto, but I am using Windows 10.

```
[general]
dbpath = ./isso/comments.db
host = http://localhost:8501/ # the website url
max-age = 15m ; the maximum time the user can edit the comments

[server]
listen = http://localhost:8501/

; comments will be moderated first before it is published
[moderation]
enabled = true
purge-after = 30d
```
I can `isso -c /path/to/isso.cfg run` to connect to the host, and its message is in the command line.

**1. Here is my first question: is the server the same address as the website? If it's not, what should I do if, for now, the website is on localhost?**

Then, I followed the client part, which embed the JS file into the HTML.

**2. My second question is, what should I write inside the `embed.min.js`?**
**3. The `data-isso-id="/path/to/resource"` that the path to the resource is referring to the `isso` file in my directory, right?**

Sincerely,

**Comment by SnorlaxYum** [comment]
1. the isso server listens on `http://127.0.0.1:8501` on ur server. but to make it production-ready, check [deployment](https://posativ.org/isso/docs/extras/deployment/) for a production-ready way to run it. 
2. to make it listen on a public domain, check [Sub-URI](https://posativ.org/isso/docs/setup/sub-uri/). (u can also make it listen on a sub-domain depending on ur need).
3. `data-isso-id`: the page path where u post comments. For example, a visitr post a comment on `https://ur.website/path`, here `data-isso-id` is `/path`

**Comment by WodenWang820118** [comment]
Thank you!
I feel like when I go through the docs, there's a huge gap since I am a newbie in terms of back-end and server. I've also found another way to make it successfully with [Caddy](https://github.com/caddyserver/caddy), which is easier for me. I'll edit the title and post a short answer here. Finally, close the issue.

Sincerely,

**Comment by WodenWang820118** [comment]
This is the short answer I've found to connect the host website and the server, in which the answer is from [here](https://stiobhart.net/2017-02-24-isso-comments/).
```
[general]
dbpath = isso/comments.db
;this will be the 'X-Script-Name' we proxy server requests to [later!]
name = isso
host = http://localhost:8501/
log-file = isso/isso.log

[server]
;port to listen on. choose a number you like!
listen = http://localhost:8181/ # connect to the server
```
The command `isso -c isso/isso.cfg run` to run isso instance.

Then, with [Caddy](https://caddyserver.com/docs/install), the file name would be "Caddyfile", without any extension.

localhost:8501 {
  redir http://localhost:8501/
}

```
localhost:8501 {
  root * http://localhost:8501/

  #compression on
  gzip

  #Isso Comments
  proxy /isso localhost:8181 {
  without /isso
  transparent
  header_upstream X-Script-Name /isso
  }
}
```
The command `caddy run` to connect to the proxy server.

```
<script data-isso="http://localhost:8181/"
      src="http://localhost:8181//js/embed.min.js"></script>
<div>
    <section id="isso-thread"></section>
</div>
```
In the HTML part.

And the comments block should show up.
