### ISSUE TITLE
importing xml comments into docker isso?

### ISSUE THREAD

**Issue by 4044ever** [posativ/isso#742]
Is there a method to import xml comments into a docker based isso? I am on Debian 10 and run isso 12.5

(really hard to setup, but it finally works, and work very well)

**Comment by ix5** [comment]
Have you tried [making any effort to research your issue](https://letmegooglethat.com/?q=docker+run+interactive+shell)?

Here's an idea:

```sh
docker run -it <isso-image> /bin/bash
```

Together with [isso docs: Migration](https://posativ.org/isso/docs/quickstart/#migration) you should be able to get going.

**Comment by 4044ever** [comment]
I don't see documentation for that. Unfortunately I am no Docker expert. I gave up on Isso already. It's a pity, it's nice, but really hard to install. Too hard.

**Comment by ix5** [comment]
What I meant is that you can run a bash shell inside your docker container. From there on, you can simply import an existing xml file containing your comments.

There is no fundamental difference to running isso inside a docker container to using plain isso on plain debian. The same concepts apply. The only thing to keep in mind is that if you want to access files that are on your host (e.g. `disqus.xml`), you need to make them available to your container.

There is an example provided with the default `Dockerfile`:
https://github.com/posativ/isso/blob/abe0a9a511c05ca6d3fa3ef1c499fd98085f30e9/Dockerfile#L33-L34
