### ISSUE TITLE
Received email has a Random text in the sender's email address

### ISSUE THREAD

**Issue by vegeta123254** [posativ/isso#745]
The email received has a random text, 
**Ich schrei sonst!** beside the sender's mail address.
Below, is a part of my config file,
```
[general]
notify = smtp
[smtp]
host = smtphost
port = 25
security = none
from = example_sender@tld.com
to = example_receiver@tld.com
timeout = 10
```

Am I missing something?

**Comment by KaiserBarbarossa** [comment]
> The email received has a random text, **Ich schrei sonst!**
That’s not random. isso stems from that sentence: **I**ch **s**chrei **so**nst as far as I remember.

It should work using the following in your configuration

```ini
[smtp]
from = Name to show <mail@example.com>
```

Of course you could replace "Name to show" with the email address.

**Comment by vegeta123254** [comment]
Thank you @KaiserBarbarossa . Worked like a charm.
Also one more doubt, 
If I have to send notification to multiple users, 
```
[general]
notify = smtp
[smtp]
host = smtphost
port = 25
security = none
from = "Name to show" <example_sender@tld.com>
to = example_receiver@tld.com, example_receiver2@tld.com
timeout = 10
```
But only one receiver, example_receiver@tld.com seems to get the notification.
Am I missing something?
