### ISSUE TITLE
How does isso prevent users from voting multiple times on the same comment? How does isso handle spam?

### ISSUE THREAD

**Issue by lumenwrites** [posativ/isso#749]
Hey guys! I'm trying to build a commenting system for my website similar to isso. I don't want to require users to sign up, I want username/email to be optional, just like in isso.

I wanted to ask - how does isso allow loginless comments, and deal with spammers or people who want to manipulate upvotes?

I'd really love to find a solution to these issues that doesn't require users to create an account, and it seems like you guys have done that somehow.

**Comment by ix5** [comment]
Isso records the IP address of the person submitting the comment/vote.

Moreover, you can enable the comment guard/moderation feature, which will only display comments to other users after you, the site admin, have manually approved them (or after a timeout iirc).

Multiple votes coming from the same IP address for the same comment are silently dropped. Isso uses a bloom filter for that, see:
https://github.com/posativ/isso/blob/9e021cb6263e921ac519f52b82df3f66a297d3d1/isso/db/comments.py#L296-L300

**Comment by ix5** [comment]
Would you mind closing this issue to not clog up the bug tracker? We can of course still discuss this if you have further questions. GitHub will not prevent anyone from commenting on closed issues afaik

**Comment by lumenwrites** [comment]
Sorry, I haven't noticed your reply before. Thank you so much for taking the time to reply!

**Comment by ix5** [comment]
Happy to help!
