### ISSUE TITLE
Please add more maintainers

### ISSUE THREAD

**Issue by fluffy-critter** [posativ/isso#752]
There's a lot of pending changes that really should be merged in, and this project is starting to feel abandoned, when a lot of people are very enthusiastic about improving it. It would be really nice, therefore, if some more people could be appointed maintainers/admins of the repository. @ix5 has done some amazing work in reviewing PRs, and as such I'd like to nominate them.

**Comment by ix5** [comment]
Thank you for your kind words! I'd certainly be up for trimming the bug tracker a bit and merging trivial fixes.
Larger architectural discussions and uploading to pypi is something I'd leave with the current maintainers though.

@jelmer and @blatinier have done a stellar job so far, but it seems they (rightfully so!) value their private lives, which necessitates a few more maintainers.

**Comment by ix5** [comment]
I'd nominate @Guts, @stefangehn who I think have made some important upkeep contributions.
And maybe @BookGin if they want to help automate a bit of the deployment/CI process.

**Comment by jelmer** [comment]
I'm in favour of adding more maintainers in general.

That said, time is not really the issue that has prevented me from merging PRs. The testing situation for isso isn't great - there are a handful of tests, and mostly for Python. Every PR (and you can find several examples of this happening) risks breaking isso for the majority of users that doesn't use the feature.

**Comment by ix5** [comment]
The creator of isso, posativ, has added me as a maintainer. We have also been in contact about trying to open up and modernize some of the development practices and opportunities for community engagement.

We'll be looking into using GitHub Discussions for support requests to keep the issue tracker on a manageable level (which we've managed to cut down to ~120 from over 160 open issues).

**Comment by fluffy-critter** [comment]
That's great news! I think that resolves this issue then. :)
