### ISSUE TITLE
WSGI framework

### ISSUE THREAD

**Issue by posativ** [posativ/isso#76]
Switch from werkzeug to a lighter framework (such as WebOb (or bottle)) or to more feature-rich framework such as Pyramid.

**Comment by jonathan-s** [comment]
The framework that comes to mind I would think fits this would be flask. In my mind it'd be nice to clean up some of the cruft that has gathered. Thoughts @blatinier and others?

**Comment by mcepl** [comment]
> The framework that comes to mind I would think fits this would be flask. In my mind it'd be nice to clean up some of the cruft that has gathered. Thoughts @blatinier and others?

Except flask is by mtsushiko as well … isn’t it dependent on werkzeug in the end?
