### ISSUE TITLE
[server] 500 Error with wrong parent

### ISSUE THREAD

**Issue by AlekseyLobanov** [posativ/isso#765]
Hello.
I use latest stable version with Docker setup.
I found that internal sqlite table does not use any constraints on `parent` column of table comments which may be a problem in two cases.
1. DB is corrupted and one of the parents is not valid. 
2. Someone trying to add comment with invalid parent.

I tried second case with curl and got 500 Error on client and stacktrace below on server
```
2022-01-29 22:57:29,824 ERROR: POST /new
Traceback (most recent call last):
  File "/isso/lib/python3.8/site-packages/isso-0.12.5-py3.8.egg/isso/__init__.py", line 147, in dispatch
    response = handler(request.environ, request, **values)
  File "/isso/lib/python3.8/site-packages/isso-0.12.5-py3.8.egg/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/isso/lib/python3.8/site-packages/isso-0.12.5-py3.8.egg/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/isso/lib/python3.8/site-packages/isso-0.12.5-py3.8.egg/isso/views/comments.py", line 307, in new
    rv = self.comments.add(uri, data)
  File "/isso/lib/python3.8/site-packages/isso-0.12.5-py3.8.egg/isso/db/comments.py", line 57, in add
    if ref.get("parent") is not None:
AttributeError: 'NoneType' object has no attribute 'get'
```

**Steps to reproduce:**
1. Start Docker instance of isso (on http://127.0.0.1:8080/ for example)
2.  POST request http://127.0.0.1:8080/new?uri=%2Fbase.html with valid comment and wrong parent. I used "Copy as cURL" button on Firefox Web Tools and replaced `null` with some invalid id (`42` for example)

**Comment by ix5** [comment]
@AlekseyLobanov thank you for your report.
Would you mind working on a fix and submitting a PR?

**Comment by ix5** [comment]
Related: https://github.com/posativ/isso/issues/531

**Comment by ix5** [comment]
@AlekseyLobanov would you like to work on a PR?

**Comment by ix5** [comment]
Copying over from #531, quoting @budui

> I am porting `isso` from Python to [Go](https://github.com/RayHY/go-isso). While testing I noticed that if I specify a wrong parent(existed but different thread) for the new comment, the new comment will be added successfully but can't be retrievaled with uri.

> Maybe we need to check whether the `tid` of new comment and parent's `tid` are consistent
https://github.com/posativ/isso/blob/6092881bb205c999a8f7f086dd5d20f686d641ea/isso/db/comments.py#L49-L52

**Comment by ix5** [comment]
Tracked in https://github.com/posativ/isso/issues/885
