### ISSUE TITLE
Isso always calls count even if not needed

### ISSUE THREAD

**Issue by GHSam** [posativ/isso#771]
I'm not using comment counts on my page but the isso embed.js code is sending an empty request for them.

It looks like [the count code is missing a check](https://github.com/posativ/isso/blob/a7c1069cf5feab721a166e7796ce725287a46189/isso/js/app/count.js#L24) to see if there are any matching URLs before making the request.

**Comment by GHSam** [comment]
@ix5 just noticed you've added the needs-contributor label. I can send a PR for this if you want?

**Comment by ix5** [comment]
That'd be great! Please explain your rationale though, since I'm still not quite sure what the exact behavior _should_ be.

**Comment by GHSam** [comment]
I was thinking just a test to check if the urls array is empty and if it is, don't bother sending the request as it does nothing if it is empty.

Something like:

```js
// No URLs matched so don't send count request as nothing to count
if (!urls.length) {
    return;
}
```

**Comment by ix5** [comment]
maybe @zaygraveyard is the right person to chime in on this

**Comment by ix5** [comment]
@GHSam would you like to submit a PR with @zaygraveyard's suggestion applied?

**Comment by ix5** [comment]
Tracked in #869
