### ISSUE TITLE
Call for testing: Isso 0.12.6

### ISSUE THREAD

**Issue by ix5** [posativ/isso#806]
We are getting ready to release Isso `0.12.6`.

If no major _new_ bugs are found, we will publish a release within one week (March 6th, 2022).

Please test extensively! Instructions for testing the latest release from the `master` branch can be found at [Installation from source](https://posativ.org/isso/docs/install/#install-from-source).

Here are some ideas:
- Post a comment
- Post an answer to a comment
- Edit your comment
- Test the admin interface
- Delete a comment from admin, then try to delete from frontend
- Reply to a comment that you have deleted from the admin/as another user
- Use curl commands
- Clear your cookies
- Restore certain cookies
- Embed into a single-page application (SPA)
- Zoom inside your browser
- Play with the embed parameters (data-isso-xyz)
- Play with the server config
- Test whether the docker container still works

Here is a sample `isso.conf` for testing:
```conf
[general]
dbpath = comments.db
host =
    http://localhost:8000/
    http://localhost:8080/
    http://localhost:5000/
    http://isso-dev.local/
max-age = 15m
notify = stdout
log-file = isso.log

reply-notifications = false

[admin]
enabled = true
password = admin

[moderation]
enabled = false
purge-after = 30d

[server]
profile = off

[guard]
enabled = false

[markup]
options = strikethrough, autolink, fenced-code, no-intra-emphasis
flags =
allowed-elements =
allowed-attributes =
```

**Comment by ix5** [comment]
Here's a version as of `0.12.6-pre` for testing:

**[isso-0.12.6.tar.gz](https://github.com/posativ/isso/files/8192515/isso-0.12.6.tar.gz)**

**Comment by fliiiix** [comment]
One little data point: did some quick testing on my production site and it looked fine

**Comment by ix5** [comment]
@fliiiix just FYI, all those PRs you opened are perfectly valid but won't make it into this release. Will review when I get to them.

**Comment by fliiiix** [comment]
No worries 0.12.6 seems to work fine most of my PRs are very minor improvements

**Comment by ix5** [comment]
0.12.6 is now released on [PyPi](https://pypi.org/project/isso/0.12.6/).
