### ISSUE TITLE
Github Action should build and deploy api docs

### ISSUE THREAD

**Issue by fliiiix** [posativ/isso#814]
It would be cool to have a easy way to access the build api docs for each PR. 
See: https://github.com/posativ/isso/pull/810#issuecomment-1068210483

If someone wants to work on that just sign up here to do it, otherwise i will create a proposal for that when i find time :D.

**Comment by ix5** [comment]
I've been in contact with @posativ about having docs auto-deploy instead of him uploading them whenever he finds the time.
Let's wait until he has some time to judge the proposal's merits and then potentially include the generated API docs.

**Comment by ix5** [comment]
fwiw, I've created a branch with apidoc generation commands, maybe we can agree on those https://github.com/ix5/isso/tree/apidoc

**Comment by fliiiix** [comment]
But this does not upload the artefacts to somewhere and does not build on a pr right?

**Comment by ix5** [comment]
> But this does not upload the artefacts to somewhere and does not build on a pr right?

Yes, that branch was just an example as a starting point for you.

For auto-deployment, see e.g. https://github.com/SoMainline/docs.somainline.org/blob/9900033292e5cf54ae3ed73edfb43841c51ec84d/.github/workflows/publish.yml

**Comment by ix5** [comment]
The GitHub Action also deploys the API docs since https://github.com/posativ/isso/commit/b2a1c611461b73f3b67c892e04377536b9a2ce4c
