### ISSUE TITLE
Identifying the author of the document

### ISSUE THREAD

**Issue by programLyrique** [posativ/isso#82]
It would be useful to identify the comments of author of the document (or, if it is difficult to do it per document, per website) which is commented, by looking at the email and the username for instance, with a chosen color for the background of the comments for example (and maybe some indication next to the username and some enhancement for the avatar).
![isso](https://cloud.githubusercontent.com/assets/382128/2765131/5957c776-ca20-11e3-9700-bc2aea21e436.png)
.

**Comment by ix5** [comment]
Closing in favour of discussion in #321.

Especially https://github.com/posativ/isso/pull/321#issuecomment-382148195 is a nice solution.

**Comment by ix5** [comment]
Re-opening until someone adds the proposed CSS solution to the docs.

**Comment by BBaoVanC** [comment]
I think a badge next to the author's name plus a different name color would be better than a message background. I think it's easier than trying to deal with trying to make the background fit in with the visual style.

**Comment by ix5** [comment]
As a first step to allow better styling, the author `hash` should be inserted into the `.isso-comment` div, not only as the has to the svg.

@BBaoVanC would you like to work on something like this?

**Comment by BBaoVanC** [comment]
> As a first step to allow better styling, the author `hash` should be inserted into the `.isso-comment` div, not only as the hash to the svg.
> 
> @BBaoVanC would you like to work on something like this?

I'll try and see what I can do. I haven't ever done much with JS so for that part of the client I might need help. I'll make a draft PR if I can figure something out.

**Comment by ix5** [comment]
That's what I mean:

```diff
diff --git a/isso/js/app/templates/comment.js b/isso/js/app/templates/comment.js
index d0daf99..53738b2 100644
--- a/isso/js/app/templates/comment.js
+++ b/isso/js/app/templates/comment.js
@@ -9,7 +9,7 @@ var html = function (globals) {
   var author = comment.author ? comment.author : i18n('comment-anonymous');
 
   return "" +
-"<div class='isso-comment' id='isso-" + comment.id + "'>"
+"<div class='isso-comment' id='isso-" + comment.id + "' data-hash='" + comment.hash + "'>"
 + (conf.gravatar ? "<div class='isso-avatar'><img src='" + comment.gravatar_image + "'></div>" : '')
 + (conf.avatar ? "<div class='isso-avatar'><svg data-hash='" + comment.hash + "'</svg></div>" : '')
 + "<div class='isso-text-wrapper'>"
```

You could then use `.isso-comments[data-hash="0bb73c4f5196"]` as a style selector, or e.g. `.isso-comments[data-hash="0bb73c4f5196"] > .isso-author` for styling only the author's name.

**Comment by ix5** [comment]
Tracked in #844
