### ISSUE TITLE
Support Webmentions

### ISSUE THREAD

**Issue by davidak** [posativ/isso#829]
By supporting [Webmentions](https://www.w3.org/TR/webmention/), a site can be part of the [Indieweb](https://indieweb.org/).

**Comment by ix5** [comment]
This is something that should be implemented as a plugin or as a layer on top of Isso.

Already tracked in https://github.com/posativ/isso/issues/19 (though judging by the lack of contributors to the issue, you can probably guess the likelihood of this ever being implemented).
