### ISSUE TITLE
Gravatar issues

### ISSUE THREAD

**Issue by fliiiix** [posativ/isso#830]
Looks like there is an display issue with gravatar images 
![image](https://user-images.githubusercontent.com/1682954/160294148-2ac89bda-6ee7-4665-b7c8-243a2270f9b4.png)

vs the non gravatar images which are smaller

![image](https://user-images.githubusercontent.com/1682954/160294227-fc2e1619-8c3f-4064-bb5f-2a138eda0f2e.png)

also related this could be a bit misleading: 

> Isso: Client value 'false' for setting 'gravatar' overridden by server value 'true'.
Since Isso version 0.12.6, 'data-isso-gravatar' is only configured via the server to keep client and server in sync

Since the default is `false` and I have not configured `data-isso-gravatar` on client side.

**Comment by ix5** [comment]
https://github.com/posativ/isso/pull/831
