### ISSUE TITLE
Docker won't build docker image

### ISSUE THREAD

**Issue by Gymnae** [posativ/isso#836]
After a fresh clone, I receive the following error:
```bash
# docker build ~/services/isso/git/. -t isso_local
Sending build context to Docker daemon  4.378MB
Step 1/16 : FROM node:dubnium-buster AS jsBuilder
 ---> c90eecc338a8
Step 2/16 : WORKDIR /src/
 ---> Using cache
 ---> 7af30b93c790
Step 3/16 : COPY . .
 ---> b6101fc6177e
Step 4/16 : RUN make init js
 ---> Running in 5b29c106970f
npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-20T18_42_22_229Z-debug.log
make: *** [Makefile:39: init] Error 1
```

My host is a Linux x64 Debian 11 system

**Comment by BBaoVanC** [comment]
I'm getting this same issue, also on a Debian 11 system.

**Comment by ix5** [comment]
A quick [Google-Fu](https://stackoverflow.com/questions/66093284/unsupported-platform-for-fsevents2-3-2-installation-issue) reveals that the OS inside the container most likely has a version of **`npm` that is too old**.

Currently, the Isso `Dockerfile` uses Debian "Buster" as a base for js-related stuff, which seems to bundle a very old version of node and npm.

I've been meaning to revamp the `Dockerfile` for a while now.

How's this for you? Using Alpine instead of Debian/Ubuntu:
```Dockerfile
# Isso production Dockerfile

# First stage: Build Javascript client parts using NodeJS

FROM node:current-alpine AS isso-js
WORKDIR /src/

# make is not installed by default on alpine
RUN apk add --no-cache make

# Only copy necessities, to not trigger re-builds unnecessarily
COPY ["Makefile", "package.json", "package-lock.json", "./"]
COPY ["isso/js/", "./isso/js/"]
COPY ["isso/css/", "./isso/css/"]

# Disable nagware and save some time skipping "security" "audits"
RUN echo -e "audit=false\nfund=false"> /root/.npmrc

RUN make init js

# Second stage: Create production-ready Isso package

# Copy needed files
FROM python:3.10-alpine AS isso-builder
WORKDIR /isso/

# Set up virtualenv
RUN python3 -m venv /isso \
 && . /isso/bin/activate \
 && pip3 install --no-cache-dir --upgrade pip \
 && pip3 install --no-cache-dir gunicorn

# Install cffi dependencies since they're not present on alpine by default
# (required by cffi which in turn is required by misaka)
RUN apk add --no-cache gcc libffi-dev libc-dev

# For some reason, it is required to install cffi before misaka, else pip will
# fail to build cffi
RUN . /isso/bin/activate \
 && pip3 install cffi

# SRC "isso/" is treated as "isso/*" by docker, so copy to subdir explicitly
COPY ["./isso/", "/isso/isso/"]
COPY ["./share/", "./share/"]
COPY ["setup.py", "setup.cfg", "README.md", "LICENSE", "./"]

# Copy over generated Javascript client files
COPY --from=isso-js /src/isso/js/ ./isso/js

# Build and install Isso package
RUN . /isso/bin/activate \
 && python3 setup.py install


# Third stage: Run Isso
FROM python:3.10-alpine AS isso
WORKDIR /isso/
COPY --from=isso-builder /isso/ .

# Clean up
RUN rm -rf /var/apk/cache/* /tmp/* /var/tmp/*

# Configuration
VOLUME /db /config
EXPOSE 8080
ENV ISSO_SETTINGS /config/isso.cfg

# Run Isso via gunicorn WSGI server
CMD ["/isso/bin/gunicorn", "-b", "0.0.0.0:8080", "-w", "4", "--preload", "isso.run", "--worker-tmp-dir", "/dev/shm"]

# Example of use:
#
# Build:
# $ docker build -t isso .
#
# Run:
# $ mkdir config
# $ cp share/isso-dev.conf config/isso.cfg
# $ mkdir db/
# $ docker run -d --rm --name isso -p 8080:8080 -v $PWD/config:/config -v $PWD/db:/db isso:latest
```

**Comment by BBaoVanC** [comment]
> A quick [Google-Fu](https://stackoverflow.com/questions/66093284/unsupported-platform-for-fsevents2-3-2-installation-issue) reveals that the OS inside the container most likely has a version of **`npm` that is too old**.
> 
> Currently, the Isso `Dockerfile` uses Debian "Buster" as a base for js-related stuff, which seems to bundle a very old version of node and npm.
> 
> I've been meaning to revamp the `Dockerfile` for a while now.
> 
> How's this for you? Using Alpine instead of Debian/Ubuntu:
> 
> ```dockerfile
> # Isso production Dockerfile
> 
> # First stage: Build Javascript client parts using NodeJS
> 
> FROM node:current-alpine AS isso-js
> WORKDIR /src/
> 
> # make is not installed by default on alpine
> RUN apk add --no-cache make
> 
> # Only copy necessities, to not trigger re-builds unnecessarily
> COPY ["Makefile", "package.json", "package-lock.json", "./"]
> COPY ["isso/js/", "./isso/js/"]
> COPY ["isso/css/", "./isso/css/"]
> 
> # Disable nagware and save some time skipping "security" "audits"
> RUN echo -e "audit=false\nfund=false"> /root/.npmrc
> 
> RUN make init js
> 
> # Second stage: Create production-ready Isso package
> 
> # Copy needed files
> FROM python:3.10-alpine AS isso-builder
> WORKDIR /isso/
> 
> # Set up virtualenv
> RUN python3 -m venv /isso \
>  && . /isso/bin/activate \
>  && pip3 install --no-cache-dir --upgrade pip \
>  && pip3 install --no-cache-dir gunicorn
> 
> # Install cffi dependencies since they're not present on alpine by default
> # (required by cffi which in turn is required by misaka)
> RUN apk add --no-cache gcc libffi-dev libc-dev
> 
> # For some reason, it is required to install cffi before misaka, else pip will
> # fail to build cffi
> RUN . /isso/bin/activate \
>  && pip3 install cffi
> 
> # SRC "isso/" is treated as "isso/*" by docker, so copy to subdir explicitly
> COPY ["./isso/", "/isso/isso/"]
> COPY ["./share/", "./share/"]
> COPY ["setup.py", "setup.cfg", "README.md", "LICENSE", "./"]
> 
> # Copy over generated Javascript client files
> COPY --from=isso-js /src/isso/js/ ./isso/js
> 
> # Build and install Isso package
> RUN . /isso/bin/activate \
>  && python3 setup.py install
> 
> 
> # Third stage: Run Isso
> FROM python:3.10-alpine AS isso
> WORKDIR /isso/
> COPY --from=isso-builder /isso/ .
> 
> # Clean up
> RUN rm -rf /var/apk/cache/* /tmp/* /var/tmp/*
> 
> # Configuration
> VOLUME /db /config
> EXPOSE 8080
> ENV ISSO_SETTINGS /config/isso.cfg
> 
> # Run Isso via gunicorn WSGI server
> CMD ["/isso/bin/gunicorn", "-b", "0.0.0.0:8080", "-w", "4", "--preload", "isso.run", "--worker-tmp-dir", "/dev/shm"]
> 
> # Example of use:
> #
> # Build:
> # $ docker build -t isso .
> #
> # Run:
> # $ mkdir config
> # $ cp share/isso-dev.conf config/isso.cfg
> # $ mkdir db/
> # $ docker run -d --rm --name isso -p 8080:8080 -v $PWD/config:/config -v $PWD/db:/db isso:latest
> ```

Tested this Dockerfile and it works for me!

**Comment by Gymnae** [comment]
I can second this, the docker file posted by @ix5 in his [reply](https://github.com/posativ/isso/issues/836#issuecomment-1106810323) works fine :)
