### ISSUE TITLE
[client] `fetchComments` is adding another PostBox even if there is already one displayed

### ISSUE THREAD

**Issue by Kerumen** [posativ/isso#842]
Everytime we call `window.Isso.fetchComments()`, a new PostBox is added, even if there is already a PostBox displayed. It means that if we call it 4 times, there will be 4 PostBox displayed.

<img width="961" alt="Screenshot 2022-04-23 at 15 43 20" src="https://user-images.githubusercontent.com/5436545/164901535-25274051-e169-45c4-a56c-4077bd63698c.png">

**Comment by ix5** [comment]
Recent changes made to `isso.js` which moved the logic of the postbox creation to after the `/config` endpoint had been fetched introduced this issue.

Currently, Isso promises the `window.Isso.fetchComments()` and `window.Isso.init()` functions to users [in the docs](https://github.com/posativ/isso/blob/46f1bc851868e406a97c4ab3b9a7f024508503e7/docs/docs/extras/advanced-integration.rst#asynchronous-comments-loading).
Should we keep it that way? IMO those hooks make sense for SPA and the like, although I have to admit I have very little experience with the subject.

@Kerumen, would you like to tackle this issue? In the process, you might use the opportunity to untangle the JS a bit (there is a lot of logic inside `isso.js` that might better be in separate files, afaics, and some `require()` dependency chains seem unnecessarily deep). I defer to your knowledge and experience there.

**Comment by ix5** [comment]
Also, the styling to the comment box in the screenshot you attached looks very cool! Very elegant and understated.

Maybe you could **share the CSS you used**, and **if people agree**, we could make something like it (with better contrast than grey-on-grey text, and without the cool-but-too-whimsical submit button) the **Isso default?**

**Comment by ix5** [comment]
@Kerumen I noticed that I still had https://github.com/posativ/isso/pull/821 open. I changed the logic there and pushed just now, so maybe you could review that PR again, with the new changes.

**Comment by Kerumen** [comment]
> Recent changes made to `embed.js` which moved the logic of the postbox creation to after the `/config` endpoint had been fetched introduced this issue.
> 
> Currently, Isso promises the `window.Isso.fetchComments()` and `window.Isso.init()` functions to users [in the docs](https://github.com/posativ/isso/blob/46f1bc851868e406a97c4ab3b9a7f024508503e7/docs/docs/extras/advanced-integration.rst#asynchronous-comments-loading). Should we keep it that way? IMO those hooks make sense for SPA and the like, although I have to admit I have very little experience with the subject.
> 
> @Kerumen, would you like to tackle this issue? In the process, you might use the opportunity to untangle the JS a bit (there is a lot of logic inside `embed.js` and `isso.js` that might better be in separate files, afaics, and some `require()` dependency chains seem unnecessarily deep). I defer to your knowledge and experience there.

You are right about SPA. I do integrated Isso in a SPA and needed to call `fetchComments` while navigating between posts to load the new comments. Otherwise we were stuck with the comments from the previous post. I can have a look but I have literally no knowledge at all about the codebase and how to develop locally so it can take some time for me to tackle this.

---

> Also, the styling to the comment box in the screenshot you attached looks very cool! Very elegant and understated.
> 
> Maybe you could **share the CSS you used**, and **if people agree**, we could make something like it (with better contrast than grey-on-grey text, and without the cool-but-too-whimsical submit button) the **Isso default?**

Yes of course! I can do a separate PR for this, this one is more in my capabilities 😄 (NB: I took the colors from the [Tailwind Palette](https://tailwindcss.com/docs/customizing-colors#default-color-palette), I really like their default).

**Comment by ix5** [comment]
Just quickly re:

> I can have a look but I have literally no knowledge at all about the codebase and how to develop locally so it can take some time for me to tackle this.

- Clone repo
- `make init js` (will install npm packages and generate js bundles)
- `virtualenv .venv && source .venv/bin/activate && pip install -e .`
- `isso -c share/isso-dev.cfg run`
- Visit [http://localhost:8080/demo/index.html](http://localhost:8080/demo/index.html) in browser

Then you can edit js files. With `npm run watch-dev`, you can run `webpack` automatically whenever a file changes. You will have to refresh to browser tab ofc, there's no "hot-reload" or whatever it's called.

Keep in mind ES5 compatibility (for now, I know it irks you but babel is just _so heavy_) and feel free to iron out any quirks/inconsistencies you see along the way. The upcoming 0.13 release is going to be shipping a few breaking changes, so feel free to go wild ;)

**Comment by Kerumen** [comment]
Thanks for the development steps. I quickly tried to launch the project yesterday and could not reproduce the bug. It seems that in development, `window.Isso.fetchComments()` reload the whole page. I have to dig more.

**Comment by ix5** [comment]
Should mostly be fixed by https://github.com/posativ/isso/pull/821
Still not entirely sure if any of that code is racy, but looks fine for now.
