### ISSUE TITLE
Call for testing: Version 0.13 will be released soon

### ISSUE THREAD

**Issue by ix5** [posativ/isso#892]
The release of Isso version 0.13 is approaching.

### Open issues
~~See [milestone: 0.13](https://github.com/posativ/isso/milestone/5)~~ **None**

### Changes
The main changes are
- the port of the Javascript client code to `webpack` instead of `require.js`
- adding of `<label>`s, using a `<textarea>` instead of buggy `contentEditable` fields
- prefixing all CSS classes with `isso-`.

Pretty **Changelog**: See [isso-comments.de: Isso version 0.13.0.beta1 released](https://isso-comments.de/news/#isso-version-0-13-0-beta1-released)

Comparisons: [commits since 0.12.6](https://github.com/posativ/isso/compare/0.12.6...master), [merged/closed PRs since 0.12.6](https://github.com/posativ/isso/milestone/5?closed=1)

**Comment by ix5** [comment]
**Please test extensively!**

You can download a build of `isso 0.13.0.beta0` here: [isso-0.13.0b0.tar.gz](https://github.com/posativ/isso/files/8840577/isso-0.13.0b0.tar.gz)


Testing using the newly provided official [Docker](https://isso-comments.de/docs/reference/installation/#using-docker) image has also been documented (using `0.13.0.beta0`).

```
docker pull ghcr.io/isso-comments/isso:latest
docker run -d --rm --name isso -p 127.0.0.1:8080:8080 \
    -v /opt/isso:/config -v /opt/isso:/db \
    ghcr.io/isso-comments/isso:0.13.0.beta0
```

**Comment by BBaoVanC** [comment]
Sorry that I didn't notice this earlier but I just noticed that in `admin.html`, it should be `/login/` instead of `/login` for the form. It didn't seem to cause any issue on my live Isso instance with HTTPS, but when tesitng locally I get a 405 method not allowed when trying to log in.

**Comment by ix5** [comment]
Just what I was looking at as well ;) 0.13.0 is live now. Let me know if you find any other issues, but I think 15 days should be enough wait time.
