### ISSUE TITLE
[meta] Website move and re-org

### ISSUE THREAD

**Issue by ix5** [posativ/isso#896]
Since @posativ is not as involved in the project as he used to be, Isso will transition to a community-owned and maintained project under its own umbrella organisation.

As you might have noticed, https://posativ.org/isso/ now redirects to https://isso-comments.de.

See:
- https://github.com/posativ/isso/pull/897

Some other organisational changes will follow soon.

**Comment by posativ** [comment]
@ix5 @jelmer I just transfered the repository from posativ/isso to isso-comments/isso.
