### ISSUE TITLE
isso-comments.de down

### ISSUE THREAD

**Issue by hariom147** [posativ/isso#917]
I'm sure you have noticed and are working on it, but just in case not:

[isso-comments.de](https://isso-comments.de) is down since this morning.

**Comment by cambid** [comment]
@hariom147 Thanks for bringing this up. But the page is accessible here (Switzerland with Init7) without any problems and also testing with https://www.uptrends.de/tools/uptime is working successfully.

Do you get an error message, and can you provide a screenshot from it maybe?

**Comment by ix5** [comment]
The website (including documentation) is hosted on GitHub Pages.
I can't see any issues in the [Incident History](https://www.githubstatus.com/history) and my Uptime monitor for website and demo API didn't indicate anything either.

Might be Cloudflare/GH CDN blocking your IP or otherwise connectivity problems on your end.

**Comment by BBaoVanC** [comment]
Checked myself just now and it looks like there's something wrong with the DNS record (maybe DNSSEC related?)

```console
$ dig isso-comments.de

; <<>> DiG 9.18.4 <<>> isso-comments.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 48340
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 6 (DNSSEC Bogus): (for DNSKEY isso-comments.de., id = 26795)
;; QUESTION SECTION:
;isso-comments.de.		IN	A

;; Query time: 593 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Tue Jul 19 19:06:44 CDT 2022
;; MSG SIZE  rcvd: 91
```

See the line there that starts with `EDE: 6 (DNSSEC Bogus)`

**Comment by atomicwrites** [comment]
Hmm, I'm also getting an NXDOMAIN error from my browser today, I'll check on it once I get home.

**Comment by BBaoVanC** [comment]
Wait, this still hasn't been fixed? I'm pretty sure it's a DNSSEC issue

```console
$ dig isso-comments.de

; <<>> DiG 9.18.10 <<>> isso-comments.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 48925
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 6 (DNSSEC Bogus): (for DNSKEY isso-comments.de., id = 26795)
;; QUESTION SECTION:
;isso-comments.de.		IN	A

;; Query time: 1354 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Sat Jan 07 18:05:53 CST 2023
;; MSG SIZE  rcvd: 91
```

And dnsviz.net also agrees: https://dnsviz.net/d/isso-comments.de/dnssec/

(If it's not easy to just fix the DNSSEC, maybe disable it entirely)

**Comment by ix5** [comment]
Thank you for re-raising the issue, I'll see what I can do on the DNS registrar's side.

**Comment by ix5** [comment]
I turned off DNSSEC from the registrar panel.

@BBaoVanC or @atomicwrites would you kindly ping me in about a day once this change has propagated so I can close the issue then?

**Comment by atomicwrites** [comment]
@ix5 Works for me now, thanks!
