### ISSUE TITLE
Why does data-isso-id need to be written twice?

### ISSUE THREAD

**Issue by flux77** [posativ/isso#924]
According to the documentation at https://isso-comments.de/docs/reference/client-config/?highlight=data-isso-id, there are two places where `data-isso-id` could be written: in the `<script>` tag, or in the tag containing the comments (i.e. `#isso-thread`). The documentation for `data-isso-id` was added in commit 30f0c7eeb895163339d3515fc15f6d408137fee6. Why are there two places to write `data-isso-id`? 

I noticed that the embed script will only use the `data-isso-id` that is in `#isso-thread` (reference: https://github.com/posativ/isso/blob/0.13.0/isso/js/embed.js#L125), so what is the use of the `data-isso-id` in the `<script>` tag?

**Comment by ix5** [comment]
Should be solved by https://github.com/posativ/isso/pull/987

@flux77 please see whether you're satisfied with the wording of the docs now.
