### ISSUE TITLE
Docker: isso:latest still points to 0.12.6

### ISSUE THREAD

**Issue by tribut** [posativ/isso#935]
`ghcr.io/isso-comments/isso:latest` points to an image of isso version 0.12.6.

I would have expected it to be isso 0.13.0, given that 0.13 was released in June and [the README states](https://github.com/posativ/isso#docker) (emphasis mine):

> A Docker image **with the latest stable release** is provided at ghcr.io/isso-comments/isso:latest.

**Comment by ix5** [comment]
`latest` now points to `0.13.0`, see https://github.com/isso-comments/placeholder/pkgs/container/isso

Thanks for notifying!

We ought to automate the release process more.
