### ISSUE TITLE
Please add Multi-CPU architecture for Docker image

### ISSUE THREAD

**Issue by daniel-san05** [posativ/isso#942]
Hello, I would kindly request adding support for Multi-CPU architecture on Docker Image with building and pushing images for different architectures during CI/CD workload.

**Comment by jelmer** [comment]
I think the only way to realistically do this is to build the container images from GitHub actions.

**Comment by ix5** [comment]
I agree with jelmer, we should set up GitHub actions so that on release, the artifacts and docker images are set up automatically.
@daniel-san05 is that something you could help us with?

**Comment by janw** [comment]
Not OP but I'd be happy to help with that; I have some experience with build automation, an d GH actions in particular and would love to contribute.

**Comment by jelmer** [comment]
@janw That'd be great!

**Comment by daniel-san05** [comment]
> I agree with jelmer, we should set up GitHub actions so that on release, the artifacts and docker images are set up automatically. @daniel-san05 is that something you could help us with?

Completely forgot answering the question :-(
But if @janw is contributing already it will go its way ;-).

**Comment by daniel-san05** [comment]
> I compiled one for personal use in the meantime https://hub.docker.com/r/kendofriendo/isso

Tested and it is working fine. 😊
And of course: Happy new year!
