### ISSUE TITLE
Unable to post comments with umlaut domains in the website field

### ISSUE THREAD

**Issue by schneidr** [posativ/isso#951]
## Checklist
- [x] I am running the latest version. Installing Isso from GitHub from the `master` branch does not fix my issue
- [x] I have checked the [troubleshooting guide](https://isso-comments.de/docs/guides/troubleshooting/)
- [x] I have searched the [open issues](https://github.com/posativ/isso/issues), but my issue has not already been reported

* **Note:** I was unable to get the master branch running, but I compared the source code and the relevant parts didn't change

## What is not working?
Posting a comment with an umlaut in the website (IDN) fails. The developer console of the browser shows the error from the server:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Website not Django-conform</p>
```

I tracked it down to the [regex definition in `views/comments.py`](https://github.com/posativ/isso/blob/64374a8af978f1cfd4a91875c18a309122c7d9ca/isso/views/comments.py#L35), which only allows `[A-Z0-9-]`.

Using the validator module instead [looks promising](https://stackoverflow.com/a/45011112/212107), otherwise the domain probably needs to be converted to IDN notation before the check.

## How can one reproduce this issue?
Enter an IDN domain with an umlaut in any installation, it also fails in the demo in the isso website, and check the developer console.

**Comment by ix5** [comment]
Should be resolved by https://github.com/posativ/isso/pull/952
Otherwise, please comment if this should still be an ongoing issue.
