### ISSUE TITLE
IP address ending with "zero" in emails from comments

### ISSUE THREAD

**Issue by roughnecks** [posativ/isso#962]
## Checklist
- ~~[ ] I am running the latest version. Installing Isso from GitHub from the `master` branch does not fix my issue~~
- Using pip here: "Install Isso with pip, using the virtualenv"
- [x] I have checked the [troubleshooting guide](https://isso-comments.de/docs/guides/troubleshooting/)
- [x] I have searched the [open issues](https://github.com/posativ/isso/issues), but my issue has not already been reported

## What is not working?

The mails I'm receiving, at least from 2 different sources I could check, always have an IP address for the comments, ending with "0".
Is this by design or broken?

Thanks

**Comment by ix5** [comment]
Could be that your setup somehow isn't passing through the real IP addresses for commenters.
This can happen if your proxy server fails to pass the appropriate headers.

See e.g. https://github.com/posativ/isso/issues/735 for some further links

E.g. nginx has `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for`

**Comment by roughnecks** [comment]
I don't know, already have this config in place:

```
  location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://localhost:8100;
  }
```

**Comment by BBaoVanC** [comment]
This is by design, see the `anonymize` function: https://github.com/posativ/isso/blob/64374a8af978f1cfd4a91875c18a309122c7d9ca/isso/utils/__init__.py#L16

**Comment by roughnecks** [comment]
> This is by design, see the `anonymize` function:

Thanks!
